<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="Evidence-based therapy for teens — anxiety, depression, ADHD, peer pressure, academic stress &amp; emotional regulation. Expert adolescent psychologists in Delhi."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/adolescents" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/adolescents" property="og:url" />
    <meta content="Adolescent Therapy &amp; Counselling in Delhi | eMbrace Lives" property="og:title" />
    <meta
      content="Evidence-based therapy for teens — anxiety, depression, ADHD, peer pressure, academic stress &amp; emotional regulation. Expert adolescent psychologists in Delhi."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="Adolescent Therapy &amp; Counselling in Delhi | eMbrace Lives" name="twitter:title" />
    <meta
      content="Evidence-based therapy for teens — anxiety, depression, ADHD, peer pressure, academic stress &amp; emotional regulation. Expert adolescent psychologists in Delhi."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>Adolescent Therapy &amp; Counselling in Delhi | eMbrace Lives</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  <link href="/assets/lead-magnets.css" rel="stylesheet"/>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "WebPage",
      "@id": "https://embracelives.com/adolescents#webpage",
      "url": "https://embracelives.com/adolescents",
      "name": "Adolescent Therapy & Counselling in Delhi | eMbrace Lives",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "Evidence-based therapy for teens — anxiety, depression, ADHD, peer pressure, academic stress & emotional regulation. Expert adolescent psychologists in Delhi."
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div
        class="md:min-h-[calc(100vh-4.4rem)] overflow-hidden flex flex-col items-center justify-center bg-[linear-gradient(360deg,_#FFFFFF_7.69%,_rgba(147,207,239,0.26)_35.1%,_rgba(255,204,0,0.24)_100%)] px-4 md:px-8 lg:px-16 xl:px-30 py-6 relative"
      >
        <div class="flex flex-col items-center justify-center">
          <h1 class="md:text-3xl text-lg font-bold text-center">eMbrace for Adolescents</h1>
          <p class="font-semibold text-sm md:text-lg text-[var(--text-gray)] italic text-center">
            Specialized Assessments, Therapy &amp; Psychiatric Support for Teens
          </p>
        </div>
        <div class="relative w-full flex flex-col items-center justify-center 2xl:mt-30 md:mt-14 -mt-6">
          <div class="flex items-center justify-center w-full gap-2 md:gap-6 relative h-56 md:h-60">
            <img decoding="async" width="600" height="400"
              alt="carousel-img-0"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-30 md:scale-95 scale-170 -translate-x-1/2 -translate-y-1/2 shadow-2xl"
              src="/assets/Hero1-B-ajiMbY.png"
              style="pointer-events: auto; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img fetchpriority="high" decoding="async" width="600" height="400"
              alt="carousel-img-1"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-20 md:scale-75 scale-150 -translate-x-1/2 -translate-y-1/2 -translate-x-[10%] md:translate-x-[0%]"
              src="/assets/Hero2-CZSbv1Ty.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img decoding="async" width="600" height="400"
              alt="carousel-img-2"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-10 md:scale-50 scale-100 -translate-x-1/2 -translate-y-1/2 translate-x-[30%]"
              src="/assets/Hero3-BLDY-4Ve.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img loading="lazy" decoding="async" width="600" height="400"
              alt="carousel-img-3"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-10 md:scale-50 scale-100 -translate-x-1/2 -translate-y-1/2 -translate-x-[130%]"
              src="/assets/Hero4-mSTuGqTP.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img loading="lazy" decoding="async" width="600" height="400"
              alt="carousel-img-4"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-20 md:scale-75 scale-150 -translate-x-1/2 -translate-y-1/2 -translate-x-[90%] md:-translate-x-[100%]"
              src="/assets/Hero2-BYwvac1Z.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            />
          </div>
          <div class="flex items-center justify-center 2xl:mt-40 md:mt-14 -mt-5 gap-4 relative z-20">
            <button aria-label="Previous" class="cursor-pointer">
              <img
                alt="Previous"
                class="w-6 h-6"
                src="data:image/svg+xml,%3csvg%20width='50'%20height='50'%20viewBox='0%200%2050%2050'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20fill-rule='evenodd'%20clip-rule='evenodd'%20d='M16.917%2021.8752H43.7475V28.1252H16.917L27.2073%2038.4155L22.7878%2042.8349L4.95312%2025.0002L22.7878%207.16553L27.2073%2011.5849L16.917%2021.8752Z'%20fill='%23999999'/%3e%3c/svg%3e"
              />
            </button>
            <div class="flex gap-2">
              <span class="h-2 w-2 rounded-full bg-purple-500"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span>
            </div>
            <button aria-label="Next" class="cursor-pointer">
              <img
                alt="Next"
                class="rotate-180 w-6 h-6"
                src="data:image/svg+xml,%3csvg%20width='50'%20height='50'%20viewBox='0%200%2050%2050'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20fill-rule='evenodd'%20clip-rule='evenodd'%20d='M16.917%2021.8752H43.7475V28.1252H16.917L27.2073%2038.4155L22.7878%2042.8349L4.95312%2025.0002L22.7878%207.16553L27.2073%2011.5849L16.917%2021.8752Z'%20fill='%23999999'/%3e%3c/svg%3e"
              />
            </button>
          </div>
        </div>
        <div class="flex flex-col 2xl:mt-12 mt-4 items-center justify-center">
          <p class="font-semibold text-sm text-[var(--text-gray)] text-center italic">
            Empathetic, expert-led care that nurtures resilience and mental wellness.
          </p>
          <p class="font-medium text-sm text-[var(--text-gray)] text-center italic mt-2">
            At eMbrace, we support adolescents through the most formative years of their lives. From academic pressures
            and emotional regulation to identity and peer relationships, our multidisciplinary team offers comprehensive
            assessments, therapy, and psychiatric support. Each care plan is personalized, evidence-based, and focused
            on helping teens thrive in school, at home, and socially.
          </p>
          <a href="/appointment.php"
            class="inline-block w-[70%] md:w-[20%] py-2 rounded-full bg-[var(--blue-fig)] mt-4 md:mt-4 2xl:mt-6 text-white font-medium cursor-pointer"
          >
            Book a Session
          </a>
        </div>
      </div>
      <div
        class="md:min-h-screen overflow-hidden flex flex-col items-center bg-[#D9F2FF] md:mt-12 relative gap-8 md:gap-4"
      >
        <div class="py-6 bg-white w-full relative">
          <h2 class="md:text-3xl text-lg font-bold text-center">Our Services</h2>
          <p class="font-medium text-sm md:text-base text-[var(--text-gray)] italic text-center">
            A full spectrum of support for emotional, behavioral, and learning needs.
          </p>
          <div
            class="md:w-12 md:h-12 w-8 h-8 rounded-full bg-white absolute md:-bottom-5 -bottom-[26%] -left-[1.5%] md:left-0"
          ></div>
          <div
            class="md:w-12 md:h-12 w-8 h-8 rounded-full bg-white absolute md:-bottom-3 md:left-11 -bottom-[15%] left-[5%]"
          ></div>
          <div
            class="md:w-14 md:h-14 w-14 h-14 rounded-full bg-white absolute md:-bottom-6 md:left-22 -bottom-[30%] left-[14%]"
          ></div>
          <div
            class="md:w-12 md:h-12 w-8 h-8 rounded-full bg-white absolute md:-bottom-4 md:left-33 -bottom-[14%] left-[30%]"
          ></div>
          <div
            class="md:w-12 md:h-12 w-8 h-8 rounded-full bg-white absolute md:-bottom-5 -bottom-[26%] -right-[1.5%] md:right-0"
          ></div>
          <div
            class="md:w-12 md:h-12 w-8 h-8 rounded-full bg-white absolute md:-bottom-3 md:right-11 -bottom-[15%] right-[5%]"
          ></div>
          <div
            class="md:w-14 md:h-14 w-14 h-14 rounded-full bg-white absolute md:-bottom-6 md:right-22 -bottom-[28%] right-[14%]"
          ></div>
          <div
            class="md:w-12 md:h-12 w-8 h-8 rounded-full bg-white absolute md:-bottom-4 md:right-33 -bottom-[14%] right-[30%]"
          ></div>
        </div>
        <div class="md:justify-center w-full p-4 py-8 relative flex flex-col md:pt-0 md:p-12 gap-8 md:px-16">
          <div class="h-14 w-14 hidden md:block bg-[#36A72982] rounded-full absolute -left-[2%] top-[10%]"></div>
          <div class="h-14 w-14 hidden md:block bg-[#F5B7A9] rounded-full absolute -bottom-[4%] right-[50%]"></div>
          <div class="h-14 w-14 hidden md:block bg-[#90A7E1] rounded-full absolute -right-[2%] bottom-[20%]"></div>
          <h2 class="md:text-3xl text-lg font-bold text-center">Assessments</h2>
          <p class="font-medium text-sm md:text-base text-[var(--text-gray)] italic text-center">
            Accurate diagnosis and actionable insights for academic and emotional growth.
          </p>
          <div class="2xl:px-12 flex md:flex-row w-full flex-col items-start h-auto gap-8 justify-center">
            <div
              class="bg-[#FFFFFF] pb-6 md:pb-4 2xl:py-10 2xl:gap-8 md:w-[90%] w-full lg:w-[40%] items-center gap-2 px-4 pt-6 z-10 rounded-3xl md:rounded-2xl flex flex-col shadow-[0px_7px_12px_0px_#00000070] md:shadow-[0_2px_6.2px_rgba(0,0,0,0.1)] md:gap-4"
            >
              <img loading="lazy" decoding="async" width="998" height="667"
                alt="Essential Screenings illustration"
                class="md:w-[95%] 2xl:h-[70%] w-[90%] mb-2 md:mt-4"
                src="/assets/Service1-QMda4RQE.svg"
              />
              <div
                class="bg-[#BC70C22E] w-full rounded-xl flex justify-center flex-col items-center md:p-4 px-1 py-2 gap-2"
              >
                <span
                  class="text-base 2xl:text-xl text-[#403D3DC4] font-bold text-center flex gap-2 justify-center items-center"
                  ><div class="w-[70%]">Essential Screenings</div>
                  <div class="w-[30%]">
                    <button
                      aria-label="Toggle details for Essential Screenings"
                      class="bg-[#BC70C2B2] rounded-full p-2"
                    >
                      <img
                        alt=""
                        class="w-6 h-6 transition-transform duration-300"
                        src="data:image/svg+xml,%3csvg%20width='55'%20height='38'%20viewBox='0%200%2055%2038'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M53.9351%207.79555C54.3209%207.31655%2054.6119%206.76348%2054.7914%206.16794C54.9709%205.5724%2055.0355%204.94604%2054.9815%204.32463C54.9274%203.70322%2054.7558%203.09893%2054.4764%202.54626C54.197%201.99359%2053.8153%201.50336%2053.3531%201.10356C52.8908%200.703765%2052.3572%200.402228%2051.7825%200.216173C51.2078%200.0301166%2050.6034%20-0.0368144%2050.0037%200.0191962C49.4041%200.0752068%2048.821%200.253064%2048.2877%200.542614C47.7544%200.832164%2047.2813%201.22774%2046.8955%201.70674L27.5%2025.8245L8.10448%201.70674C7.32534%200.739343%206.20728%200.132315%204.99625%200.0191962C3.78523%20-0.0939223%202.58045%200.296136%201.64694%201.10356C0.713436%201.91099%200.127678%203.06964%200.0185242%204.32463C-0.0906334%205.57963%200.285759%206.82815%201.0649%207.79555L23.9802%2036.2923C24.4103%2036.8268%2024.9486%2037.2569%2025.5568%2037.552C26.165%2037.847%2026.8284%2038%2027.5%2038C28.1716%2038%2028.835%2037.847%2029.4432%2037.552C30.0515%2037.2569%2030.5897%2036.8268%2031.0198%2036.2923L53.9351%207.79555Z'%20fill='white'/%3e%3c/svg%3e"
                      />
                    </button></div
                ></span>
              </div>
              <ul
                class="w-full flex flex-col gap-2 transition-all items-center justify-around duration-300 bg-[#BC70C22E] rounded-2xl px-2 opacity-0 max-h-0 overflow-hidden"
              >
                <li class="flex items-start gap-2">
                  <img loading="lazy" decoding="async" width="100" height="100" alt="" class="w-6 h-6" src="/assets/Diamond-dGu0kMrR.svg" /><span
                    class="text-sm 2xl:text-base text-[#403D3DC4] font-bold"
                    >Risk Evaluations -<span class="font-medium">
                      Evaluate high risk in teenagers for mental health concerns using standardized assessment
                      protocols.</span
                    ></span
                  >
                </li>
                <li class="flex items-start gap-2">
                  <img loading="lazy" decoding="async" width="100" height="100" alt="" class="w-6 h-6" src="/assets/Diamond-dGu0kMrR.svg" /><span
                    class="text-sm 2xl:text-base text-[#403D3DC4] font-bold"
                    >ADHD &amp; Learning Disability Assessments -<span class="font-medium">
                      Focused evaluations for attention, executive functioning, and academic challenges.</span
                    ></span
                  >
                </li>
                <li class="flex items-start gap-2">
                  <img loading="lazy" decoding="async" width="100" height="100" alt="" class="w-6 h-6" src="/assets/Diamond-dGu0kMrR.svg" /><span
                    class="text-sm 2xl:text-base text-[#403D3DC4] font-bold"
                    >WISC (Wechsler Intelligence Scale for Children) -<span class="font-medium">
                      Measures IQ and cognitive strengths.</span
                    ></span
                  >
                </li>
                <li class="flex items-start gap-2">
                  <img loading="lazy" decoding="async" width="100" height="100" alt="" class="w-6 h-6" src="/assets/Diamond-dGu0kMrR.svg" /><span
                    class="text-sm 2xl:text-base text-[#403D3DC4] font-bold"
                    >WRAT (Wide Range Achievement Test) -<span class="font-medium">
                      Evaluates academic skills including reading, math, and spelling.</span
                    ></span
                  >
                </li>
              </ul>
            </div>
            <div
              class="bg-[#FFFFFF] pb-6 md:pb-4 2xl:py-10 2xl:gap-8 md:w-[90%] w-full lg:w-[40%] items-center gap-2 px-4 pt-6 z-10 rounded-3xl md:rounded-2xl flex flex-col shadow-[0px_7px_12px_0px_#00000070] md:shadow-[0_2px_6.2px_rgba(0,0,0,0.1)] md:gap-4"
            >
              <img loading="lazy" decoding="async" width="998" height="665"
                alt="Comprehensive Cognitive &amp; Learning Psychometric Assessments illustration"
                class="md:w-[95%] 2xl:h-[70%] w-[90%] mb-2 md:mt-4"
                src="/assets/Service2-Dqmq_0TO.svg"
              />
              <div
                class="bg-[#BC70C22E] w-full rounded-xl flex justify-center flex-col items-center md:p-4 px-1 py-2 gap-2"
              >
                <span
                  class="text-base 2xl:text-xl text-[#403D3DC4] font-bold text-center flex gap-2 justify-center items-center"
                  ><div class="w-[70%]">Comprehensive Cognitive &amp; Learning Psychometric Assessments</div>
                  <div class="w-[30%]">
                    <button
                      aria-label="Toggle details for Comprehensive Cognitive &amp; Learning Psychometric Assessments"
                      class="bg-[#BC70C2B2] rounded-full p-2"
                    >
                      <img
                        alt=""
                        class="w-6 h-6 transition-transform duration-300"
                        src="data:image/svg+xml,%3csvg%20width='55'%20height='38'%20viewBox='0%200%2055%2038'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M53.9351%207.79555C54.3209%207.31655%2054.6119%206.76348%2054.7914%206.16794C54.9709%205.5724%2055.0355%204.94604%2054.9815%204.32463C54.9274%203.70322%2054.7558%203.09893%2054.4764%202.54626C54.197%201.99359%2053.8153%201.50336%2053.3531%201.10356C52.8908%200.703765%2052.3572%200.402228%2051.7825%200.216173C51.2078%200.0301166%2050.6034%20-0.0368144%2050.0037%200.0191962C49.4041%200.0752068%2048.821%200.253064%2048.2877%200.542614C47.7544%200.832164%2047.2813%201.22774%2046.8955%201.70674L27.5%2025.8245L8.10448%201.70674C7.32534%200.739343%206.20728%200.132315%204.99625%200.0191962C3.78523%20-0.0939223%202.58045%200.296136%201.64694%201.10356C0.713436%201.91099%200.127678%203.06964%200.0185242%204.32463C-0.0906334%205.57963%200.285759%206.82815%201.0649%207.79555L23.9802%2036.2923C24.4103%2036.8268%2024.9486%2037.2569%2025.5568%2037.552C26.165%2037.847%2026.8284%2038%2027.5%2038C28.1716%2038%2028.835%2037.847%2029.4432%2037.552C30.0515%2037.2569%2030.5897%2036.8268%2031.0198%2036.2923L53.9351%207.79555Z'%20fill='white'/%3e%3c/svg%3e"
                      />
                    </button></div
                ></span>
              </div>
              <ul
                class="w-full flex flex-col gap-2 transition-all items-center justify-around duration-300 bg-[#BC70C22E] rounded-2xl px-2 opacity-0 max-h-0 overflow-hidden"
              >
                <li class="flex items-start gap-2">
                  <img loading="lazy" decoding="async" width="100" height="100" alt="" class="w-6 h-6" src="/assets/Diamond-dGu0kMrR.svg" /><span
                    class="text-sm 2xl:text-base text-[#403D3DC4] font-bold"
                    >WIAT (Wechsler Individual Achievement Test) -<span class="font-medium">
                      In-depth academic proficiency testing.</span
                    ></span
                  >
                </li>
                <li class="flex items-start gap-2">
                  <img loading="lazy" decoding="async" width="100" height="100" alt="" class="w-6 h-6" src="/assets/Diamond-dGu0kMrR.svg" /><span
                    class="text-sm 2xl:text-base text-[#403D3DC4] font-bold"
                    >GORT (Gray Oral Reading Test) -<span class="font-medium">
                      Assesses fluency and reading comprehension.</span
                    ></span
                  >
                </li>
                <li class="flex items-start gap-2">
                  <img loading="lazy" decoding="async" width="100" height="100" alt="" class="w-6 h-6" src="/assets/Diamond-dGu0kMrR.svg" /><span
                    class="text-sm 2xl:text-base text-[#403D3DC4] font-bold"
                    >CBRS / Connors / BASC -<span class="font-medium">
                      Behavioral rating scales used to evaluate emotional, behavioral, and social functioning.</span
                    ></span
                  >
                </li>
              </ul>
            </div>
          </div>
          <div class="text-center text-base md:text-lg italic text-[#234394] font-semibold 2xl:text-xl mb-4">
            Gain clarity with structured diagnostic insights and expert feedback.
          </div>
        </div>
      </div>
      <div class="overflow-hidden flex flex-col items-center px-4 md:px-8 lg:px-16 xl:px-20 py-6 relative">
        <div class="md:min-h-screen flex flex-col items-center">
          <h2 class="text-xl md:text-3xl font-bold text-center">Therapy Services</h2>
          <p class="font-medium text-sm md:text-base text-[var(--text-gray)] italic text-center mt-2">
            Supportive spaces where teens feel seen, heard, and understood.
          </p>
          <div class="flex flex-col md:flex-row gap-6 md:gap-4 mt-6">
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img loading="lazy" decoding="async" width="400" height="200" alt="Why Embrace 2" class="w-[90%] md:w-full mb-2" src="/assets/Therapy1-DgnquvMg.svg" />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">
                  Individual Therapy
                </h2>
                <p class="text-sm text-center">
                  For anxiety, mood issues, low self-esteem, identity concerns, and more.
                </p>
              </div>
            </div>
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img loading="lazy" decoding="async" width="400" height="200" alt="Why Embrace 2" class="w-[90%] md:w-full mb-2" src="/assets/Therapy2-Bl6c5u_s.svg" />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">Family Therapy</h2>
                <p class="text-sm text-center">
                  Strengthening communication and connection between teens and their families.
                </p>
              </div>
            </div>
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img loading="lazy" decoding="async" width="400" height="200" alt="Why Embrace 2" class="w-[90%] md:w-full mb-2" src="/assets/Therapy3-CVhirgQ3.svg" />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">Group Therapy</h2>
                <p class="text-sm text-center">
                  Peer-based support for social anxiety, emotional regulation, and shared experiences.
                </p>
              </div>
            </div>
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img loading="lazy" decoding="async" width="400" height="200" alt="Why Embrace 2" class="w-[90%] md:w-full mb-2" src="/assets/Therapy4-DkgC4fh3.svg" />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">Parent Support</h2>
                <p class="text-sm text-center">
                  Coaching to help caregivers navigate adolescent development with empathy and structure.
                </p>
              </div>
            </div>
          </div>
          <p class="font-medium text-sm md:text-base text-[var(--text-gray)] italic text-center mt-4">
            Every session is evidence-based and tailored to the adolescent’s context.
          </p>
          <div class="gap-8 flex flex-col pt-8 mb-4 w-full">
            <h2 class="text-xl md:text-3xl font-bold text-center">Psychiatric Support</h2>
            <p class="font-medium text-sm md:text-base text-[var(--text-gray)] italic text-center">
              When clinical intervention is needed, our in-house psychiatrists are here.
            </p>
            <div class="flex md:gap-8 gap-4 justify-center md:flex-row flex-col">
              <div
                class="border-[2px] border-[#399349] shadow-[0px_2px_4px_0px_#36A729] items-center flex md:gap-8 gap-4 w-full md:w-[40%] rounded-2xl pl-4 px-8 py-4"
              >
                <img loading="lazy" decoding="async" width="100" height="100" alt="" class="h-10 w-10" src="/assets/Psy1-DeFgA123.svg" />
                <p class="font-semibold text-sm md:text-base">Diagnostic Clarification</p>
              </div>
              <div
                class="border-[2px] border-[#399349] shadow-[0px_2px_4px_0px_#36A729] items-center flex md:gap-8 gap-4 w-full md:w-[40%] rounded-2xl pl-4 px-8 py-4"
              >
                <img loading="lazy" decoding="async" width="100" height="100" alt="" class="h-10 w-10" src="/assets/Psy2-C9DvQadH.svg" />
                <p class="font-semibold text-sm md:text-base">Medication Management</p>
              </div>
            </div>
            <div class="flex md:gap-8 gap-4 justify-center">
              <div
                class="border-[2px] border-[#399349] shadow-[0px_2px_4px_0px_#36A729] items-center flex md:gap-8 gap-4 w-full md:w-[40%] rounded-2xl pl-4 px-8 py-4"
              >
                <img loading="lazy" decoding="async" width="100" height="100" alt="" class="h-10 w-10" src="/assets/Psy3-BjjPD7tO.svg" />
                <p class="font-semibold">Collaborative Care Plans</p>
              </div>
            </div>
          </div>
          <p class="font-medium text-sm md:text-base md:mt-4 text-[var(--text-gray)] italic text-center">
            Ethical, cautious, and adolescent-centered psychiatric care.
          </p>
        </div>
        <img
          alt=""
          class="absolute bottom-[30%] right-0 rotate-x-180 hidden md:block"
          src="data:image/svg+xml,%3csvg%20width='66'%20height='80'%20viewBox='0%200%2066%2080'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20cx='26.1005'%20cy='27.2656'%20rx='26.1005'%20ry='27.2656'%20transform='matrix(0.154383%20-0.988011%200.989983%200.141189%2017.957%2051.5752)'%20fill='%23B9F1DA'/%3e%3cellipse%20opacity='0.5'%20cx='26.1005'%20cy='27.2656'%20rx='26.1005'%20ry='27.2656'%20transform='matrix(0.154383%20-0.988011%200.989983%200.141189%200%2072.3008)'%20fill='%2390A7E1'/%3e%3c/svg%3e"
        />
      </div>
      <div
        class="overflow-hidden pb-16 relative w-full min-h-fit md:min-h-screen bg-gradient-to-b from-[#FAF4FF] to-[#F5FAFB] py-20 p-6 md:px-16 md:py-8 gap-6 md:gap-6 text-center flex flex-col justify-center items-center"
      >
        <div class="h-12 w-12 hidden md:block absolute bg-[#90A7E1] rounded-full top-[3.5%] -right-[1.75%]"></div>
        <span class="text-2xl md:text-2xl lg:text-3xl font-bold">What Teens &amp; Parents Say</span>
        <p class="font-medium italic hidden md:block text-xl">
          Testimonials from families who’ve experienced the eMbrace Impact
        </p>
        <div class="flex flex-col gap-8 md:gap-0 md:flex-row md:py-4 z-10 items-stretch">
          <div
            class="lg:w-80 xl:w-90 w-70 bg-white py-10 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 gap-6 custom-shadow"
          >
            <img loading="lazy" decoding="async" width="580" height="317" alt="img1" class="w-50 lg:w-80 xl:w-70" src="/assets/Gift_test-1-Bw1nidTz.svg" />
            <p class="w-50 font-normal text-sm md:text-center text-start">
              “Therapy helped my child open up emotionally and feel more in control of her feelings.”
            </p>
          </div>
          <div
            class="lg:w-80 xl:w-90 w-70 bg-white py-10 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 gap-6 custom-shadow"
          >
            <img loading="lazy" decoding="async" width="547" height="317" alt="img2" class="w-50 lg:w-80 xl:w-70" src="/assets/Gift_test-2-wR21sUIx.svg" />
            <p class="w-50 font-normal text-sm md:text-center text-start">
              “We finally understood the root of his school challenges after the assessment.”
            </p>
          </div>
          <div
            class="lg:w-80 xl:w-90 w-70 bg-white py-10 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 gap-6 custom-shadow"
          >
            <img loading="lazy" decoding="async" width="520" height="317" alt="img3" class="w-50 lg:w-80 xl:w-70" src="/assets/Gift_test-3-CCKZ9D9K.svg" />
            <p class="w-50 font-normal text-sm md:text-center text-start">
              “The care team made us feel supported every step of the way.”
            </p>
          </div>
        </div>
      </div>
      <div
        class="md:min-h-screen overflow-hidden flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-20 py-6 md:py-10 relative bg-gradient-to-b from-[#ffffff] to-[#E6FFFD99]/80"
      >
        <div class="bg-[#90A7E178] w-12 h-12 hidden md:block rounded-full absolute -right-[1.5%] bottom-[30%]"></div>
        <h2 class="text-xl md:text-3xl font-bold text-center">See Wellbeing Spaces in Action</h2>
        <p class="font-medium text-[var(--text-gray)] italic text-center">
          Personalized, empathetic spaces designed for comfort and growth
        </p>
        <div class="relative flex mt-6 items-center justify-center w-full mx-auto">
          <img loading="lazy" decoding="async" width="1200" height="1600"
            alt="carousel-1"
            class="md:w-[90%] 2xl:h-[50rem] h-[30rem] object-cover rounded-xl shadow"
            src="/assets/carousel1-BUqaO1dK.jpg"
          /><button
            class="absolute top-1/2 left-3 md:left-16 2xl:left-25 -translate-y-1/2 z-10 p-3 md:p-4 bg-white/70 rounded-full shadow hover:bg-white"
          >
            <img
              alt="Previous"
              class="md:w-4 md:h-4 w-3 h-3"
              src="data:image/svg+xml,%3csvg%20width='30'%20height='39'%20viewBox='0%200%2030%2039'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M1.694%2017.0118C-0.0713594%2018.2009%20-0.0713545%2020.7991%201.694%2021.9882L24.824%2037.568C26.8167%2038.9102%2029.5%2037.4824%2029.5%2035.0798L29.5%203.92019C29.5%201.51762%2026.8167%200.0897827%2024.824%201.432L1.694%2017.0118Z'%20fill='%23234394'/%3e%3c/svg%3e"
            /></button
          ><button
            class="absolute top-1/2 right-3 md:right-16 2xl:right-25 -translate-y-1/2 z-10 p-3 md:p-4 bg-white/70 rounded-full shadow hover:bg-white"
          >
            <img
              alt="Next"
              class="rotate-180 md:w-4 md:h-4 w-3 h-3"
              src="data:image/svg+xml,%3csvg%20width='30'%20height='39'%20viewBox='0%200%2030%2039'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M1.694%2017.0118C-0.0713594%2018.2009%20-0.0713545%2020.7991%201.694%2021.9882L24.824%2037.568C26.8167%2038.9102%2029.5%2037.4824%2029.5%2035.0798L29.5%203.92019C29.5%201.51762%2026.8167%200.0897827%2024.824%201.432L1.694%2017.0118Z'%20fill='%23234394'/%3e%3c/svg%3e"
            />
          </button>
        </div>
      </div>
      <div
        class="md:min-h-screen pb-20 md:p-16 bg-gradient-to-b from-[#E6FFFD99] to-[#FEF9FC] justify-center items-center flex p-6 font-sans relative overflow-hidden drop-shadow-xs"
      >
        <div class="h-12 w-12 hidden md:block bg-[#B9F1DA] rounded-full right-[10%] bottom-[0.25%] absolute"></div>
        <div class="h-12 w-12 hidden md:block bg-[#EF917B69] rounded-full -left-[0.25%] top-[40%] absolute"></div>
        <div class="max-w-3xl mx-auto">
          <div class="text-center mb-8">
            <h2 class="text-2xl xl:text-3xl font-bold text-gray-900">Frequently asked questions</h2>
          </div>
          <div class="space-y-4 mb-12">
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >How do I know if my teen needs therapy or assessment?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200 rotate-45"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-[1000px] py-2 opacity-100"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      If you notice persistent academic stress, emotional changes, behavioral concerns, or social
                      withdrawal, an evaluation or therapy consultation can help bring clarity and direction.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >Do you offer support for learning disabilities and ADHD?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      Yes. We offer comprehensive cognitive and learning assessments along with therapy tailored to
                      support executive functioning, attention, and academic success.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >Can I be involved in my teen’s care?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                       Absolutely. We believe in a collaborative approach that includes caregivers, while maintaining
                      adolescent confidentiality and autonomy.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <a href="/appointment.php"
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  > Are sessions available online?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </a>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      Yes, both assessments and therapy sessions can be scheduled remotely for flexibility and
                      convenience.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <p class="xl:text-lg font-semibold text-gray-800 text-center">
            Have more questions? Write to us at
            <a class="text-[#234394]" href="mailto:info@embracelives.com">info@embracelives.com</a>
          </p>
        </div>
      </div>
      <!-- LOCATION-LINKS:START (generated by generate-location-links.js — do not edit by hand) -->
<div class="px-6 md:px-16 bg-white">
<div class="max-w-7xl mx-auto">
<section class="emb-nearby" aria-labelledby="emb-nearby-title">
  <h2 class="emb-nearby__title" id="emb-nearby-title">Teen Counselling across Delhi NCR</h2>
  <p class="emb-nearby__sub">We offer teen counselling at eMbrace centres throughout Delhi and the wider NCR. Choose the location closest to you.</p>
  <div class="emb-nearby__cols">
    <div class="emb-nearby__group">
      <ul class="emb-nearby__list emb-nearby__list--wide">
      <li><a href="/locations/teen-counselling-in-delhi">Teen Counselling in Delhi</a></li>
      <li><a href="/locations/teen-counselling-in-south-delhi">Teen Counselling in South Delhi</a></li>
      <li><a href="/locations/teen-counselling-in-saket">Teen Counselling in Saket</a></li>
      <li><a href="/locations/teen-counselling-in-hauz-khas">Teen Counselling in Hauz Khas</a></li>
      <li><a href="/locations/teen-counselling-in-green-park">Teen Counselling in Green Park</a></li>
      <li><a href="/locations/teen-counselling-in-greater-kailash">Teen Counselling in Greater Kailash</a></li>
      <li><a href="/locations/teen-counselling-in-defence-colony">Teen Counselling in Defence Colony</a></li>
      <li><a href="/locations/teen-counselling-in-vasant-kunj">Teen Counselling in Vasant Kunj</a></li>
      <li><a href="/locations/teen-counselling-in-gurgaon">Teen Counselling in Gurgaon</a></li>
      <li><a href="/locations/teen-counselling-in-noida">Teen Counselling in Noida</a></li>
      </ul>
    </div>
  </div>
  <a class="emb-nearby__more" href="/locations">View all eMbrace locations &rsaquo;</a>
</section>
</div>
</div>
<!-- LOCATION-LINKS:END -->
      <?php include __DIR__ . '/components/lead-magnet-band-child.php'; ?>
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  <?php include __DIR__ . '/components/lead-magnet-popup.php'; ?>
<script src="/assets/lead-magnets.js"></script>
<script>EmbraceLM.popup({ id: 'lm-popup' });</script>
</body>
</html>
