<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="Understand eMbrace booking, cancellation &amp; refund policies for therapy sessions. Learn about rescheduling, payment terms &amp; session guidelines."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/bookingandCancellation" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/bookingandCancellation" property="og:url" />
    <meta content="Booking &amp; Cancellation Policy | eMbrace Lives" property="og:title" />
    <meta
      content="Understand eMbrace booking, cancellation &amp; refund policies for therapy sessions. Learn about rescheduling, payment terms &amp; session guidelines."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="Booking &amp; Cancellation Policy | eMbrace Lives" name="twitter:title" />
    <meta
      content="Understand eMbrace booking, cancellation &amp; refund policies for therapy sessions. Learn about rescheduling, payment terms &amp; session guidelines."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>Booking &amp; Cancellation Policy | eMbrace Lives</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  
  
  
  
  
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "WebPage",
        "@id": "https://embracelives.com/bookingandCancellation#webpage",
        "url": "https://embracelives.com/bookingandCancellation",
        "name": "Booking & Cancellation Policy | eMbrace Lives",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Understand eMbrace booking, cancellation & refund policies for therapy sessions. Learn about rescheduling, payment terms & session guidelines."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div class="flex flex-col items-center justify-center bg-white px-4 py-6 max-w-6xl mx-auto">
        <h4 class="text-lg text-black mx-auto py-2 font-bold text-center lg:text-2xl">
          Booking &amp; Cancellation of Services
        </h4>
        <p class="text-sm text-[#403D3D] text-left [word-spacing:0.4em] pt-2">
          Users can book therapy sessions using their registered Account. Users can opt for different therapy packages
          depending on their needs and requirements. All payments are to be made in advance. Every therapy session is
          time bound and can last up to 50 minutes depending on the User’s needs and requirements. In case the duration
          of a session is extended, User shall be liable to pay additional fee for the extended duration. Please note
          that the fee paid needs to be used within 1 month of payment done. In case of any emergencies or other
          unforeseen reasons, you can cancel an appointment by giving a 12-hour prior written notice through email at
          info@embracelives.com. If the session cannot be scheduled or continued due to a technical glitch, we may
          reschedule the session to a later date mutually agreeable to you and the psychologist. We do not allow refunds
          for therapy sessions.
        </p>
        <h4 class="text-lg text-black mx-auto pt-5 font-bold text-center lg:text-2xl">
          Cancellation and Refund Policy
        </h4>
        <p class="text-sm text-[#403D3D] text-left [word-spacing:0.4em] pt-4">
          We understand that sometimes plans change and you may need to cancel a scheduled therapy session. To do so,
          please contact us at least 24 hours in advance of your appointment to reschedule the booked appointment.
          Please note cancellations made with less than 24 hours’ notice will be taken as No-Show and charged in full.
          We DO NOT offer refunds for sessions booked unless exceptional circumstances.
        </p>
        <h4 class="text-lg text-black mx-auto pt-5 font-bold text-center lg:text-2xl">Disclaimer</h4>
        <p class="text-sm text-[#403D3D] text-left [word-spacing:0.4em] pt-4">
          <a class="text-[#234394] cursor-pointer underline" href="https://www.embracelives.com/"
            >www.embracelives.com</a
          >
          is not equipped to handle medical or psychological emergencies. Our services are not intended for crisis
          situations, which may include, but are not limited to, thoughts of self-harm, suicidal ideation, or symptoms
          of severe clinical disorders such as schizophrenia and other psychotic conditions. In such instances,
          immediate in-person medical attention is the most suitable form of assistance. If you find yourself facing any
          of these challenges, or if you are contemplating suicide or feel that you pose a risk to yourself or others,
          we implore you to seek immediate help. Please call at the mentioned helplines numbers or proceed to the
          nearest hospital or emergency room to connect with medical professionals like psychiatrists, social workers,
          counselors, or therapists face-to-face. In the event of any medical or psychological health emergency, it is
          also advisable to involve a trusted family member or friend who can provide support during this critical time.
          Remember, your safety is paramount, and professional in-person support is essential in an emergency.
        </p>
        <h4 class="text-lg text-black mx-auto pt-5 font-bold text-center lg:text-2xl">Emergency Helpline</h4>
        <p class="text-sm text-[#403D3D] text-left [word-spacing:0.4em] pt-4">
          <span class="text-sm text-[#234394] text-left font-semibold">Sangath,</span> <br />
          <a class="text-[#234394] cursor-pointer underline" href="https://outlive.in/get-help-now"
            >https://outlive.in/get-help-now</a
          >
          Sangath Well-being Center- If the crisis involves domestic or sexual violence, discrimination due to caste or
          sexuality, grief or academic pressure, Sangath has curated a list of organisations working in these
          psychosocial spaces that you can reach out to for help.
        </p>
        <p class="text-sm text-[#403D3D] text-left [word-spacing:0.4em] pt-4">
          <span class="text-sm text-[#234394] text-left font-semibold">iCall 9372048501, 022-25521111</span>
          <br />ICALL@TISS.EDU -iCall- iCall is a service from TISS, run by trained mental health professionals. iCALL
          provides emotional support, information and referral services to individuals in psycho-social distress, across
          the lifespan and across different gender and sexual identities.
          <a class="underline hover:cursor-pointer" href="http://icallhelpline.org/">http://icallhelpline.org/</a>
          MONDAY TO SATURDAY, 8 AM - 10 PM
        </p>
        <p class="text-sm text-[#403D3D] text-left [word-spacing:0.4em] pt-4">
          <span class="text-sm text-[#234394] text-left font-semibold">National Helpline (NIMHANS), 080 46110007</span>
          <br />NIMHANS- This is a helpline for anyone experiencing mental health distress during the COVID 19 crisis by
          National Institute of Mental Health &amp; Neuro Sciences Bengaluru.
        </p>
      </div>
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  </body>
</html>
