<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="Evidence-based couples therapy — communication issues, conflict resolution, pre-marital counselling &amp; relationship support. Expert therapists in Delhi."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/couples" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/couples" property="og:url" />
    <meta content="Couples Therapy &amp; Relationship Counselling in Delhi | eMbrace Lives" property="og:title" />
    <meta
      content="Evidence-based couples therapy — communication issues, conflict resolution, pre-marital counselling &amp; relationship support. Expert therapists in Delhi."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="Couples Therapy &amp; Relationship Counselling in Delhi | eMbrace Lives" name="twitter:title" />
    <meta
      content="Evidence-based couples therapy — communication issues, conflict resolution, pre-marital counselling &amp; relationship support. Expert therapists in Delhi."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>Couples Therapy &amp; Relationship Counselling in Delhi | eMbrace Lives</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "WebPage",
        "@id": "https://embracelives.com/couples#webpage",
        "url": "https://embracelives.com/couples",
        "name": "Couples Therapy & Relationship Counselling in Delhi | eMbrace Lives",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Evidence-based couples therapy — communication issues, conflict resolution, pre-marital counselling & relationship support. Expert therapists in Delhi."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div
        class="md:min-h-[calc(100vh-4.4rem)] overflow-hidden flex flex-col items-center justify-center bg-gradient-to-b to-[#F3779830] from-[#FFFFFF] px-4 md:px-8 lg:px-16 xl:px-30 py-6 relative"
      >
        <div class="bg-[#F4433666] h-14 hidden w-14 md:block rounded-full absolute -bottom-[1%] right-[20%]"></div>
        <div class="flex flex-col items-center justify-center">
          <h1 class="md:text-3xl text-lg font-bold text-center">eMbrace for Couples</h1>
          <p class="font-semibold text-sm md:text-lg text-[var(--text-gray)] text-center italic">
            Science-Backed Support for Healthier Communication &amp; Deeper Connection
          </p>
        </div>
        <div class="relative w-full flex flex-col items-center justify-center 2xl:mt-30 md:mt-14 -mt-6">
          <div class="flex items-center justify-center w-full gap-2 md:gap-6 relative h-56 md:h-60">
            <img
              alt="carousel-img-0"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-30 md:scale-95 scale-170 -translate-x-1/2 -translate-y-1/2 shadow-2xl"
              src="/assets/Hero1-iglZ4lXe.png"
              style="pointer-events: auto; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-1"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-20 md:scale-75 scale-150 -translate-x-1/2 -translate-y-1/2 -translate-x-[10%] md:translate-x-[0%]"
              src="/assets/Hero2-Bon_ICe0.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-2"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-10 md:scale-50 scale-100 -translate-x-1/2 -translate-y-1/2 translate-x-[30%]"
              src="/assets/Hero3-DQRTtdUA.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-3"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-10 md:scale-50 scale-100 -translate-x-1/2 -translate-y-1/2 -translate-x-[130%]"
              src="/assets/Hero4-DfdI1WDF.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-4"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-20 md:scale-75 scale-150 -translate-x-1/2 -translate-y-1/2 -translate-x-[90%] md:-translate-x-[100%]"
              src="/assets/Hero5-DZPe7lhE.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            />
          </div>
          <div class="flex items-center justify-center 2xl:mt-40 md:mt-14 -mt-5 gap-4 relative z-20">
            <button aria-label="Previous" class="cursor-pointer">
              <img
                alt="Previous"
                class="w-6 h-6"
                src="data:image/svg+xml,%3csvg%20width='50'%20height='50'%20viewBox='0%200%2050%2050'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20fill-rule='evenodd'%20clip-rule='evenodd'%20d='M16.917%2021.8752H43.7475V28.1252H16.917L27.2073%2038.4155L22.7878%2042.8349L4.95312%2025.0002L22.7878%207.16553L27.2073%2011.5849L16.917%2021.8752Z'%20fill='%23999999'/%3e%3c/svg%3e"
              />
            </button>
            <div class="flex gap-2">
              <span class="h-2 w-2 rounded-full bg-purple-500"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span>
            </div>
            <button aria-label="Next" class="cursor-pointer">
              <img
                alt="Next"
                class="rotate-180 w-6 h-6"
                src="data:image/svg+xml,%3csvg%20width='50'%20height='50'%20viewBox='0%200%2050%2050'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20fill-rule='evenodd'%20clip-rule='evenodd'%20d='M16.917%2021.8752H43.7475V28.1252H16.917L27.2073%2038.4155L22.7878%2042.8349L4.95312%2025.0002L22.7878%207.16553L27.2073%2011.5849L16.917%2021.8752Z'%20fill='%23999999'/%3e%3c/svg%3e"
              />
            </button>
          </div>
        </div>
        <div class="flex flex-col 2xl:mt-12 mt-4 lg:mt-0 items-center justify-center">
          <p class="font-medium text-sm md:text-base text-[var(--text-gray)] text-center italic">
            At eMbrace, we offer personalized couples therapy using internationally recognized models like the Gottman
            Method—proven to help partners improve emotional connection, resolve conflict, and build lasting intimacy
            across dating, marriage, or long-term relationships.<br />Therapy that meets you where you are—whether
            you're dating, living together, married, or rebuilding trust.
          </p>
          <a href="/appointment.php"
            class="inline-block w-[70%] md:w-[24.25%] py-2 rounded-full bg-[var(--blue-fig)] mt-4 md:mt-2 2xl:mt-6 text-white font-medium cursor-pointer"
          >
            Request Session
          </a>
        </div>
      </div>
      <div
        class="md:min-h-screen md:justify-around 2xl:justify-center overflow-hidden w-full p-2 relative flex flex-col md:p-12 gap-8 md:px-16"
      >
        <div class="h-14 w-14 hidden md:block bg-[#FFCC0073] rounded-full absolute -left-[2%] bottom-[30%]"></div>
        <div class="h-14 w-14 hidden md:block bg-[#90A7E187] rounded-full absolute -bottom-[4%] right-[30%]"></div>
        <div class="flex flex-col items-center justify-center gap-4">
          <h1 class="md:text-3xl text-lg font-bold text-center 2xl:text-5xl">What We Offer for Couples</h1>
        </div>
        <div class="2xl:px-12 flex md:flex-row w-full flex-col items-stretch h-auto gap-8 justify-center px-2 md:px-0">
          <div
            class="bg-gradient bg-[#FFF7D747] pb-2 md:pb-4 2xl:py-10 2xl:gap-8 md:w-[90%] w-full lg:w-[40%] items-center px-4 md:h-auto pt-6 md:pt-0 z-10 rounded-xl md:rounded-2xl flex flex-col shadow-[0_2px_6.2px_rgba(0,0,0,0.1)] md:gap-4"
          >
            <img
              alt=""
              class="md:w-[90%] md:h-40 2xl:h-[70%] w-[90%] md:mb-0 mb-2 md:mt-4"
              src="/assets/What1-CBWtBqC0.svg"
            /><span class="text-lg 2xl:text-2xl 3xl:text-5xl font-semibold text-center mb-2"
              >Relationship &amp; Pre-Marital Counseling</span
            ><span class="font-medium text-center md:pb-4 pb-2"
              >For couples looking to build strong foundations or deepen emotional connection.</span
            >
            <div class="px-6 py-4 2xl:py-8 w-full h-auto justify-center flex flex-col pb-2">
              <li>Compatibility &amp; communication coaching</li>
              <li>Conflict resolution &amp; emotional safety</li>
              <li>Navigating expectations &amp; long-term goals</li>
            </div>
          </div>
          <div
            class="bg-gradient bg-[#FFF7D747] pb-2 md:pb-4 2xl:py-10 2xl:gap-8 md:w-[90%] w-full lg:w-[40%] items-center px-4 md:h-auto pt-6 md:pt-0 z-10 rounded-xl md:rounded-2xl flex flex-col shadow-[0_2px_6.2px_rgba(0,0,0,0.1)] md:gap-4"
          >
            <img
              alt=""
              class="md:w-[90%] md:h-40 2xl:h-[70%] w-[90%] md:mb-0 mb-2 md:mt-4"
              src="/assets/What2-CGGveSaT.svg"
            /><span class="text-lg 2xl:text-2xl 3xl:text-5xl font-semibold text-center mb-2"
              >Marriage &amp; Partnership Therapy</span
            ><span class="font-medium text-center md:pb-4 pb-2"
              >Restore emotional intimacy, manage recurring conflicts &amp; strengthen commitment.</span
            >
            <div class="px-6 py-4 2xl:py-8 w-full h-auto justify-center flex flex-col pb-2">
              <li>Gottman-based therapy &amp; emotion-focused interventions</li>
              <li>Managing trust issues, infidelity &amp; resentment</li>
              <li>Rebuilding after major life transitions</li>
            </div>
          </div>
          <div
            class="bg-gradient bg-[#FFF7D747] pb-2 md:pb-4 2xl:py-10 2xl:gap-8 md:w-[90%] w-full lg:w-[40%] items-center px-4 md:h-auto pt-6 md:pt-0 z-10 rounded-xl md:rounded-2xl flex flex-col shadow-[0_2px_6.2px_rgba(0,0,0,0.1)] md:gap-4"
          >
            <img
              alt=""
              class="md:w-[90%] md:h-40 2xl:h-[70%] w-[90%] md:mb-0 mb-2 md:mt-4"
              src="/assets/What3-7sJb5i9K.svg"
            /><span class="text-lg 2xl:text-2xl 3xl:text-5xl font-semibold text-center mb-2"
              >Therapy for Separation, Divorce, or Co-Parenting</span
            ><span class="font-medium text-center md:pb-4 pb-2"
              >Support through transitions—respectful closure or co-parenting with empathy.</span
            >
            <div class="px-6 py-4 2xl:py-8 w-full h-auto justify-center flex flex-col pb-2">
              <li>Co-parenting agreements &amp; emotional boundaries</li>
              <li>Navigating grief, guilt, and healing</li>
              <li>Ensuring child well-being during transitions</li>
            </div>
          </div>
        </div>
      </div>
      <div
        class="overflow-hidden xl:justify-center relative md:min-h-screen w-full p-4 md:p-16 pb-20 bg-[#FBF7F9] justify-center flex flex-col"
      >
        <div class="h-15 w-15 rounded-full absolute hidden md:block bg-[#BEEDB9] -bottom-[5%] left-[9%]"></div>
        <div class="h-15 w-15 rounded-full absolute hidden md:block bg-[#FF8E0078] -right-[2.5%] bottom-[40%]"></div>
        <div class="h-15 w-15 rounded-full absolute hidden md:block bg-[#F5D1D6] -left-[2.5%] top-[30%]"></div>
        <span class="text-center text-2xl w-full md:text-3xl lg:text-4xl 2xl:text-5xl font-bold">How it works?</span>
        <div class="hidden md:flex justify-center w-full py-[3rem]">
          <div class="relative w-full max-w-4xl 2xl:max-w-6xl">
            <div
              class="absolute left-1/2 transform -translate-x-1/2 w-0.75 bg-[#7F7F7F] z-0 -mt-6 -mb-6 h-[calc(100%+3rem)]"
            >
              <div
                class="absolute top-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-3 h-3 bg-[#7F7F7F] rounded-full z-10"
              ></div>
              <div
                class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2 w-3 h-3 bg-[#7F7F7F] rounded-full z-10"
              ></div>
            </div>
            <div class="flex items-start mb-5 2xl:mb-20 relative z-10">
              <div class="w-1/2 pr-8 text-left">
                <h3 class="lg:text-2xl 2xl:text-3xl font-bold text-[#4562AD]">Step 1</h3>
                <p class="w-[70%] text-gray-600 font-medium text-lg 2xl:text-xl">
                  Book a consultation for both partners
                </p>
              </div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2"></div>
            </div>
            <div class="flex items-start mb-5 2xl:mb-20 relative z-10">
              <div class="w-1/2"></div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2 pl-8 text-right flex items-end flex-col">
                <h3 class="lg:text-2xl 2xl:text-3xl font-bold text-[#4562AD]">Step 2</h3>
                <p class="w-[70%] text-gray-600 font-medium text-lg 2xl:text-xl">
                  Relationship mapping &amp; initial goal setting
                </p>
              </div>
            </div>
            <div class="flex items-start mb-5 2xl:mb-20 relative z-10">
              <div class="w-1/2 pr-8 text-left">
                <h3 class="lg:text-2xl 2xl:text-3xl font-bold text-[#4562AD]">Step 3</h3>
                <p class="w-[70%] text-gray-600 font-medium text-lg 2xl:text-xl">
                  Begin structured therapy with expert psychologist
                </p>
              </div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2"></div>
            </div>
            <div class="flex items-start relative z-10">
              <div class="w-1/2"></div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2 pl-8 text-right flex items-end flex-col">
                <h3 class="lg:text-2xl 2xl:text-3xl font-bold text-[#4562AD]">Step 4</h3>
                <p class="w-[70%] text-gray-600 font-medium text-lg 2xl:text-xl">
                  Ongoing support &amp; progress reviews
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="block md:hidden px-6 py-12 mt-10 relative">
          <div class="absolute top-0 h-full w-0.75 bg-[#7F7F7F]">
            <div
              class="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 w-4 h-4 bg-[#7F7F7F] rounded-full z-10"
            ></div>
            <div
              class="absolute bottom-0 left-1/2 -translate-x-1/2 translate-y-1/2 w-4 h-4 bg-[#7F7F7F] rounded-full z-10"
            ></div>
          </div>
          <div class="flex items-start mb-10 relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">Step 1</h3>
              <p class="text-gray-600 font-medium text-sm">Book a consultation for both partners</p>
            </div>
          </div>
          <div class="flex items-start mb-10 relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">Step 2</h3>
              <p class="text-gray-600 font-medium text-sm">Relationship mapping &amp; initial goal setting</p>
            </div>
          </div>
          <div class="flex items-start mb-10 relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">Step 3</h3>
              <p class="text-gray-600 font-medium text-sm">Begin structured therapy with expert psychologist</p>
            </div>
          </div>
          <div class="flex items-start relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">Step 4</h3>
              <p class="text-gray-600 font-medium text-sm">Ongoing support &amp; progress reviews</p>
            </div>
          </div>
        </div>
      </div>
      <div
        class="overflow-hidden pb-16 relative w-full min-h-fit md:min-h-screen bg-gradient-to-b from-[#FAF4FF] to-[#F5FAFB] py-20 p-6 md:px-16 md:py-8 gap-6 md:gap-6 text-center flex flex-col justify-center items-center"
      >
        <div class="h-12 w-12 hidden md:block absolute bg-[#90A7E187] rounded-full -bottom-[3.5%] left-[20%]"></div>
        <img
          alt=""
          class="md:block hidden h-12 w-12 absolute right-[0%] bottom-[4%]"
          src="data:image/svg+xml,%3csvg%20width='126'%20height='128'%20viewBox='0%200%20126%20128'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M125.242%2064C125.242%2049.1933%20120.228%2034.8446%20111.055%2023.3988C101.882%2011.9531%2089.1172%204.11839%2074.9353%201.22974C60.7535%20-1.65891%2046.0322%200.57719%2033.2799%207.55704C20.5276%2014.5369%2010.5332%2025.8286%204.99972%2039.5083C-0.533772%2053.1879%20-1.26401%2068.409%202.93341%2082.5782C7.13084%2096.7474%2015.9962%20108.988%2028.019%20117.214C40.0418%20125.44%2054.4782%20129.143%2068.8682%20127.692C83.2583%20126.241%2096.7118%20119.725%20106.936%20109.255L62.7422%2064H125.242Z'%20fill='%23FFCC00'%20fill-opacity='0.45'/%3e%3c/svg%3e"
        /><span class="text-2xl md:text-3xl lg:text-4xl font-bold">What Our Clients Say</span>
        <div class="flex flex-col gap-8 md:gap-0 md:flex-row md:py-4 z-10 items-stretch">
          <div
            class="lg:w-80 xl:w-90 w-70 bg-white py-10 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 gap-6 custom-shadow"
          >
            <img alt="img1" class="w-50 lg:w-80 xl:w-70" src="/assets/Gift_test-1-Bw1nidTz.svg" />
            <p class="w-50 font-normal text-sm md:text-center text-start">
              "We were stuck in a cycle of fights &amp; miscommunication. Therapy at eMbrace helped us rebuild our
              connection &amp; understand each other better."
            </p>
          </div>
          <div
            class="lg:w-80 xl:w-90 w-70 bg-white py-10 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 gap-6 custom-shadow"
          >
            <img alt="img2" class="w-50 lg:w-80 xl:w-70" src="/assets/Gift_test-2-wR21sUIx.svg" />
            <p class="w-50 font-normal text-sm md:text-center text-start">
              "Pre-marital therapy helped us align on our expectations before marriage. The Gottman approach was
              eye-opening!"
            </p>
          </div>
          <div
            class="lg:w-80 xl:w-90 w-70 bg-white py-10 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 gap-6 custom-shadow"
          >
            <img alt="img3" class="w-50 lg:w-80 xl:w-70" src="/assets/Gift_test-3-CCKZ9D9K.svg" />
            <p class="w-50 font-normal text-sm md:text-center text-start">
              We've always struggled solving conflicts, taking professional help was such a refreshing experience.
            </p>
          </div>
        </div>
        <p class="text-[#4562AD] font-medium italic hidden md:block text-xl">
           Take the first step toward a stronger relationship.
        </p>
      </div>
      <div
        class="md:min-h-screen overflow-visible flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-20 py-6 md:py-10 relative bg-gradient-to-b from-[#ffffff] to-[#E6FFFD99]/80"
      >
        <h1 class="text-xl md:text-3xl font-bold text-center">See Wellbeing Spaces in Action</h1>
        <p class="font-medium text-[var(--text-gray)] italic text-center">
          Personalized, empathetic spaces designed for comfort and growth
        </p>
        <div class="relative flex mt-6 items-center justify-center w-full mx-auto">
          <img
            alt="carousel-1"
            class="md:w-[90%] 2xl:h-[50rem] h-[30rem] object-cover rounded-xl shadow"
            src="/assets/carousel1-BUqaO1dK.jpg"
          /><button
            class="absolute top-1/2 left-3 md:left-16 2xl:left-25 -translate-y-1/2 z-10 p-3 md:p-4 bg-white/70 rounded-full shadow hover:bg-white"
          >
            <img
              alt="Previous"
              class="md:w-4 md:h-4 w-3 h-3"
              src="data:image/svg+xml,%3csvg%20width='30'%20height='39'%20viewBox='0%200%2030%2039'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M1.694%2017.0118C-0.0713594%2018.2009%20-0.0713545%2020.7991%201.694%2021.9882L24.824%2037.568C26.8167%2038.9102%2029.5%2037.4824%2029.5%2035.0798L29.5%203.92019C29.5%201.51762%2026.8167%200.0897827%2024.824%201.432L1.694%2017.0118Z'%20fill='%23234394'/%3e%3c/svg%3e"
            /></button
          ><button
            class="absolute top-1/2 right-3 md:right-16 2xl:right-25 -translate-y-1/2 z-10 p-3 md:p-4 bg-white/70 rounded-full shadow hover:bg-white"
          >
            <img
              alt="Next"
              class="rotate-180 md:w-4 md:h-4 w-3 h-3"
              src="data:image/svg+xml,%3csvg%20width='30'%20height='39'%20viewBox='0%200%2030%2039'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M1.694%2017.0118C-0.0713594%2018.2009%20-0.0713545%2020.7991%201.694%2021.9882L24.824%2037.568C26.8167%2038.9102%2029.5%2037.4824%2029.5%2035.0798L29.5%203.92019C29.5%201.51762%2026.8167%200.0897827%2024.824%201.432L1.694%2017.0118Z'%20fill='%23234394'/%3e%3c/svg%3e"
            />
          </button>
        </div>
      </div>
      <div
        class="md:min-h-screen pb-20 md:p-16 bg-gradient-to-b from-[#E6FFFD99] to-[#FEF9FC] justify-center items-center flex p-6 font-sans relative overflow-hidden drop-shadow-xs"
      >
        <div class="h-12 w-12 hidden md:block bg-[#BE62796B] rounded-full -right-[2%] top-[10%] absolute"></div>
        <div class="h-12 w-12 hidden md:block bg-[#90A7E19C] rounded-full -left-[2%] top-[40%] absolute"></div>
        <div class="h-12 w-12 hidden md:block bg-[#F2B81B5E] rounded-full -left-[2%] bottom-[30%] absolute"></div>
        <div class="h-12 w-12 hidden md:block bg-[#BEEDB9] rounded-full -right-[2%] absolute bottom-[20%]"></div>
        <div class="h-14 w-14 hidden md:block bg-[#FF8E0080] rounded-full absolute -bottom-[3.5%] left-[15%]"></div>
        <div class="max-w-3xl mx-auto">
          <div class="text-center mb-8">
            <h1 class="text-2xl xl:text-3xl font-bold text-gray-900">Frequently asked questions</h1>
          </div>
          <div class="space-y-4 mb-12">
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <a href="/appointment.php"
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >Do both partners need to attend every session?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200 rotate-45"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </a>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-[1000px] py-2 opacity-100"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      Not always. Some sessions may begin individually, especially during the assessment phase. Your
                      therapist will guide you on the best structure.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >Is this therapy only for married couples?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      No, our services support all types of relationships—dating, live-in, married, or separated.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >What is couples therapy not?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      Couples therapy is not about taking sides, offering legal advice, or assigning blame. The
                      therapist acts as a neutral facilitator—not an advocate for either partner.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >Does couples therapy always continue once it starts?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      Not always. Therapy may be paused or redirected in cases involving ongoing infidelity, domestic
                      violence, or high-risk situations that require individual safety and stabilization first.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >What does a couples therapist actually do?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      A couples therapist helps facilitate open, respectful, and goal-oriented dialogue between
                      partners. Using evidence-based approaches like the Gottman Method, they guide couples in improving
                      communication, managing conflict, and rebuilding emotional connection.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
              <button
                class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
              >
                <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                  >Can we come for therapy even if we’re not sure we want to stay together?</span
                ><img
                  alt="toggle"
                  class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                  src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
                />
              </button>
              <div
                class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
                style="word-break: break-word"
              >
                <div class="pb-4 text-sm sm:text-base break-words">
                  <div class="space-y-3">
                    <p class="text-[#234394]">
                      Absolutely. Therapy can help clarify whether to repair the relationship, redefine it, or part ways
                      with mutual respect and understanding.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <p class="xl:text-lg font-semibold text-gray-800 text-center">
            Have more questions? Write to us at
            <a class="text-[#234394]" href="mailto:info@embracelives.com">info@embracelives.com</a>
          </p>
        </div>
      </div>
      <!-- LOCATION-LINKS:START (generated by generate-location-links.js — do not edit by hand) -->
<div class="px-6 md:px-16 bg-white">
<div class="max-w-7xl mx-auto">
<section class="emb-nearby" aria-labelledby="emb-nearby-title">
  <h2 class="emb-nearby__title" id="emb-nearby-title">Adult Counselling across Delhi NCR</h2>
  <p class="emb-nearby__sub">We offer adult counselling and therapy at eMbrace centres throughout Delhi and the wider NCR. Choose the location closest to you.</p>
  <div class="emb-nearby__cols">
    <div class="emb-nearby__group">
      <ul class="emb-nearby__list emb-nearby__list--wide">
      <li><a href="/locations/adult-counselling-in-delhi">Adult Counselling in Delhi</a></li>
      <li><a href="/locations/adult-counselling-in-south-delhi">Adult Counselling in South Delhi</a></li>
      <li><a href="/locations/adult-counselling-in-saket">Adult Counselling in Saket</a></li>
      <li><a href="/locations/adult-counselling-in-hauz-khas">Adult Counselling in Hauz Khas</a></li>
      <li><a href="/locations/adult-counselling-in-green-park">Adult Counselling in Green Park</a></li>
      <li><a href="/locations/adult-counselling-in-greater-kailash">Adult Counselling in Greater Kailash</a></li>
      <li><a href="/locations/adult-counselling-in-defence-colony">Adult Counselling in Defence Colony</a></li>
      <li><a href="/locations/adult-counselling-in-vasant-kunj">Adult Counselling in Vasant Kunj</a></li>
      <li><a href="/locations/adult-counselling-in-gurgaon">Adult Counselling in Gurgaon</a></li>
      <li><a href="/locations/adult-counselling-in-noida">Adult Counselling in Noida</a></li>
      </ul>
    </div>
  </div>
  <a class="emb-nearby__more" href="/locations">View all eMbrace locations &rsaquo;</a>
</section>
</div>
</div>
<!-- LOCATION-LINKS:END -->
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  </body>
</html>
