<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    <title>Gallery | eMbrace Lives</title>
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="Explore the eMbrace Gallery featuring moments from our clinics, corporate workshops, and events." name="description" />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/gallery" rel="canonical" />
    <!-- Site stylesheet. Required for the shared header/footer — .glass-nav (the
         header's translucent background) is defined only here, so without it the
         fixed header renders fully transparent and overlaps the page content.
         Loaded before the CDN script so the CDN's runtime styles still win. -->
    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <!-- NOTE: this page still uses the Tailwind Play CDN, which compiles CSS in the
         browser and is not intended for production. It cannot simply be removed —
         this page's own classes (max-w-[95%], bg-[#E8F8F2], blur-2xl, …) are absent
         from the purged stylesheet above, so the gallery layout would collapse.
         Proper fix: rebuild Tailwind with gallery.php in the content glob, then
         drop this script. -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      // The purged stylesheet above already ships Tailwind's Preflight reset.
      // Leaving the CDN's own copy enabled re-injects it after that stylesheet
      // and wins the cascade, re-normalizing shared elements (nav, svg, button)
      // and making the shared header render larger than on other pages. Disable
      // it here so the CDN only adds the missing arbitrary-value utilities.
      tailwind.config = { corePlugins: { preflight: false } };
    </script>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect" />
    <link
      href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
      rel="stylesheet"
    />
    <style>
      .masonry {
        column-count: 1;
        column-gap: 1.5rem;
      }
      @media (min-width: 640px) {
        .masonry { column-count: 2; }
      }
      @media (min-width: 1024px) {
        .masonry { column-count: 3; }
      }
      @media (min-width: 1280px) {
        .masonry { column-count: 4; }
      }
      .masonry-item {
        break-inside: avoid;
        margin-bottom: 1.5rem;
      }

      /* Gallery filter tabs
         Sticky below the fixed site header (.glass-nav) so the tabs stay
         reachable while scrolling a gallery panel — no more scrolling all
         the way back up to switch tabs. --gallery-nav-h is set by JS below
         to the header's real height; the fallback covers the brief moment
         before that script runs. */
      .gallery-tabs {
        display: flex;
        justify-content: center;
        flex-wrap: wrap;
        gap: 0.75rem;
        margin-bottom: 3rem;
        position: sticky;
        top: var(--gallery-nav-h, 76px);
        z-index: 40;
        background: rgba(255, 255, 255, 0.95);
        backdrop-filter: blur(12px);
        -webkit-backdrop-filter: blur(12px);
        padding: 1rem 1rem 1.25rem;
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.06);
      }
      .gallery-tab-btn {
        padding: 0.75rem 1.75rem;
        border-radius: 9999px;
        font-weight: 700;
        font-size: 1rem;
        border: 2px solid #234394;
        color: #234394;
        background: transparent;
        cursor: pointer;
        transition: all 0.3s ease;
      }
      .gallery-tab-btn:hover {
        background: rgba(35, 67, 148, 0.08);
      }
      .gallery-tab-btn.active-tab {
        background: #234394;
        color: #fff;
        box-shadow: 0 4px 14px rgba(35, 67, 148, 0.25);
      }
      .gallery-panel {
        display: none;
      }
      .gallery-panel.active-panel {
        display: block;
      }

      /* Lightbox styles */
      #lightbox {
        display: none;
        position: fixed;
        z-index: 9999;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.9);
        backdrop-filter: blur(5px);
        align-items: center;
        justify-content: center;
      }
      #lightbox img {
        max-width: 90%;
        max-height: 90vh;
        object-fit: contain;
        border-radius: 8px;
        box-shadow: 0 4px 20px rgba(0,0,0,0.5);
      }
      #lightbox-close {
        position: absolute;
        top: 20px;
        right: 30px;
        color: white;
        font-size: 40px;
        font-weight: bold;
        cursor: pointer;
        transition: 0.3s;
      }
      #lightbox-close:hover {
        color: #ddd;
      }
    </style>
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "CollectionPage",
        "@id": "https://embracelives.com/gallery#webpage",
        "url": "https://embracelives.com/gallery",
        "name": "Gallery | eMbrace Lives",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Explore the eMbrace Gallery featuring moments from our clinics, corporate workshops, and events."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body class="font-['DM_Sans'] antialiased text-[#403D3D]">
    <?php include __DIR__ . '/components/header.php'; ?>

    <div class="relative w-full py-14 md:py-20 bg-[#E8F8F2] flex items-center justify-center overflow-hidden">
        <div class="text-center z-10">
            <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold text-[#234394]">Our Gallery</h1>
            <p class="mt-4 text-lg md:text-xl text-[#403D3D] max-w-2xl mx-auto px-4">Moments from our clinics, corporate workshops, and events.</p>
        </div>
        <!-- Decorative blobs -->
        <div class="absolute w-32 h-32 bg-[#DC649D]/20 rounded-full top-10 left-[10%] blur-xl"></div>
        <div class="absolute w-40 h-40 bg-[#C499F6]/30 rounded-full bottom-10 right-[15%] blur-2xl"></div>
    </div>

    <div class="max-w-[95%] mx-auto py-12 md:py-20">

      <div class="gallery-tabs" role="tablist" aria-label="Gallery categories">
        <button class="gallery-tab-btn active-tab" data-gallery="supriya" type="button">Dr. Supriya</button>
        <button class="gallery-tab-btn" data-gallery="vk" type="button">VK Center</button>
        <button class="gallery-tab-btn" data-gallery="gurgaon" type="button">Gurgaon Centre</button>
      </div>
      <script>
        // Delegated on document + queried fresh at click-time (not captured once
        // at parse-time), so this works regardless of where this tag sits relative
        // to the panels in the DOM, and can't be broken by any other script on the
        // page failing or loading slowly (Tailwind CDN, header/footer includes,
        // lightbox code, etc). Same delegation pattern as /assets/interactive.js.
        (function () {
          document.addEventListener('click', function (e) {
            var btn = e.target.closest('.gallery-tab-btn');
            if (!btn) return;
            var tab = btn.dataset.gallery;
            document.querySelectorAll('.gallery-panel').forEach(function (panel) {
              panel.classList.toggle('active-panel', panel.dataset.gallery === tab);
            });
            document.querySelectorAll('.gallery-tab-btn').forEach(function (b) {
              b.classList.toggle('active-tab', b.dataset.gallery === tab);
            });
          });

          // Pin the sticky tab bar right below the fixed header, whatever
          // its real height turns out to be (fonts/logo can shift it a
          // little), instead of hardcoding a pixel value that could drift.
          var nav = document.querySelector('.glass-nav');
          function setNavHeight() {
            if (nav) {
              document.documentElement.style.setProperty('--gallery-nav-h', nav.offsetHeight + 'px');
            }
          }
          setNavHeight();
          window.addEventListener('resize', setNavHeight);
          window.addEventListener('load', setNavHeight);
        })();
      </script>

      <div class="gallery-panel active-panel" data-gallery="supriya">
      <div class="text-center mb-10">
        <h2 class="text-2xl md:text-3xl font-bold text-[#234394]">Dr. Supriya & Team in Action</h2>
        <div class="w-16 h-1 bg-[#F5A962] mx-auto mt-4 rounded-full"></div>
      </div>

      <div class="masonry">

        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/IMG-20250324-WA0088.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/IMG-20250324-WA0088.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-37.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-37.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-38%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-38%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-38%203.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-38%203.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-38.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-38.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-39%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-39%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-39.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-03-11-20-14-39.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-05-20-16-33-41%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-05-20-16-33-41%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-05-20-16-48-47.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-05-20-16-48-47.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-05-20-16-49-16.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2023-05-20-16-49-16.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2024-11-08-13-47-15.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2024-11-08-13-47-15.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%2010.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%2010.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%2011.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%2011.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%206.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%206.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%207.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%207.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%208.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%208.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%209.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58%209.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-02-18-18-31-58.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-20-10-12-58.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-20-10-12-58.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%203.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%203.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%204.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%204.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%205.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%205.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%206.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00%206.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-01.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-01.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-01-16-30-43%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-01-16-30-43%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-01-16-30-43.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-01-16-30-43.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-01-16-30-44.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-01-16-30-44.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-03-12-06-08.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-03-12-06-08.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-06-03-14-40-05.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-06-03-14-40-05.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-06-03-14-40-06%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-06-03-14-40-06%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-08-02-13-38-18.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-08-02-13-38-18.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50%203.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50%203.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50%204.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50%204.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-02-19-37-50.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-11-23-16-05%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-11-23-16-05%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-11-23-16-05%203.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-11-23-16-05%203.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-11-23-16-05%204.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-11-23-16-05%204.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-10-13-20-24-18.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-10-13-20-24-18.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-10-13-20-24-19%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-10-13-20-24-19%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-10-13-20-24-19.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-10-13-20-24-19.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%203.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%203.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%204.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%204.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%205.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%205.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%206.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13%206.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-01-03-20-22-13.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-02-18-09-44-22.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-02-18-09-44-22.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-02-25-14-14-26.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-02-25-14-14-26.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-02-25-14-14-27.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-02-25-14-14-27.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-03-27-14-55-34%202.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-03-27-14-55-34%202.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1525%20%281%29.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1525%20%281%29.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1539.jpg')">
          <img src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1539.jpg" loading="lazy" alt="eMbrace Event" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
      </div>
      </div>

      <div class="gallery-panel" data-gallery="vk">
      <div class="text-center mb-10">
        <h2 class="text-2xl md:text-3xl font-bold text-[#234394]">VK Center</h2>
        <div class="w-16 h-1 bg-[#F5A962] mx-auto mt-4 rounded-full"></div>
      </div>

      <div class="masonry">

        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/21a4eec5-5263-4992-a120-9a460e5a6bd0.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/21a4eec5-5263-4992-a120-9a460e5a6bd0.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/6389e31c-ce1b-4576-a5e6-dd86f3b69e8b.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/6389e31c-ce1b-4576-a5e6-dd86f3b69e8b.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/679aab4d-ae8d-41fe-8e58-d7edd6bb0438.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/679aab4d-ae8d-41fe-8e58-d7edd6bb0438.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/9ae5e881-b7f3-43b5-b0a6-6d535f575500.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/9ae5e881-b7f3-43b5-b0a6-6d535f575500.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2896.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2896.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2897.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2897.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2898.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2898.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2899.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2899.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2900.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2900.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2901.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/IMG_2901.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/a02d7ea3-a77a-4ab8-b6dd-64452589d589.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/a02d7ea3-a77a-4ab8-b6dd-64452589d589.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/a192d3e0-b514-4510-a48e-1c564cc45a9d.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/a192d3e0-b514-4510-a48e-1c564cc45a9d.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/c795ee9c-4024-4cb3-88d5-65adb9fb57ef.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/c795ee9c-4024-4cb3-88d5-65adb9fb57ef.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/ce57b366-cb31-4b7e-ac99-1561304a0df4.jpg')">
          <img src="/embrace-media/VK%20Center-20260806T082448Z-1-001/VK%20Center/ce57b366-cb31-4b7e-ac99-1561304a0df4.jpg" loading="lazy" alt="eMbrace VK Center" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
      </div>
      </div>

      <div class="gallery-panel" data-gallery="gurgaon">
      <div class="text-center mb-10">
        <h2 class="text-2xl md:text-3xl font-bold text-[#234394]">Gurgaon Centre</h2>
        <div class="w-16 h-1 bg-[#F5A962] mx-auto mt-4 rounded-full"></div>
      </div>

      <div class="masonry">

        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn1.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn1.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn2.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn2.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn3.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn3.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn4.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn4.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn5.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn5.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn6.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn6.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn7.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn7.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn8.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn8.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn9.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn9.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn10.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn10.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn11.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn11.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn12.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn12.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn13.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn13.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn14.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn14.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn15.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn15.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
        <div class="masonry-item rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 group cursor-pointer" onclick="openLightbox('/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn16.jpg')">
          <img src="/embrace-media/Gurgaon%20Centre-20260806T082441Z-1-001/Gurgaon%20Centre/Ggn16.jpg" loading="lazy" alt="eMbrace Gurgaon Centre" class="w-full h-auto object-cover transform group-hover:scale-105 transition-transform duration-500 rounded-xl" />
        </div>
      </div>
      </div>

    </div>

    <!-- Lightbox Modal -->
    <div id="lightbox" onclick="closeLightbox()">
      <span id="lightbox-close">&times;</span>
      <img id="lightbox-img" src="" alt="Full view" />
    </div>

    <?php include __DIR__ . '/components/footer.php'; ?>
    
    <script src="/assets/interactive.js"></script>
    <script>
      function openLightbox(url) {
        document.getElementById('lightbox-img').src = url;
        document.getElementById('lightbox').style.display = 'flex';
        document.body.style.overflow = 'hidden';
      }
      function closeLightbox() {
        document.getElementById('lightbox').style.display = 'none';
        document.body.style.overflow = 'auto';
      }
      document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape') closeLightbox();
      });
    </script>
  </body>
</html>
