/**
 * Generates a single JSON-LD @graph per page and writes it between the SCHEMA
 * markers, just before </head>.
 *
 *     node generate-schema.js
 *
 * Design notes
 * ------------
 * - One consolidated @graph per page instead of several loose <script> blocks, so
 *   the Organization is defined once with a stable @id and every other node
 *   references it rather than redeclaring it.
 * - Questions, answers and breadcrumb trails are READ OUT OF THE PAGE MARKUP, never
 *   invented. Google requires FAQ answers to be visible on the page, and these are —
 *   they come from the page's own accordion.
 * - The legacy hand-written blocks (45 MedicalWebPage + 26 MedicalBusiness) are
 *   replaced. Their hand-authored MedicalCondition detail was lifted into
 *   schema-medical-entities.json and is re-applied here, so nothing editorial was
 *   lost. Those blocks also carried the same root-level URL bug as the canonicals
 *   ("/ados-2-assessment" for a page that actually lives at
 *   /autism/ados-2-assessment); the generated graph uses the real clean URL.
 * - Location pages get a Service node with `areaServed`, NOT a LocalBusiness with a
 *   fabricated street address. eMbrace has three real clinics; the other seven areas
 *   are served, not sited. Inventing addresses there would be fake NAP data.
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const BASE = 'https://embracelives.com';
const ORG_ID = `${BASE}/#organization`;
const SITE_ID = `${BASE}/#website`;

const START = '<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->';
const END = '<!-- SCHEMA:END -->';

/* ---------------------------------------------------------------- real data */

// Verified from contact-us.php. Only these three are actual premises.
const CLINICS = [
  {
    id: 'vasant-kunj', name: 'eMbrace — Vasant Kunj Centre',
    street: 'C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj',
    locality: 'New Delhi', region: 'Delhi', postal: '110070',
  },
  {
    id: 'gurugram', name: 'eMbrace — Gurugram Centre',
    street: '710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24',
    locality: 'Gurugram', region: 'Haryana', postal: '122002',
  },
  {
    id: 'malviya-nagar', name: 'eMbrace — Malviya Nagar Centre',
    street: 'FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1',
    locality: 'New Delhi', region: 'Delhi', postal: '110017',
  },
];

const PHONE = '+91-9971576800';
const EMAIL = 'info@embracelives.com';
const LOGO = `${BASE}/assets/Logo-DrHvIBUF.svg`;
const SAME_AS = [
  'https://www.linkedin.com/company/embracelives/',
  'https://www.instagram.com/embracelives/',
  'https://www.facebook.com/embracelives22/',
];
const HOURS = {
  '@type': 'OpeningHoursSpecification',
  dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  opens: '10:00', closes: '18:00',
};

const SERVICES = [
  'Child Psychology', 'Clinical Psychology', 'Autism Assessment', 'ADHD Assessment',
  'Learning Disability Assessment', 'Speech and Language Therapy', 'Occupational Therapy',
  'Special Education', 'Teen Counselling', 'Adult Counselling', 'Couples Therapy',
];

/* ------------------------------------------------------------- page walking */

const SKIP_DIRS = new Set(['node_modules', 'dist', '.git', 'api', 'components', '_external', 'assets', 'assets_backup', 'practitioner-images', 'practitioner-images_backup', 'embrace-media', 'videos', '__pycache__']);
// blog.php is a bare 301 stub pointing at /blog/; it has no markup to describe.
const SKIP_FILES = new Set(['build.php', 'blog.php']);

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name.startsWith('.')) continue;
    const f = path.join(dir, e.name);
    if (e.isDirectory()) { if (SKIP_DIRS.has(e.name)) continue; walk(f, out); }
    else if (e.name.endsWith('.php')) {
      const rel = path.relative(ROOT, f).split(path.sep).join('/');
      if (!SKIP_FILES.has(rel)) out.push(rel);
    }
  }
  return out;
}

// A page at `<dir>/index.php` is served at `/<dir>/`, slash included: nginx
// 301s `/<dir>` to `/<dir>/` as soon as the directory exists, so the slashless
// form is only ever a redirect.
const urlFor = rel =>
  rel === 'index.php' ? `${BASE}/`
  : rel.endsWith('/index.php') ? `${BASE}/` + rel.replace(/index\.php$/, '')
  : `${BASE}/` + rel.replace(/\.php$/, '');

/** Turn an internal href from the markup into the site's clean URL form. */
function cleanHref(href) {
  if (!href) return null;
  if (/^https?:/i.test(href)) return href;
  let u = href.split('#')[0].split('?')[0];
  if (u === '/index.php' || u === '/' || u === '/index') return `${BASE}/`;
  u = u.replace(/\.php$/, '');
  return u.startsWith('/') ? BASE + u : `${BASE}/${u}`;
}

/* --------------------------------------------------------- text extraction */

const decode = s => s
  .replace(/<[^>]*>/g, ' ')
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ')
  .replace(/&rsquo;/g, '’').replace(/&lsquo;/g, '‘')
  .replace(/&ldquo;/g, '“').replace(/&rdquo;/g, '”')
  .replace(/&ndash;/g, '–').replace(/&mdash;/g, '—').replace(/&hellip;/g, '…')
  .replace(/\s+/g, ' ').trim();

const attr = (html, re) => { const m = html.match(re); return m ? decode(m[1]) : null; };

const getTitle = h => attr(h, /<title>([\s\S]*?)<\/title>/i);
const getDesc = h =>
  attr(h, /<meta[^>]*name="description"[^>]*content="([^"]*)"/i) ||
  attr(h, /<meta[^>]*content="([^"]*)"[^>]*name="description"/i);

/** The visible <h1>, which is the real headline; <title> carries SEO padding. */
const getH1 = h => attr(h, /<h1[^>]*>([\s\S]*?)<\/h1>/i);

/** ISO publication date from the article:published_time meta tag. */
const getPublished = h =>
  attr(h, /<meta[^>]*property="article:published_time"[^>]*content="([^"]*)"/i) ||
  attr(h, /<meta[^>]*content="([^"]*)"[^>]*property="article:published_time"/i);

/**
 * Reviewer name from the visible author card, e.g. "Reviewed by Dr. Supriya
 * Malik". Read out of the page like everything else here, never invented: if a
 * post carries no author card, the BlogPosting simply gets no reviewer.
 */
function getReviewer(html) {
  const m = html.match(/<div class="author-card"[\s\S]*?<strong>([\s\S]*?)<\/strong>/i);
  if (!m) return null;
  const name = decode(m[1]).replace(/^Reviewed by\s+/i, '').trim();
  return name || null;
}

/** Pull visible Q&A pairs out of whichever accordion pattern the page uses. */
function extractFaqs(html) {
  const out = [];
  const push = (q, a) => {
    q = decode(q); a = decode(a);
    if (q && a && q.length >= 8 && q.length <= 300 && a.length >= 25) {
      a = a.slice(0, 1200);
      if (!out.some(x => x.q === q)) out.push({ q, a });
    }
  };

  // Pattern A — topic and location pages: <div class="faq-item"> button>span + p
  for (const c of html.split(/<div class="faq-item"/).slice(1)) {
    const q = c.match(/<span[^>]*>([\s\S]*?)<\/span>/);
    const a = c.match(/<p[^>]*>([\s\S]*?)<\/p>/);
    if (q && a) push(q[1], a[1]);
  }
  if (out.length) return out;

  // Pattern B — homepage accordion
  for (const m of html.matchAll(/<span class="font-semibold text-sm md:text-base 2xl:text-lg text-gray-900 pr-4">([\s\S]*?)<\/span>[\s\S]*?<p class="px-5[^"]*">([\s\S]*?)<\/p>/g)) {
    push(m[1], m[2]);
  }
  if (out.length) return out;

  // Pattern C — the dedicated /faq page
  for (const c of html.split('<div class="bg-white rounded-lg shadow-sm overflow-hidden">').slice(1)) {
    const q = c.match(/<span class="font-medium text-gray-800[^"]*"[^>]*>([\s\S]*?)<\/span>/);
    if (!q) continue;
    const rest = c.slice(c.indexOf('</button>') + 9);
    push(q[1], rest);
  }
  return out;
}

/** Read the visible breadcrumb trail. */
function extractBreadcrumb(html) {
  const m = html.match(/<div class="[^"]*breadcrumbs"[\s\S]*?<div[^>]*>([\s\S]*?)<\/div>/);
  if (!m) return null;
  const items = [];
  for (const a of m[1].matchAll(/<a[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/g)) {
    const name = decode(a[2]);
    if (name) items.push({ name, url: cleanHref(a[1]) });
  }
  const last = m[1].match(/<span class="text-gray-800 font-medium">([\s\S]*?)<\/span>/);
  if (last) { const n = decode(last[1]); if (n) items.push({ name: n, url: null }); }
  return items.length > 1 ? items : null;
}

/**
 * Hand-authored MedicalCondition detail, keyed by page path.
 *
 * This was originally embedded in 45 loose <script> blocks in the page markup.
 * It is real editorial content (conditions, possible treatments), so it lives in
 * schema-medical-entities.json now — an explicit, reviewable data file rather than
 * something scraped back out of HTML on every run. Edit that file to change it.
 */
const MEDICAL_ENTITIES = (() => {
  const p = path.join(ROOT, 'schema-medical-entities.json');
  if (!fs.existsSync(p)) {
    console.warn('WARNING: schema-medical-entities.json missing — MedicalCondition detail will be omitted.');
    return {};
  }
  return JSON.parse(fs.readFileSync(p, 'utf8'));
})();

/* ------------------------------------------------------------- page typing */

const MEDICAL_DIRS = new Set(['autism', 'adhd', 'learning-disabilities', 'speech-therapy', 'occupational-therapy', 'child-psychology', 'teen-mental-health', 'adult-mental-health', 'locations', 'parent-hub', 'schools-hub', 'corporate-wellness']);

const PAGE_TYPE_OVERRIDES = {
  'about.php': 'AboutPage',
  'contact-us.php': 'ContactPage',
  'faq.php': 'WebPage',   // the generated FAQPage node covers it; avoids a duplicate
  'gallery.php': 'CollectionPage',
  'seo_sitemap.php': 'CollectionPage',
  'locations/index.php': 'CollectionPage',
  'userListing.php': 'CollectionPage',
  'practitioner.php': 'CollectionPage',
  'media.php': 'CollectionPage',
  'careers.php': 'WebPage',
  'privacypolicy.php': 'WebPage',
  'terms_and_conditions.php': 'WebPage',
  'bookingandCancellation.php': 'WebPage',
  // The blog hub is blog/index.php, served at /blog/. The rest of the blog/
  // directory holds the articles.
  'blog/index.php': 'CollectionPage',
};

/** Articles under blog/. The hub itself (blog/index.php) is not one of them. */
const isBlogPost = rel => rel.startsWith('blog/') && rel !== 'blog/index.php';

function pageTypeFor(rel) {
  if (PAGE_TYPE_OVERRIDES[rel]) return PAGE_TYPE_OVERRIDES[rel];
  const dir = rel.includes('/') ? rel.split('/')[0] : null;
  if (dir && MEDICAL_DIRS.has(dir)) return 'MedicalWebPage';
  return 'WebPage';
}

/* --------------------------------------------- location page service parsing */

const AREAS = {
  'delhi': 'Delhi', 'south-delhi': 'South Delhi', 'saket': 'Saket', 'hauz-khas': 'Hauz Khas',
  'green-park': 'Green Park', 'greater-kailash': 'Greater Kailash', 'defence-colony': 'Defence Colony',
  'vasant-kunj': 'Vasant Kunj', 'gurgaon': 'Gurgaon', 'noida': 'Noida',
};
const SERVICE_NAMES = {
  'child-psychologist': 'Child Psychology', 'child-counselling': 'Child Counselling',
  'teen-counselling': 'Teen Counselling', 'adult-counselling': 'Adult Counselling',
  'autism-assessment': 'Autism Assessment', 'autism-therapy': 'Autism Therapy',
  'adhd-assessment': 'ADHD Assessment',
  'learning-disability-assessment': 'Learning Disability Assessment',
  'speech-therapy': 'Speech Therapy', 'occupational-therapy': 'Occupational Therapy',
  'special-education': 'Special Education',
  // Added with the child development service pages.
  'developmental-delay-treatment': 'Developmental Delay Treatment',
  'intellectual-disability-treatment': 'Intellectual Disability Treatment',
  'down-syndrome-treatment': 'Down Syndrome Treatment',
  'oral-motor-therapy': 'Oral Motor Delay Treatment',
  'aba-therapy': 'ABA Therapy',
  'physiotherapy': 'Physiotherapy',
  'pediatric-neurologist': 'Pediatric Neurology',
  'developmental-pediatrician': 'Developmental Paediatrics',
  'child-development-centre': 'Child Development Centre',
};

/**
 * Gurgaon is in Haryana and Noida is in Uttar Pradesh, so the old blanket
 * "<area>, Delhi NCR, India" was wrong for both, and redundant for Delhi itself.
 */
function areaServedName(area) {
  if (area === 'Gurgaon' || area === 'Gurugram') return 'Gurgaon, Haryana, India';
  if (area === 'Noida') return 'Noida, Uttar Pradesh, India';
  if (area === 'Delhi') return 'Delhi, India';
  return `${area}, Delhi, India`;
}

function parseLocation(rel) {
  if (!rel.startsWith('locations/') || rel === 'locations/index.php') return null;
  const slug = path.basename(rel, '.php');
  for (const [aSlug, aName] of Object.entries(AREAS)) {
    const suf = `-in-${aSlug}`;
    if (slug.endsWith(suf)) {
      const svc = slug.slice(0, -suf.length);
      if (SERVICE_NAMES[svc]) return { service: SERVICE_NAMES[svc], area: aName };
    }
  }
  return null;
}

/* ------------------------------------------------------------ graph builder */

function organizationNode() {
  return {
    '@type': ['MedicalBusiness', 'MedicalOrganization'],
    '@id': ORG_ID,
    name: 'eMbrace',
    alternateName: 'eMbrace Lives',
    legalName: 'eMbrace, a unit of SMD Wellness',
    url: `${BASE}/`,
    logo: { '@id': `${BASE}/#logo` },
    image: { '@id': `${BASE}/#logo` },
    description: 'Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.',
    telephone: PHONE,
    email: EMAIL,
    priceRange: '$$',
    currenciesAccepted: 'INR',
    areaServed: [
      { '@type': 'AdministrativeArea', name: 'Delhi NCR' },
      ...Object.values(AREAS).map(a => ({ '@type': 'Place', name: a })),
    ],
    medicalSpecialty: ['Psychiatric', 'Pediatric'],
    availableService: SERVICES.map(s => ({ '@type': 'MedicalTherapy', name: s })),
    address: {
      '@type': 'PostalAddress',
      streetAddress: CLINICS[0].street,
      addressLocality: CLINICS[0].locality,
      addressRegion: CLINICS[0].region,
      postalCode: CLINICS[0].postal,
      addressCountry: 'IN',
    },
    location: CLINICS.map(c => ({
      '@type': 'MedicalClinic',
      '@id': `${BASE}/contact-us#${c.id}`,
      name: c.name,
      parentOrganization: { '@id': ORG_ID },
      telephone: PHONE,
      email: EMAIL,
      url: `${BASE}/contact-us`,
      address: {
        '@type': 'PostalAddress',
        streetAddress: c.street,
        addressLocality: c.locality,
        addressRegion: c.region,
        postalCode: c.postal,
        addressCountry: 'IN',
      },
      openingHoursSpecification: [HOURS],
    })),
    openingHoursSpecification: [HOURS],
    sameAs: SAME_AS,
  };
}

function buildGraph(rel, html) {
  const url = urlFor(rel);
  const pageId = `${url}#webpage`;
  const title = getTitle(html) || 'eMbrace';
  const desc = getDesc(html);
  const graph = [];

  // Top-level so every {"@id": ".../#logo"} reference resolves within the graph.
  graph.push({
    '@type': 'ImageObject', '@id': `${BASE}/#logo`,
    url: LOGO, contentUrl: LOGO, caption: 'eMbrace',
  });
  graph.push(organizationNode());
  graph.push({
    '@type': 'WebSite', '@id': SITE_ID, url: `${BASE}/`, name: 'eMbrace',
    publisher: { '@id': ORG_ID }, inLanguage: 'en-IN',
  });

  const type = pageTypeFor(rel);
  const page = {
    '@type': type,
    '@id': pageId,
    url,
    name: title,
    isPartOf: { '@id': SITE_ID },
    about: { '@id': ORG_ID },
    inLanguage: 'en-IN',
  };
  if (desc) page.description = desc;
  if (type === 'MedicalWebPage' && MEDICAL_ENTITIES[rel]) {
    page.mainEntity = MEDICAL_ENTITIES[rel].mainEntity;
    if (MEDICAL_ENTITIES[rel].aspect) page.aspect = MEDICAL_ENTITIES[rel].aspect;
  }

  const crumbs = extractBreadcrumb(html);
  if (crumbs) {
    page.breadcrumb = { '@id': `${url}#breadcrumb` };
    graph.push({
      '@type': 'BreadcrumbList',
      '@id': `${url}#breadcrumb`,
      itemListElement: crumbs.map((c, i) => {
        const item = { '@type': 'ListItem', position: i + 1, name: c.name };
        if (c.url) item.item = c.url; // last crumb is the current page: no item, per Google
        return item;
      }),
    });
  }
  graph.push(page);

  const faqs = extractFaqs(html);
  if (faqs.length) {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${url}#faq`,
      url,
      name: `${title} — Frequently Asked Questions`,
      isPartOf: { '@id': pageId },
      inLanguage: 'en-IN',
      mainEntity: faqs.map(f => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    });
  }

  const loc = parseLocation(rel);
  if (loc) {
    graph.push({
      '@type': 'Service',
      '@id': `${url}#service`,
      name: `${loc.service} in ${loc.area}`,
      serviceType: loc.service,
      provider: { '@id': ORG_ID },
      areaServed: { '@type': 'Place', name: areaServedName(loc.area) },
      availableChannel: {
        '@type': 'ServiceChannel',
        serviceUrl: url,
        servicePhone: PHONE,
      },
      audience: { '@type': 'PeopleAudience', audienceType: 'Children, adolescents and adults' },
    });
  }

  if (isBlogPost(rel)) {
    const posting = {
      '@type': 'BlogPosting',
      '@id': `${url}#article`,
      isPartOf: { '@id': pageId },
      mainEntityOfPage: { '@id': pageId },
      headline: getH1(html) || title,
      url,
      inLanguage: 'en-IN',
      // The practice is the author of record; a named clinician signs off on the
      // clinical content and appears as reviewedBy below when the page says so.
      author: { '@id': ORG_ID },
      publisher: { '@id': ORG_ID },
      image: `${BASE}/og-image.png`,
    };
    if (desc) posting.description = desc;

    const published = getPublished(html);
    if (published) {
      posting.datePublished = published;
      posting.dateModified = published;
    }

    const reviewer = getReviewer(html);
    if (reviewer) {
      posting.reviewedBy = { '@type': 'Person', name: reviewer, worksFor: { '@id': ORG_ID } };
    }

    page.mainEntity = { '@id': `${url}#article` };
    graph.push(posting);
  }

  if (rel === 'contact-us.php') {
    page.mainEntity = { '@id': ORG_ID };
  }

  return { '@context': 'https://schema.org', '@graph': graph };
}

/* ------------------------------------------------------------------ writing */

const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
// Consume the block's own indentation and trailing newline too, otherwise each run
// leaves an orphaned blank line behind and every file grows by a line per run.
const MARKER_RE = new RegExp('[ \\t]*' + esc(START) + '[\\s\\S]*?' + esc(END) + '[ \\t]*\\r?\\n?');
// Legacy hand-written blocks, replaced by the generated graph.
const LEGACY_RE = /[ \t]*<script[^>]*type="application\/ld\+json"[^>]*>[\s\S]*?<\/script>\s*/gi;

const stats = { written: 0, faqPages: 0, faqQuestions: 0, crumbs: 0, services: 0, posts: 0, legacyRemoved: 0, preserved: 0, noHead: [] };

for (const rel of walk(ROOT).sort()) {
  const full = path.join(ROOT, rel);
  let html = fs.readFileSync(full, 'utf8');

  // Drop any previously generated block first so the legacy sweep cannot eat it.
  html = html.replace(MARKER_RE, '');

  const before = html;
  html = html.replace(LEGACY_RE, '');
  if (html !== before) stats.legacyRemoved++;

  const graph = buildGraph(rel, html);
  if (MEDICAL_ENTITIES[rel]) stats.preserved++;
  const json = JSON.stringify(graph, null, 2);
  const block = `${START}\n<script type="application/ld+json">\n${json}\n</script>\n${END}\n`;

  if (!/<\/head>/i.test(html)) { stats.noHead.push(rel); continue; }
  // Collapse any blank lines left by earlier runs so spacing stays stable.
  html = html.replace(/(?:[ \t]*\r?\n){2,}([ \t]*<\/head>)/i, '\n$1');
  html = html.replace(/([ \t]*)<\/head>/i, (m, indent) =>
    block.split('\n').map(l => (l ? indent + l : l)).join('\n') + `${indent}</head>`);

  fs.writeFileSync(full, html);
  stats.written++;

  const faq = graph['@graph'].find(n => Array.isArray(n.mainEntity) && n['@type'] === 'FAQPage');
  if (faq) { stats.faqPages++; stats.faqQuestions += faq.mainEntity.length; }
  if (graph['@graph'].some(n => n['@type'] === 'BreadcrumbList')) stats.crumbs++;
  if (graph['@graph'].some(n => n['@type'] === 'Service')) stats.services++;
  if (graph['@graph'].some(n => n['@type'] === 'BlogPosting')) stats.posts++;
}

console.log(`Schema written to ${stats.written} pages (legacy blocks replaced on ${stats.legacyRemoved}).`);
console.log(`  FAQPage nodes: ${stats.faqPages} (${stats.faqQuestions} questions)`);
console.log(`  BreadcrumbList nodes: ${stats.crumbs}`);
console.log(`  Service nodes (location pages): ${stats.services}`);
console.log(`  BlogPosting nodes: ${stats.posts}`);
console.log(`  MedicalCondition detail applied: ${stats.preserved}`);
if (stats.noHead.length) console.log(`  NO </head> — skipped: ${stats.noHead.join(', ')}`);
