<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="Give the gift of mental well-being. Purchase therapy gift vouchers from eMbrace — a thoughtful, meaningful gift for loved ones in Delhi &amp; across India."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/giftatherapy" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/giftatherapy" property="og:url" />
    <meta content="Gift a Therapy Session | eMbrace Child Psychology, Delhi NCR" property="og:title" />
    <meta
      content="Give the gift of mental well-being. Purchase therapy gift vouchers from eMbrace — a thoughtful, meaningful gift for loved ones in Delhi &amp; across India."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="Gift a Therapy Session | eMbrace Child Psychology, Delhi NCR" name="twitter:title" />
    <meta
      content="Give the gift of mental well-being. Purchase therapy gift vouchers from eMbrace — a thoughtful, meaningful gift for loved ones in Delhi &amp; across India."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>Gift a Therapy Session | eMbrace Child Psychology, Delhi NCR</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "WebPage",
        "@id": "https://embracelives.com/giftatherapy#webpage",
        "url": "https://embracelives.com/giftatherapy",
        "name": "Gift a Therapy Session | eMbrace Child Psychology, Delhi NCR",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Give the gift of mental well-being. Purchase therapy gift vouchers from eMbrace — a thoughtful, meaningful gift for loved ones in Delhi & across India."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div
        class="w-full h-fit bg-gradient-to-b from-[#FCEEF3] to-[#F8F2FF] items-center flex flex-col p-6 gap-4 relative overflow-hidden justify-center md:min-h-[calc(100vh-4.4rem)]"
      >
        <img decoding="async" width="399" height="406"
          alt="Child"
          class="h-48 w-48 2xl:h-80 2xl:w-80 drop-shadow-[#FFAAE5CC]"
          src="/assets/giftChild-B09OJNFN.svg"
        />
        <h1 class="text-lg 2xl:text-5xl md:text-3xl font-semibold text-center">
          A Thoughtful Gift for Mental Well-Being
        </h1>
        <p class="w-full md:w-[65%] 2xl:text-xl text-sm md:text-lg px-4 font-medium text-center">
          Mental health matters, and sometimes, the best way to show you care is by
          <span class="text-[#234394]">offering support, healing,</span> and a safe space to talk. With
          <span class="text-[#234394]">eMbrace’s "Gift a Therapy" program</span>, you can gift a personalized therapy
          session to a loved one, friend, or colleague.
        </p>
        <div
          class="absolute h-8 w-8 md:w-15 md:h-15 bg-[#FF00735E] rounded-full -left-[4%] top-[5%] md:-left-[2.25%] md:bottom-[50%]"
        ></div>
      </div>
      <div
        class="md:min-h-fit lg:flex lg:items-center lg:justify-center w-full px-6 py-20 md:py-10 pb-8 relative bg-[#F9FAFB] overflow-hidden z-5"
      >
        <div
          class="absolute md:w-16 md:h-16 h-8 w-8 rounded-full bg-[#D2ADFE9C] top-[13%] md:top-[40%] left-[2%] md:left-0"
        ></div>
        <div
          class="absolute w-16 h-16 rounded-full bg-[#FF00735E] -bottom-[7%] md:-bottom-[4%] right-[0%] md:right-[10%] -z-1"
        ></div>
        <div class="max-w-fit mx-auto">
          <h2 class="2xl:text-5xl text-2xl md:text-3xl font-bold text-black mb-8 md:ml-2 text-center md:text-left">
            How It Works
          </h2>
          <div class="flex flex-col gap-6 md:ml-2">
            <div
              class="bg-white p-4 md:px-6 rounded-2xl flex md:items-center gap-2 shadow-[0_2px_3px_-1px_rgba(0,0,0,0.3)]"
            >
              <img
                alt="Step"
                class="h-5 w-5 2xl:h-8 2xl:w-8"
                src="data:image/svg+xml,%3csvg%20width='57'%20height='58'%20viewBox='0%200%2057%2058'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cg%20clip-path='url(%23clip0_1833_1388)'%3e%3cpath%20d='M28.5%200C22.8632%200%2017.3531%201.70082%2012.6663%204.88738C7.97946%208.07394%204.32654%2012.6031%202.16945%2017.9022C0.0123487%2023.2012%20-0.552046%2029.0322%200.547632%2034.6576C1.64731%2040.2831%204.36167%2045.4504%208.34747%2049.5061C12.3333%2053.5618%2017.4115%2056.3238%2022.9399%2057.4428C28.4684%2058.5617%2034.1988%2057.9874%2039.4065%2055.7925C44.6142%2053.5976%2049.0653%2049.8806%2052.1969%2045.1115C55.3285%2040.3425%2057%2034.7357%2057%2029C56.9918%2021.3113%2053.9865%2013.9398%2048.6435%208.50309C43.3005%203.06633%2036.0562%200.00831595%2028.5%200ZM28.5%2053.1667C23.8027%2053.1667%2019.2109%2051.7493%2015.3052%2049.0938C11.3996%2046.4384%208.35546%2042.6641%206.55787%2038.2482C4.76029%2033.8323%204.28996%2028.9732%205.20636%2024.2853C6.12276%2019.5974%208.38473%2015.2914%2011.7062%2011.9116C15.0277%208.53182%2019.2596%206.23017%2023.8666%205.29769C28.4737%204.36521%2033.249%204.84379%2037.5887%206.67291C41.9285%208.50203%2045.6377%2011.5995%2048.2474%2015.5737C50.8571%2019.5479%2052.25%2024.2203%2052.25%2029C52.2431%2035.4072%2049.7387%2041.55%2045.2862%2046.0806C40.8337%2050.6112%2034.7968%2053.1596%2028.5%2053.1667Z'%20fill='%23234394'/%3e%3cpath%20d='M25.2722%2015.0605C25.0327%2014.8571%2024.7561%2014.7037%2024.4583%2014.609C24.1605%2014.5143%2023.8473%2014.4803%2023.5366%2014.5088C23.2258%2014.5373%2022.9237%2014.6278%2022.6473%2014.7751C22.3709%2014.9224%2022.1258%2015.1237%2021.9259%2015.3675C21.7259%2015.6112%2021.5752%2015.8926%2021.4821%2016.1956C21.3891%2016.4987%2021.3556%2016.8174%2021.3836%2017.1336C21.4116%2017.4498%2021.5006%2017.7572%2021.6454%2018.0385C21.7902%2018.3197%2021.988%2018.5691%2022.2275%2018.7725L34.2877%2028.9999L22.2275%2039.2272C21.7437%2039.6381%2021.4402%2040.2276%2021.3836%2040.8662C21.3271%2041.5048%2021.5221%2042.1401%2021.9259%2042.6323C22.3296%2043.1245%2022.909%2043.4334%2023.5366%2043.491C24.1642%2043.5485%2024.7885%2043.3501%2025.2722%2042.9392L39.5222%2030.8559C39.7895%2030.6291%2040.0046%2030.3453%2040.1521%2030.0245C40.2997%2029.7038%2040.3762%2029.354%2040.3762%2028.9999C40.3762%2028.6457%2040.2997%2028.2959%2040.1521%2027.9752C40.0046%2027.6545%2039.7895%2027.3707%2039.5222%2027.1439L25.2722%2015.0605Z'%20fill='%23234394'/%3e%3c/g%3e%3cdefs%3e%3cclipPath%20id='clip0_1833_1388'%3e%3crect%20width='57'%20height='58'%20fill='white'/%3e%3c/clipPath%3e%3c/defs%3e%3c/svg%3e"
              />
              <div class="md:flex">
                <p class="2xl:text-xl font-semibold text-sm w-fit md:text-base text-[#234394]">Choose a Session</p>
                <p class="2xl:text-xl text-[#403D3D] text-sm md:text-base font-medium">
                  - Select a standalone therapy session or earn free sessions through referrals.
                </p>
              </div>
            </div>
            <div
              class="bg-white p-4 md:px-6 rounded-2xl flex md:items-center gap-2 shadow-[0_2px_3px_-1px_rgba(0,0,0,0.3)]"
            >
              <img
                alt="Step"
                class="h-5 w-5 2xl:h-8 2xl:w-8"
                src="data:image/svg+xml,%3csvg%20width='57'%20height='58'%20viewBox='0%200%2057%2058'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cg%20clip-path='url(%23clip0_1833_1388)'%3e%3cpath%20d='M28.5%200C22.8632%200%2017.3531%201.70082%2012.6663%204.88738C7.97946%208.07394%204.32654%2012.6031%202.16945%2017.9022C0.0123487%2023.2012%20-0.552046%2029.0322%200.547632%2034.6576C1.64731%2040.2831%204.36167%2045.4504%208.34747%2049.5061C12.3333%2053.5618%2017.4115%2056.3238%2022.9399%2057.4428C28.4684%2058.5617%2034.1988%2057.9874%2039.4065%2055.7925C44.6142%2053.5976%2049.0653%2049.8806%2052.1969%2045.1115C55.3285%2040.3425%2057%2034.7357%2057%2029C56.9918%2021.3113%2053.9865%2013.9398%2048.6435%208.50309C43.3005%203.06633%2036.0562%200.00831595%2028.5%200ZM28.5%2053.1667C23.8027%2053.1667%2019.2109%2051.7493%2015.3052%2049.0938C11.3996%2046.4384%208.35546%2042.6641%206.55787%2038.2482C4.76029%2033.8323%204.28996%2028.9732%205.20636%2024.2853C6.12276%2019.5974%208.38473%2015.2914%2011.7062%2011.9116C15.0277%208.53182%2019.2596%206.23017%2023.8666%205.29769C28.4737%204.36521%2033.249%204.84379%2037.5887%206.67291C41.9285%208.50203%2045.6377%2011.5995%2048.2474%2015.5737C50.8571%2019.5479%2052.25%2024.2203%2052.25%2029C52.2431%2035.4072%2049.7387%2041.55%2045.2862%2046.0806C40.8337%2050.6112%2034.7968%2053.1596%2028.5%2053.1667Z'%20fill='%23234394'/%3e%3cpath%20d='M25.2722%2015.0605C25.0327%2014.8571%2024.7561%2014.7037%2024.4583%2014.609C24.1605%2014.5143%2023.8473%2014.4803%2023.5366%2014.5088C23.2258%2014.5373%2022.9237%2014.6278%2022.6473%2014.7751C22.3709%2014.9224%2022.1258%2015.1237%2021.9259%2015.3675C21.7259%2015.6112%2021.5752%2015.8926%2021.4821%2016.1956C21.3891%2016.4987%2021.3556%2016.8174%2021.3836%2017.1336C21.4116%2017.4498%2021.5006%2017.7572%2021.6454%2018.0385C21.7902%2018.3197%2021.988%2018.5691%2022.2275%2018.7725L34.2877%2028.9999L22.2275%2039.2272C21.7437%2039.6381%2021.4402%2040.2276%2021.3836%2040.8662C21.3271%2041.5048%2021.5221%2042.1401%2021.9259%2042.6323C22.3296%2043.1245%2022.909%2043.4334%2023.5366%2043.491C24.1642%2043.5485%2024.7885%2043.3501%2025.2722%2042.9392L39.5222%2030.8559C39.7895%2030.6291%2040.0046%2030.3453%2040.1521%2030.0245C40.2997%2029.7038%2040.3762%2029.354%2040.3762%2028.9999C40.3762%2028.6457%2040.2997%2028.2959%2040.1521%2027.9752C40.0046%2027.6545%2039.7895%2027.3707%2039.5222%2027.1439L25.2722%2015.0605Z'%20fill='%23234394'/%3e%3c/g%3e%3cdefs%3e%3cclipPath%20id='clip0_1833_1388'%3e%3crect%20width='57'%20height='58'%20fill='white'/%3e%3c/clipPath%3e%3c/defs%3e%3c/svg%3e"
              />
              <div class="md:flex">
                <p class="2xl:text-xl font-semibold text-sm w-fit md:text-base text-[#234394]">Personalized Gifting</p>
                <p class="2xl:text-xl text-[#403D3D] text-sm md:text-base font-medium">
                  - Add a heartfelt message to make it special.
                </p>
              </div>
            </div>
            <div
              class="bg-white p-4 md:px-6 rounded-2xl flex md:items-center gap-2 shadow-[0_2px_3px_-1px_rgba(0,0,0,0.3)]"
            >
              <img
                alt="Step"
                class="h-5 w-5 2xl:h-8 2xl:w-8"
                src="data:image/svg+xml,%3csvg%20width='57'%20height='58'%20viewBox='0%200%2057%2058'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cg%20clip-path='url(%23clip0_1833_1388)'%3e%3cpath%20d='M28.5%200C22.8632%200%2017.3531%201.70082%2012.6663%204.88738C7.97946%208.07394%204.32654%2012.6031%202.16945%2017.9022C0.0123487%2023.2012%20-0.552046%2029.0322%200.547632%2034.6576C1.64731%2040.2831%204.36167%2045.4504%208.34747%2049.5061C12.3333%2053.5618%2017.4115%2056.3238%2022.9399%2057.4428C28.4684%2058.5617%2034.1988%2057.9874%2039.4065%2055.7925C44.6142%2053.5976%2049.0653%2049.8806%2052.1969%2045.1115C55.3285%2040.3425%2057%2034.7357%2057%2029C56.9918%2021.3113%2053.9865%2013.9398%2048.6435%208.50309C43.3005%203.06633%2036.0562%200.00831595%2028.5%200ZM28.5%2053.1667C23.8027%2053.1667%2019.2109%2051.7493%2015.3052%2049.0938C11.3996%2046.4384%208.35546%2042.6641%206.55787%2038.2482C4.76029%2033.8323%204.28996%2028.9732%205.20636%2024.2853C6.12276%2019.5974%208.38473%2015.2914%2011.7062%2011.9116C15.0277%208.53182%2019.2596%206.23017%2023.8666%205.29769C28.4737%204.36521%2033.249%204.84379%2037.5887%206.67291C41.9285%208.50203%2045.6377%2011.5995%2048.2474%2015.5737C50.8571%2019.5479%2052.25%2024.2203%2052.25%2029C52.2431%2035.4072%2049.7387%2041.55%2045.2862%2046.0806C40.8337%2050.6112%2034.7968%2053.1596%2028.5%2053.1667Z'%20fill='%23234394'/%3e%3cpath%20d='M25.2722%2015.0605C25.0327%2014.8571%2024.7561%2014.7037%2024.4583%2014.609C24.1605%2014.5143%2023.8473%2014.4803%2023.5366%2014.5088C23.2258%2014.5373%2022.9237%2014.6278%2022.6473%2014.7751C22.3709%2014.9224%2022.1258%2015.1237%2021.9259%2015.3675C21.7259%2015.6112%2021.5752%2015.8926%2021.4821%2016.1956C21.3891%2016.4987%2021.3556%2016.8174%2021.3836%2017.1336C21.4116%2017.4498%2021.5006%2017.7572%2021.6454%2018.0385C21.7902%2018.3197%2021.988%2018.5691%2022.2275%2018.7725L34.2877%2028.9999L22.2275%2039.2272C21.7437%2039.6381%2021.4402%2040.2276%2021.3836%2040.8662C21.3271%2041.5048%2021.5221%2042.1401%2021.9259%2042.6323C22.3296%2043.1245%2022.909%2043.4334%2023.5366%2043.491C24.1642%2043.5485%2024.7885%2043.3501%2025.2722%2042.9392L39.5222%2030.8559C39.7895%2030.6291%2040.0046%2030.3453%2040.1521%2030.0245C40.2997%2029.7038%2040.3762%2029.354%2040.3762%2028.9999C40.3762%2028.6457%2040.2997%2028.2959%2040.1521%2027.9752C40.0046%2027.6545%2039.7895%2027.3707%2039.5222%2027.1439L25.2722%2015.0605Z'%20fill='%23234394'/%3e%3c/g%3e%3cdefs%3e%3cclipPath%20id='clip0_1833_1388'%3e%3crect%20width='57'%20height='58'%20fill='white'/%3e%3c/clipPath%3e%3c/defs%3e%3c/svg%3e"
              />
              <div class="md:flex">
                <p class="2xl:text-xl font-semibold text-sm w-fit md:text-base text-[#234394]">Seamless Booking</p>
                <p class="2xl:text-xl text-[#403D3D] text-sm md:text-base font-medium">
                  - The recipient schedules their session at their convenience.
                </p>
              </div>
            </div>
          </div>
          <div class="font-semibold text-[#234394] mt-20 md:block hidden 2xl:text-xl">
            Show someone they’re not alone.
          </div>
        </div>
      </div>
      <div
        class="w-full lg:justify-center flex flex-col md:px-6 py-16 md:min-h-fit md:py-20 relative bg-[linear-gradient(173.07deg,_#FFF8E0_43.52%,_rgba(255,255,255,0.6)_69.54%,_rgba(236,236,255,0.8)_95.01%)] overflow-hidden"
      >
        <div
          class="z-11 md:z-0 absolute w-8 h-8 md:w-16 md:h-16 rounded-full bg-[#D2ADFE] bottom-[30%] -right-[2%]"
        ></div>
        <div class="absolute w-16 h-16 rounded-full bg-[#FAC600] -bottom-[5%] left-[10%]"></div>
        <div class="absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#90a7e177] left-[5%] top-[15%]"></div>
        <div class="absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#b9f1da] left-[7%] top-[17.5%]"></div>
        <div
          class="absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#FF8E0024] -right-[2%] md:right-[1%] top-[3%]"
        ></div>
        <div
          class="absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#90a7e177] right-[1%] md:right-[3%] top-[5.5%]"
        ></div>
        <div
          class="hidden md:block absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#2AAC76] left-0 bottom-[22%]"
        ></div>
        <div
          class="hidden md:block absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#FFCC005E] -left-[1%] bottom-[18%]"
        ></div>
        <div
          class="md:hidden absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#FF8E0024] left-[2%] bottom-[12%]"
        ></div>
        <div
          class="md:hidden z-11 absolute h-6 w-6 md:w-12 md:h-12 rounded-full bg-[#90a7e177] left-[5%] bottom-[14%]"
        ></div>
        <div class="2xl:text-5xl text-xl md:text-3xl font-bold md:px-30 md:text-center text-center">
          Gifting Made Easy
        </div>
        <div
          class="mt-8 md:-mt-12 md:pt-0 md:p-10 py-10 px-4 text-lg text-gray-700 flex justify-center relative w-full"
        >
          <div
            class="md:hidden absolute z-0 w-60 h-60 rounded-4xl bg-[rgba(254,126,149,0.2)] flex justify-center items-center top-15 left-1/2 -translate-x-1/2 -translate-y-1/4"
          >
            <img fetchpriority="high" decoding="async" width="691" height="672" alt="child" class="h-52 w-52" src="/assets/ChildGift-DYcvGKrU.svg" />
          </div>
          <div
            class="relative h-70 2xl:h-110 2xl:w-180 md:h-90 md:w-130 bg-white rounded-4xl mt-25 ml-0 md:ml-40 border border-[#cc6f6f] z-10"
            style="box-shadow: rgba(235, 144, 144, 0.74) 0px 2px 8px 0px"
          >
            <div
              class="hidden md:flex w-70 h-70 2xl:h-90 2xl:w-90 rounded-4xl absolute bg-[rgba(254,126,149,0.2)] justify-center md:z-1 items-center top-[12.5%] -left-[25%] 2xl:top-[9%]"
            >
              <img decoding="async" width="691" height="672" alt="child" class="h-60 w-60 2xl:h-80 2xl:w-80" src="/assets/ChildGift-DYcvGKrU.svg" />
            </div>
            <div
              class="flex flex-col gap-2 md:gap-6 text-center justify-center md:mt-0 mt-5 items-center p-4 md:p-10 md:ml-32 2xl:mt-10"
            >
              <span class="font-semibold text-[#234394] text-lg md:text-2xl 2xl:text-3xl">Standalone Gift Session</span>
              <p class="text-[#403D3D] font-medium text-sm italic 2xl:text-base">
                One-time gift for a friend, colleague, or loved one.
              </p>
              <p class="text-[#403D3D] text-sm font-medium italic 2xl:text-base">
                Empower yourself &amp; others with mental well-being
              </p>
              <a href="/appointment.php"
                class="cursor-pointer 2xl:text-2xl bg-[#234394] flex justify-center items-center text-white rounded-full h-10 w-fit md:px-8 px-10 py-6 font-semibold p-4"
              >
                <p>Start Gifting</p>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div
        class="pb-8 relative w-full min-h-fit md:min-h-fit py-20 md:py-10 p-6 md:p-16 gap-6 md:gap-8 text-center flex flex-col justify-center items-center overflow-hidden"
      >
        <div
          class="absolute md:h-14 md:w-14 h-12 w-12 bg-[#7AE6B95E] rounded-full top-[2%] md:top-[5%] -right-[0.5%] md:right-[14%]"
        ></div>
        <div
          class="absolute md:h-14 md:w-14 h-12 w-12 bg-[#FFCC005E] rounded-full top-[3.5%] md:top-[10%] right-[5%] md:right-[16%]"
        ></div>
        <div class="md:hidden absolute h-12 w-12 rounded-full bg-[#c2cfef] -z-1 bottom-[4%] left-[3%]"></div>
        <div class="md:hidden absolute w-12 h-12 rounded-full bg-[#B9F1DA] bottom-[1%] left-[6%]"></div>
        <div class="flex flex-col gap-4 md:flex-row md:py-4 z-10 2xl:w-[90%] justify-center">
          <div
            class="gap-4 min-w-fit 2xl:p-8 w-70 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 custom-shadow"
          >
            <img loading="lazy" decoding="async" width="580" height="317" alt="img1" class="w-50 2xl:w-90" src="/assets/Gift_test-1-Bw1nidTz.svg" />
            <p class="w-50 2xl:w-80 font-normal text-sm md:text-center text-start 2xl:text-lg">
              When my friend gifted me a therapy session, I didn’t realize how much I needed it. It changed my
              perspective and gave me the support I was looking for
            </p>
          </div>
          <div
            class="gap-4 min-w-fit 2xl:p-8 w-70 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 custom-shadow"
          >
            <img loading="lazy" decoding="async" width="547" height="317" alt="img2" class="w-50 2xl:w-90" src="/assets/Gift_test-2-wR21sUIx.svg" />
            <p class="w-50 2xl:w-80 font-normal text-sm md:text-center text-start 2xl:text-lg">
              I had always wanted to try therapy, but I never took the first step. My sister’s gift helped me begin my
              journey to self-care.
            </p>
          </div>
          <div
            class="gap-4 min-w-fit 2xl:p-8 w-70 p-4 rounded-xl min-h-fit flex flex-col items-center md:m-4 custom-shadow"
          >
            <img loading="lazy" decoding="async" width="520" height="317" alt="img3" class="w-50 2xl:w-90" src="/assets/Gift_test-3-CCKZ9D9K.svg" />
            <p class="w-50 2xl:w-80 font-normal text-sm md:text-center text-start 2xl:text-lg">
              “The care team made us feel supported every step of the way.”
            </p>
          </div>
        </div>
        <p class="w-full md:w-fit md:not-italic italic 2xl:text-lg">
          A small act of kindness can make a world of difference.
        </p>
        <a href="/appointment.php"
          class="inline-block bg-[#234394] 2xl:text-2xl text-white rounded-full w-fit px-20 md:px-8 py-4 md:py-2 font-semibold cursor-pointer"
        >
          Gift Now
        </a>
        <div
          class="h-14 w-14 absolute bg-[#c2cfef] rounded-full -right-[6%] -bottom-[2%] md:left-[10%] md:-bottom-[7%]"
        ></div>
      </div>
      <div
        class="overflow-hidden relative flex flex-col items-center w-full md:min-h-fit md:py-10 bg-[#F5FCF9] p-4 md:p-8"
      >
        <div
          class="absolute w-16 h-16 rounded-full bg-[#FF8E0080] -bottom-[5%] -right-[12%] md:bottom-[3%] md:right-[-4%]"
        ></div>
        <div class="hidden md:block absolute w-16 h-16 rounded-full bg-[#46CC8D87] bottom-[40%] left-[-3%]"></div>
        <div class="hidden md:block absolute w-16 h-16 rounded-full bg-[#FF00735E] -bottom-[4%] left-[10%]"></div>
        <div
          class="absolute h-12 w-12 md:h-14 md:w-14 rounded-full bg-[#c2cfef] -left-[8%] bottom-[23%] md:-top-[2.5%] md:left-[10%]"
        ></div>
        <div
          class="absolute md:w-16 md:h-16 h-12 w-12 rounded-full bg-[#B9F1DA] -left-[4%] bottom-[18%] md:top-[2%] md:left-[13%]"
        ></div>
        <div class="h-full w-full py-12 md:p-16 gap-6 md:gap-12 flex flex-col">
          <span class="text-xl 2xl:text-5xl md:text-2xl p-4 font-bold text-center text-[#1A1A1A]"
            >Why Choose eMbrace?</span
          >
          <div
            class="h-fit md:p-8 w-fit md:px-16 mx-auto border border-black/20 rounded-tr-4xl rounded-bl-4xl bg-white"
          >
            <div class="flex md:items-center justify-start py-4 px-2 md:px-0 md:py-0 2xl:py-1">
              <img loading="lazy" decoding="async" width="60" height="60"
                alt="Confidential &amp; Expert-Led Therapy"
                class="md:w-8 md:h-12 2xl:w-10 2xl:h-10 w-6 h-6 mr-2 md:mr-4"
                src="/assets/mental-health-BYLQbdxr.svg"
              />
              <div class="md:flex">
                <span class="md:text-lg 2xl:text-xl text-sm font-semibold text-[#234394]"
                  >Confidential &amp; Expert-Led Therapy</span
                ><span class="md:text-lg text-sm 2xl:text-xl font-semibold text-[#403D3D]">
                  - Sessions with licensed professionals</span
                >
              </div>
            </div>
            <div class="flex md:items-center justify-start py-4 px-2 md:px-0 md:py-0 2xl:py-1">
              <img loading="lazy" decoding="async" width="60" height="60"
                alt="Flexible &amp; Hassle-Free Booking"
                class="md:w-8 md:h-12 2xl:w-10 2xl:h-10 w-6 h-6 mr-2 md:mr-4"
                src="/assets/calender-DGuQCWFM.svg"
              />
              <div class="md:flex">
                <span class="md:text-lg 2xl:text-xl text-sm font-semibold text-[#234394]"
                  >Flexible &amp; Hassle-Free Booking</span
                ><span class="md:text-lg text-sm 2xl:text-xl font-semibold text-[#403D3D]">
                  - Easy scheduling for recipients</span
                >
              </div>
            </div>
            <div class="flex md:items-center justify-start py-4 px-2 md:px-0 md:py-0 2xl:py-1">
              <img loading="lazy" decoding="async" width="60" height="60"
                alt="A Gift That Lasts"
                class="md:w-8 md:h-12 2xl:w-10 2xl:h-10 w-6 h-6 mr-2 md:mr-4"
                src="/assets/gift-Ds8pa8Mm.svg"
              />
              <div class="md:flex">
                <span class="md:text-lg 2xl:text-xl text-sm font-semibold text-[#234394]">A Gift That Lasts</span
                ><span class="md:text-lg text-sm 2xl:text-xl font-semibold text-[#403D3D]">
                  - Supporting mental well-being creates lasting impact</span
                >
              </div>
            </div>
          </div>
          <span class="font-medium text-sm md:text-lg text-[#403D3D] italic text-center 2xl:text-2xl"
            >Gift support, healing, and mental wellness today!
            <p class="text-center mt-4">
              <span class="text-[#234394]">Have questions? </span>Email us at<a
                class="text-[#234394]"
                href="mailto:enquiries@embracelives.com"
              >
                enquiries@embracelives.com</a
              >
            </p></span
          >
        </div>
      </div>
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  </body>
</html>
