<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="eMbrace in the news — media features, press coverage &amp; mental health awareness campaigns. See how we're shaping the conversation on neurodiversity."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/media" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/media" property="og:url" />
    <meta content="Media &amp; News | eMbrace Lives in the Press" property="og:title" />
    <meta
      content="eMbrace in the news — media features, press coverage &amp; mental health awareness campaigns. See how we're shaping the conversation on neurodiversity."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="Media &amp; News | eMbrace Lives in the Press" name="twitter:title" />
    <meta
      content="eMbrace in the news — media features, press coverage &amp; mental health awareness campaigns. See how we're shaping the conversation on neurodiversity."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>Media &amp; News | eMbrace Lives in the Press</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "CollectionPage",
        "@id": "https://embracelives.com/media#webpage",
        "url": "https://embracelives.com/media",
        "name": "Media & News | eMbrace Lives in the Press",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "eMbrace in the news — media features, press coverage & mental health awareness campaigns. See how we're shaping the conversation on neurodiversity."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div class="bg-white min-h-screen w-full relative overflow-hidden">
        <img
          alt=""
          class="absolute h-10 w-10 -left-3 hidden lg:block lg:top-[15%]"
          src="data:image/svg+xml,%3csvg%20width='120'%20height='120'%20viewBox='0%200%20120%20120'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3ccircle%20cx='60'%20cy='60'%20r='60'%20fill='%23D2ADFE96'%20fill-opacity='0.53'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute h-10 w-10 -left-3 hidden lg:block lg:top-[42%]"
          src="data:image/svg+xml,%3csvg%20width='93'%20height='91'%20viewBox='0%200%2093%2091'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20opacity='0.5'%20cx='44.5925'%20cy='46.287'%20rx='44.5925'%20ry='46.287'%20transform='matrix(0.560339%20-0.828264%200.835376%200.549679%20-17%2056.9253)'%20fill='%2390A7E1'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute h-10 w-10 right-[10%] hidden lg:block lg:top-[41%]"
          src="data:image/svg+xml,%3csvg%20width='120'%20height='120'%20viewBox='0%200%20120%20120'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3ccircle%20cx='60'%20cy='60'%20r='60'%20fill='%23FFCC008A'%20fill-opacity='0.62'%20stroke-opacity='0.55'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute h-10 w-10 left-[10%] hidden lg:block lg:top-[69%]"
          src="data:image/svg+xml,%3csvg%20width='107'%20height='114'%20viewBox='0%200%20107%20114'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20cx='53.5'%20cy='57'%20rx='53.5'%20ry='57'%20fill='%23B9F1DA'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute h-10 w-10 left-[11%] hidden lg:block lg:top-[92%]"
          src="data:image/svg+xml,%3csvg%20width='120'%20height='120'%20viewBox='0%200%20120%20120'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3ccircle%20cx='60'%20cy='60'%20r='60'%20fill='%23FFCC008A'%20fill-opacity='0.62'%20stroke-opacity='0.55'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute h-10 w-10 -right-3 hidden lg:block lg:top-[97%]"
          src="data:image/svg+xml,%3csvg%20width='120'%20height='120'%20viewBox='0%200%20120%20120'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3ccircle%20cx='60'%20cy='60'%20r='60'%20fill='%23D2ADFE96'%20fill-opacity='0.53'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute h-10 w-10 right-[10%] hidden lg:block lg:top-[68%]"
          src="data:image/svg+xml,%3csvg%20width='107'%20height='114'%20viewBox='0%200%20107%20114'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20cx='53.5'%20cy='57'%20rx='53.5'%20ry='57'%20fill='%23B9F1DA'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute h-10 w-10 right-[11%] hidden lg:block lg:top-[69%]"
          src="data:image/svg+xml,%3csvg%20width='93'%20height='91'%20viewBox='0%200%2093%2091'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20opacity='0.5'%20cx='44.5925'%20cy='46.287'%20rx='44.5925'%20ry='46.287'%20transform='matrix(0.560339%20-0.828264%200.835376%200.549679%20-17%2056.9253)'%20fill='%2390A7E1'/%3e%3c/svg%3e"
        /><style>
          .scrollbar-hide::-webkit-scrollbar {
            display: none;
          }
        </style>
        <div class="bg-[linear-gradient(to_bottom,_#6DD0FC45,_#FFFFFF)] px-4 py-6 text-center pt-15 lg:pb-10">
          <h4 class="text-black text-lg lg:text-2xl font-bold">Media Spotlight: eMbrace in the News</h4>
          <p class="text-sm italic pt-1 lg:pt-2">Our voice across platforms.</p>
          <p class="text-xs text-[#403D3D] pt-2 px-5 italic lg:w-[38%] mx-auto">
            Explore how eMbrace is shaping the conversation on mental health, neurodiversity, and inclusion across
            media, podcasts, and institutional partnerships.
          </p>
        </div>
        <div class="">
          <h5 class="text-md font-bold mb-4 text-center py-4 lg:text-lg lg:py-5">In Press</h5>
          <div class="md:hidden overflow-hidden h-[600px]">
            <div class="flex flex-col items-center space-y-4 animate-scroll">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Unfair Weather Warriors – The New Sunday Express Magazine"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card1-ImXgbZGy.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.newindianexpress.com/lifestyle/2025/May/11/unfair-weather-warriors"
                  rel="noopener noreferrer"
                  >Unfair Weather Warriors – The New Sunday Express Magazine</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  A powerful article by Dr. Supriya Malik on emotional resilience and inclusion in times of invisible
                  mental health struggles.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt='Awarded "Organization that Promotes Diversity &amp; Inclusion"'
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card2-pu-EdSuv.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/supriya-malik-ph-d-9b726619_awards-neurodiversity-inclusion-activity-7297626144197984256-Ifqs/"
                  rel="noopener noreferrer"
                  >Awarded "Organization that Promotes Diversity &amp; Inclusion"</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Honored at the 9th World Congress for Diversity &amp; Inclusion for pioneering inclusive mental health
                  practices.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="AI &amp; Mental Health"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card3-Bn-JCufN.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://ictconnect.in/Article.aspx?articletitle=8t4H4R6qXDJBMHRzveJWkJgihFR_3Sj3s63EWs7N4qleTnVicbPIEshwB2B4H0nK9ta-k0cFFsW1iBO6NlZnMA"
                  rel="noopener noreferrer"
                  >AI &amp; Mental Health</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Government of India &amp; Tamil Nadu-backed publication on tech-enabled mental health services by Dr.
                  Mahima Sahi.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt='"Key to Good Mental Health is Awareness" – Article by Dr. Supriya in Zoom Magazine'
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card4-1qB_pyj0.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black py-1 px-2"
                  href="#"
                  rel="noopener noreferrer"
                  >"Key to Good Mental Health is Awareness" – Article by Dr. Supriya in Zoom Magazine</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Early thought leadership on awareness-first approaches to well-being.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt='Awarded "BW 40 under 40" – Healthcare Category, 2022'
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card5-BzY2vcQL.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.bwhealthcareworld.com/article/honouring-healthcare-world%E2%80%99s-40-under-40-420395"
                  rel="noopener noreferrer"
                  >Awarded "BW 40 under 40" – Healthcare Category, 2022</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik honoured with BW 40 under 40 Healthcare for outstanding achievement to healthcare.
                </p>
              </div>
            </div>
          </div>
          <div class="hidden md:flex overflow-x-auto scrollbar-hide gap-6 px-4 pb-2" style="scrollbar-width: none">
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Unfair Weather Warriors – The New Sunday Express Magazine"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card1-ImXgbZGy.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.newindianexpress.com/lifestyle/2025/May/11/unfair-weather-warriors"
                  rel="noopener noreferrer"
                  >Unfair Weather Warriors – The New Sunday Express Magazine</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  A powerful article by Dr. Supriya Malik on emotional resilience and inclusion in times of invisible
                  mental health struggles.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt='Awarded "Organization that Promotes Diversity &amp; Inclusion"'
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card2-pu-EdSuv.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/supriya-malik-ph-d-9b726619_awards-neurodiversity-inclusion-activity-7297626144197984256-Ifqs/"
                  rel="noopener noreferrer"
                  >Awarded "Organization that Promotes Diversity &amp; Inclusion"</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Honored at the 9th World Congress for Diversity &amp; Inclusion for pioneering inclusive mental health
                  practices.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="AI &amp; Mental Health"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card3-Bn-JCufN.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://ictconnect.in/Article.aspx?articletitle=8t4H4R6qXDJBMHRzveJWkJgihFR_3Sj3s63EWs7N4qleTnVicbPIEshwB2B4H0nK9ta-k0cFFsW1iBO6NlZnMA"
                  rel="noopener noreferrer"
                  >AI &amp; Mental Health</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Government of India &amp; Tamil Nadu-backed publication on tech-enabled mental health services by Dr.
                  Mahima Sahi.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt='"Key to Good Mental Health is Awareness" – Article by Dr. Supriya in Zoom Magazine'
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card4-1qB_pyj0.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black py-1 px-2"
                  href="#"
                  rel="noopener noreferrer"
                  >"Key to Good Mental Health is Awareness" – Article by Dr. Supriya in Zoom Magazine</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Early thought leadership on awareness-first approaches to well-being.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt='Awarded "BW 40 under 40" – Healthcare Category, 2022'
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card5-BzY2vcQL.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.bwhealthcareworld.com/article/honouring-healthcare-world%E2%80%99s-40-under-40-420395"
                  rel="noopener noreferrer"
                  >Awarded "BW 40 under 40" – Healthcare Category, 2022</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik honoured with BW 40 under 40 Healthcare for outstanding achievement to healthcare.
                </p>
              </div>
            </div>
          </div>
          <div class="lg:flex justify-center space-x-2 mt-4 hidden">
            <span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#234394]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span>
          </div>
        </div>
        <div class="bg-[linear-gradient(to_bottom,_#E6FFFD99,_#FEF9FC)]">
          <h5 class="text-md lg:text-lg font-bold mb-4 text-center py-4">Podcasts &amp; Panels</h5>
          <div class="md:hidden overflow-hidden h-[600px]">
            <div class="flex flex-col items-center space-y-4 animate-scroll">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Making sense of ADHD across culture gender &amp; lived experiences"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/Mynd-aw1UC8kb.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://myndstories.com/allpodcast/making-sense-of-adhd-across-culture-gender-and-lived-experience/ "
                  rel="noopener noreferrer"
                  >Making sense of ADHD across culture gender &amp; lived experiences</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya &amp; Dr. Mahima discuss ADHD and its impact on adult relationships
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Podcast on Parenting Neurodivergent Children - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card2-hdAdLOv2.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://open.spotify.com/episode/17rSM3bXKHidHndmCrDrWS"
                  rel="noopener noreferrer"
                  >Podcast on Parenting Neurodivergent Children - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik shares insights on compassion-led parenting for neurodivergent children.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Rising 2023 Women in Tech"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card3-4U-ZnHuw.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://rising.analyticsindiamag.com/speaker/supriya-malik/"
                  rel="noopener noreferrer"
                  >Rising 2023 Women in Tech</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik invited to speak on Neurodiversity in Tech as a leading voice in inclusive mental
                  health.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Podcast: Creating Space for Neurodivergence - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card4-CDQebk9g.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://open.spotify.com/episode/1a7NevvAv3s4CohTxMpiMB"
                  rel="noopener noreferrer"
                  >Podcast: Creating Space for Neurodivergence - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi on systemic barriers and inclusive carein neurodivergent issues.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Doctube Webisode 8 – Indian Menopause Society"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card5-8d5JpuLO.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/mahimasahi_mentalhealth-menopause-womenmentalhealth-activity-7285980330673545220-cPqn/"
                  rel="noopener noreferrer"
                  >Doctube Webisode 8 – Indian Menopause Society</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi joins as panelist to 'Menopause &amp; Mental Health'
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Radio Masti Singapore – MastiAVI Exclusive Interview"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card6-BRB1C9eu.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.facebook.com/radiomasti24x7/videos/1074958017566751/"
                  rel="noopener noreferrer"
                  >Radio Masti Singapore – MastiAVI Exclusive Interview</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Spotlight on Dr. Mahima Sahi's work in digital-first mental health.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Workshop at AIIMS - hosted by Indian Academy of Neurology"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card7-Cq5PwFTF.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/supriya-malik-ph-d-9b726619_gratitude-trainings-adhd-activity-7293911537805602816-l0JO/"
                  rel="noopener noreferrer"
                  >Workshop at AIIMS - hosted by Indian Academy of Neurology</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik's global training on Positive Behavior Supports.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Webinar: Psychological Effects of Environmental &amp; Women's Health"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card8-OX_YWUJV.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black py-1 px-2"
                  href="#"
                  rel="noopener noreferrer"
                  >Webinar: Psychological Effects of Environmental &amp; Women's Health</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Presented by Dr. Mahima Sahi for gynecological and mental health integration.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="UpTodd Podcast &amp; Blog Feature"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card9-JxtDqZsB.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.youtube.com/watch?v=5OQL_CxIoys&amp;ab_channel=UpTodd"
                  rel="noopener noreferrer"
                  >UpTodd Podcast &amp; Blog Feature</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Video on screen time and early development, featured in their Expert Talks.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Artemis Online Counselling Connect - Fortis Mental Health Department"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card10-2U7QtOA_.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.bwhealthcareworld.com/article/artemis-hospitals-hosts-seminar-on-telehealth-ai-in-mental-wellness-523141"
                  rel="noopener noreferrer"
                  >Artemis Online Counselling Connect - Fortis Mental Health Department</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi &amp; Dr. Supriya Malik represent embrace in a panel &amp; presentation at Artemis.
                </p>
              </div>
            </div>
          </div>
          <div class="hidden md:flex overflow-x-auto scrollbar-hide gap-6 px-4 pb-2" style="scrollbar-width: none">
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Making sense of ADHD across culture gender &amp; lived experiences"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/Mynd-aw1UC8kb.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://myndstories.com/allpodcast/making-sense-of-adhd-across-culture-gender-and-lived-experience/ "
                  rel="noopener noreferrer"
                  >Making sense of ADHD across culture gender &amp; lived experiences</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya &amp; Dr. Mahima discuss ADHD and its impact on adult relationships
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Podcast on Parenting Neurodivergent Children - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card2-hdAdLOv2.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://open.spotify.com/episode/17rSM3bXKHidHndmCrDrWS"
                  rel="noopener noreferrer"
                  >Podcast on Parenting Neurodivergent Children - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik shares insights on compassion-led parenting for neurodivergent children.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Rising 2023 Women in Tech"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card3-4U-ZnHuw.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://rising.analyticsindiamag.com/speaker/supriya-malik/"
                  rel="noopener noreferrer"
                  >Rising 2023 Women in Tech</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik invited to speak on Neurodiversity in Tech as a leading voice in inclusive mental
                  health.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Podcast: Creating Space for Neurodivergence - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card4-CDQebk9g.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://open.spotify.com/episode/1a7NevvAv3s4CohTxMpiMB"
                  rel="noopener noreferrer"
                  >Podcast: Creating Space for Neurodivergence - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi on systemic barriers and inclusive carein neurodivergent issues.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Doctube Webisode 8 – Indian Menopause Society"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card5-8d5JpuLO.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/mahimasahi_mentalhealth-menopause-womenmentalhealth-activity-7285980330673545220-cPqn/"
                  rel="noopener noreferrer"
                  >Doctube Webisode 8 – Indian Menopause Society</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi joins as panelist to 'Menopause &amp; Mental Health'
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Radio Masti Singapore – MastiAVI Exclusive Interview"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card6-BRB1C9eu.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.facebook.com/radiomasti24x7/videos/1074958017566751/"
                  rel="noopener noreferrer"
                  >Radio Masti Singapore – MastiAVI Exclusive Interview</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Spotlight on Dr. Mahima Sahi's work in digital-first mental health.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Workshop at AIIMS - hosted by Indian Academy of Neurology"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card7-Cq5PwFTF.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/supriya-malik-ph-d-9b726619_gratitude-trainings-adhd-activity-7293911537805602816-l0JO/"
                  rel="noopener noreferrer"
                  >Workshop at AIIMS - hosted by Indian Academy of Neurology</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Supriya Malik's global training on Positive Behavior Supports.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Webinar: Psychological Effects of Environmental &amp; Women's Health"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card8-OX_YWUJV.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black py-1 px-2"
                  href="#"
                  rel="noopener noreferrer"
                  >Webinar: Psychological Effects of Environmental &amp; Women's Health</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Presented by Dr. Mahima Sahi for gynecological and mental health integration.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="UpTodd Podcast &amp; Blog Feature"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card9-JxtDqZsB.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.youtube.com/watch?v=5OQL_CxIoys&amp;ab_channel=UpTodd"
                  rel="noopener noreferrer"
                  >UpTodd Podcast &amp; Blog Feature</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Video on screen time and early development, featured in their Expert Talks.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Artemis Online Counselling Connect - Fortis Mental Health Department"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card10-2U7QtOA_.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.bwhealthcareworld.com/article/artemis-hospitals-hosts-seminar-on-telehealth-ai-in-mental-wellness-523141"
                  rel="noopener noreferrer"
                  >Artemis Online Counselling Connect - Fortis Mental Health Department</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi &amp; Dr. Supriya Malik represent embrace in a panel &amp; presentation at Artemis.
                </p>
              </div>
            </div>
          </div>
          <div class="lg:flex justify-center space-x-2 mt-4 hidden">
            <span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#234394]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span>
          </div>
        </div>
        <div class="py-6 space-y-6">
          <h5 class="text-md lg:text-lg font-bold mb-4 text-center py-4">Collaborations</h5>
          <div class="md:hidden overflow-hidden h-[1200px]">
            <div class="flex flex-col items-center space-y-4 animate-scroll">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Caregivers &amp; Autism - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card1-D7K00Rlt.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://myndstories.com/product/supporting-caregivers-of-individuals-with-autism/"
                  rel="noopener noreferrer"
                  >Caregivers &amp; Autism - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Taranpreet Kaur leads session on supporting caregivers of individuals with autism.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="ADHD at Work - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card1-D7K00Rlt.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://myndstories.com/product/neurodivergence-series-part-1-harnessing-adhd-at-work/"
                  rel="noopener noreferrer"
                  >ADHD at Work - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Taranpreet Kaur leads Neurodivergence Series Part 1 with practical tips for workplace focus.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Autism at Work @ Amazon - in"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card3-CGK_QcDd.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/mahimasahi_neurodiversity-inclusion-changethenarrative-activity-7328707305800118272-VD44?utm_source=share&amp;utm_medium=member_desktop&amp;rcm=ACoAAAvm8G8B_A0a5MlnNkLKwgIJUrsuI2DmGC4"
                  rel="noopener noreferrer"
                  >Autism at Work @ Amazon - in</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima leads session with 100+ HR leaders on hiring &amp; inclusion &amp; partnership with
                  Atypical Advantage.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Workplace Wellbeing with The Union (USAID)"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card4-B3pHMjIT.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://theunion.org/"
                  rel="noopener noreferrer"
                  >Workplace Wellbeing with The Union (USAID)</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Session on mental health in high-pressure public health environments by Dr. Mahima Sahi.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Neurodiversity at Work - Workshop with Ashoka University"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card5-DgPC6hsC.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.ashoka.edu.in/ols-awareness-campaigns/"
                  rel="noopener noreferrer"
                  >Neurodiversity at Work - Workshop with Ashoka University</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Hosted by Dr. Supriya Malik in partnership with Atypical Advantage.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Neurodiversity at Work - Workshops with Allianz"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card6-CyRvqOla.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://tech.allianz.com/en.php"
                  rel="noopener noreferrer"
                  >Neurodiversity at Work - Workshops with Allianz</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Hosted by Dr. Supriya Malik in partnership with Atypical Advantage.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Neurodiversity at Work - Workshops with RMZ"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card7-CxaZ9P9X.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.r1rcm.com/"
                  rel="noopener noreferrer"
                  >Neurodiversity at Work - Workshops with RMZ</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Hosted by Dr. Supriya Malik in partnership with Atypical Advantage.
                </p>
              </div>
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Digital Wellbeing &amp; Cybersafety Workshop- The Doon School"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card8-DMqRkChg.jpeg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black py-1 px-2"
                  href="#"
                  rel="noopener noreferrer"
                  >Digital Wellbeing &amp; Cybersafety Workshop- The Doon School</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi leads the Digital Wellbeing Workshop 5 session series at the Doon School on digtal
                  risks &amp; safety.
                </p>
              </div>
            </div>
          </div>
          <div class="hidden md:flex overflow-x-auto scrollbar-hide gap-6 px-4 pb-2" style="scrollbar-width: none">
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Caregivers &amp; Autism - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card1-D7K00Rlt.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://myndstories.com/product/supporting-caregivers-of-individuals-with-autism/"
                  rel="noopener noreferrer"
                  >Caregivers &amp; Autism - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Taranpreet Kaur leads session on supporting caregivers of individuals with autism.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="ADHD at Work - Myndstories"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card1-D7K00Rlt.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://myndstories.com/product/neurodivergence-series-part-1-harnessing-adhd-at-work/"
                  rel="noopener noreferrer"
                  >ADHD at Work - Myndstories</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Taranpreet Kaur leads Neurodivergence Series Part 1 with practical tips for workplace focus.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Autism at Work @ Amazon - in"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card3-CGK_QcDd.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.linkedin.com/posts/mahimasahi_neurodiversity-inclusion-changethenarrative-activity-7328707305800118272-VD44?utm_source=share&amp;utm_medium=member_desktop&amp;rcm=ACoAAAvm8G8B_A0a5MlnNkLKwgIJUrsuI2DmGC4"
                  rel="noopener noreferrer"
                  >Autism at Work @ Amazon - in</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima leads session with 100+ HR leaders on hiring &amp; inclusion &amp; partnership with
                  Atypical Advantage.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Workplace Wellbeing with The Union (USAID)"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card4-B3pHMjIT.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://theunion.org/"
                  rel="noopener noreferrer"
                  >Workplace Wellbeing with The Union (USAID)</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Session on mental health in high-pressure public health environments by Dr. Mahima Sahi.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Neurodiversity at Work - Workshop with Ashoka University"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card5-DgPC6hsC.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.ashoka.edu.in/ols-awareness-campaigns/"
                  rel="noopener noreferrer"
                  >Neurodiversity at Work - Workshop with Ashoka University</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Hosted by Dr. Supriya Malik in partnership with Atypical Advantage.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Neurodiversity at Work - Workshops with Allianz"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card6-CyRvqOla.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://tech.allianz.com/en.php"
                  rel="noopener noreferrer"
                  >Neurodiversity at Work - Workshops with Allianz</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Hosted by Dr. Supriya Malik in partnership with Atypical Advantage.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Neurodiversity at Work - Workshops with RMZ"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card7-CxaZ9P9X.svg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black underline underline-offset-4 py-1 px-2"
                  href="https://www.r1rcm.com/"
                  rel="noopener noreferrer"
                  >Neurodiversity at Work - Workshops with RMZ</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Hosted by Dr. Supriya Malik in partnership with Atypical Advantage.
                </p>
              </div>
            </div>
            <div class="w-80 flex-shrink-0">
              <div
                class="bg-white rounded-2xl shadow-md p-4 flex flex-col items-center text-center space-y-2 w-[90%] h-70 lg:h-80 flex-shrink-0"
              >
                <img
                  alt="Digital Wellbeing &amp; Cybersafety Workshop- The Doon School"
                  class="w-20 h-20 lg:w-40 lg:h-25 object-contain"
                  src="/assets/card8-DMqRkChg.jpeg"
                /><a
                  class="text-[14px] lg:text-[15px] font-bold text-black py-1 px-2"
                  href="#"
                  rel="noopener noreferrer"
                  >Digital Wellbeing &amp; Cybersafety Workshop- The Doon School</a
                >
                <p class="text-[13px] text-[#403D3D] leading-5 text-left [word-spacing:1em] px-5">
                  Dr. Mahima Sahi leads the Digital Wellbeing Workshop 5 session series at the Doon School on digtal
                  risks &amp; safety.
                </p>
              </div>
            </div>
          </div>
          <div class="lg:flex justify-center space-x-2 mt-4 hidden">
            <span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#234394]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span
            ><span class="h-2.5 w-2.5 rounded-full cursor-pointer transition-all duration-300 bg-[#767676]"></span>
          </div>
        </div>
        <!-- Real Event Photo Gallery -->
        <div class="mt-8 pb-4">
          <h5 class="text-md lg:text-lg font-bold mb-2 text-center py-4">eMbrace in Action</h5>
          <p class="text-center text-sm text-[#403D3D] italic mb-6">Behind the scenes — real workshops, real moments, real impact.</p>
          <div class="columns-2 md:columns-3 lg:columns-4 gap-4 px-4">
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Workshop - Dr. Supriya" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-03-27-14-56-26.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Event - Dr. Supriya" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-03-27-14-55-34.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="Bangalore - The Rising Event" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1537.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Workshop Session" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-06-03-14-40-06.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="Bangalore - The Rising Event" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1534.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Team Workshop" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-09-11-23-16-05.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="Bangalore - The Rising Event" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1527.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Event Photo" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2026-02-18-09-44-21.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Workshop" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-10-06-20-23-03.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="Bangalore - The Rising Event" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/Bangalore%20The%20Rising/IMG_1530.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Panel Discussion" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-03-21-12-02-00.jpg" />
            </div>
            <div class="rounded-2xl overflow-hidden break-inside-avoid shadow-sm mb-4">
              <img alt="eMbrace Workshop Photo" class="w-full h-auto block object-cover hover:scale-105 transition-transform duration-500" loading="lazy" src="/embrace-media/Dr%20Supriya%20Photos-20260806T082436Z-1-001/Dr%20Supriya%20Photos/PHOTO-2025-04-03-12-06-22.jpg" />
            </div>
          </div>
        </div>
        <p class="text-xs text-center font-semibold text-[#403D3D] px-6 pb-5 lg:py-10 lg:text-sm italic">
          For any media collaborations or partnerships, please write to us at
          <a class="font-semibold text-[#234394] italic underline" href="mailto:enquiries@embracelives.com"
            >enquiries@embracelives.com</a
          >
        </p>
      </div>
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  </body>
</html>
