<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="Meet our team of RCI-certified clinical psychologists, child psychologists, speech therapists &amp; occupational therapists. Find the right therapist for you."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/practitioner" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/practitioner" property="og:url" />
    <meta content="Our Therapists &amp; Psychologists | eMbrace Lives" property="og:title" />
    <meta
      content="Meet our team of RCI-certified clinical psychologists, child psychologists, speech therapists &amp; occupational therapists. Find the right therapist for you."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="Our Therapists &amp; Psychologists | eMbrace Lives" name="twitter:title" />
    <meta
      content="Meet our team of RCI-certified clinical psychologists, child psychologists, speech therapists &amp; occupational therapists. Find the right therapist for you."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>Our Therapists &amp; Psychologists | eMbrace Lives</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  
  
  
  
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "CollectionPage",
        "@id": "https://embracelives.com/practitioner#webpage",
        "url": "https://embracelives.com/practitioner",
        "name": "Our Therapists & Psychologists | eMbrace Lives",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Meet our team of RCI-certified clinical psychologists, child psychologists, speech therapists & occupational therapists. Find the right therapist for you."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <!-- Hero Section -->
      <main>
        <section
          class="px-4 md:px-8 lg:px-16 xl:px-24 2xl:px-50 bg-gradient-to-b from-[#E7F7FF] to-[#FFFFFF] relative overflow-hidden py-16 md:py-24 flex flex-col items-center"
        >
          <div class="bg-[#7AE6B95E] h-14 w-14 rounded-full absolute hidden md:block top-[10%] -right-[2%]"></div>
          <div class="bg-[#B9F1DA] h-12 w-12 rounded-full absolute hidden md:block top-[15%] left-[5%]"></div>
          <div class="bg-[#FFCC004A] h-14 w-14 rounded-full absolute -bottom-[4%] left-[6%] md:left-[15%]"></div>
          <div class="flex flex-col items-center justify-center max-w-4xl mx-auto text-center">
            <h1 class="text-3xl md:text-4xl 2xl:text-5xl font-bold">Our Therapists &amp; Psychologists</h1>
            <p
              class="2xl:mt-4 2xl:text-2xl font-medium text-base md:text-lg text-center text-[var(--text-gray)] italic mt-4 md:mt-6"
            >
              Meet our team of
              <span class="text-[#234394]"
                >RCI-certified clinical psychologists, child psychologists, speech therapists &amp; occupational
                therapists</span
              >
              — each bringing specialised expertise to support your mental health journey.
            </p>
          </div>
        </section>

        <!-- Specialties Section -->
        <section class="px-4 md:px-8 lg:px-16 xl:px-24 py-12 md:py-16 relative">
          <div class="bg-[#FFAAF99E] w-14 h-14 hidden md:block rounded-full absolute -right-[1.75%] top-[10%]"></div>
          <div class="bg-[#AAAAFF61] w-14 h-14 hidden md:block absolute rounded-full bottom-0 left-[5%]"></div>
          <div class="flex flex-col items-center justify-center max-w-5xl mx-auto">
            <h2 class="md:text-3xl text-xl font-bold text-center 2xl:text-4xl">Areas of Expertise</h2>
            <p
              class="font-medium text-sm md:text-base text-center text-[var(--text-gray)] italic mt-4 md:mt-6 max-w-2xl"
            >
              Our therapists specialise across a wide range of conditions and age groups, ensuring you receive expert,
              personalised care.
            </p>
            <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4 md:gap-6 mt-10 w-full">
              <div
                class="bg-white border border-[#ADADAD] rounded-3xl shadow-md p-5 flex flex-col items-center text-center"
              >
                <div class="w-12 h-12 rounded-full bg-[#E7F7FF] flex items-center justify-center text-2xl mb-3">🧠</div>
                <h3 class="text-sm md:text-base font-semibold text-[#234394]">Clinical Psychology</h3>
                <p class="text-xs md:text-sm text-gray-600 mt-1">Anxiety, Depression, OCD, PTSD &amp; more</p>
              </div>
              <div
                class="bg-white border border-[#ADADAD] rounded-3xl shadow-md p-5 flex flex-col items-center text-center"
              >
                <div class="w-12 h-12 rounded-full bg-[#FEF3F7] flex items-center justify-center text-2xl mb-3">👶</div>
                <h3 class="text-sm md:text-base font-semibold text-[#234394]">Child Psychology</h3>
                <p class="text-xs md:text-sm text-gray-600 mt-1">ADHD, Autism, Developmental Delays</p>
              </div>
              <div
                class="bg-white border border-[#ADADAD] rounded-3xl shadow-md p-5 flex flex-col items-center text-center"
              >
                <div class="w-12 h-12 rounded-full bg-[#F1E6FF] flex items-center justify-center text-2xl mb-3">🗣️</div>
                <h3 class="text-sm md:text-base font-semibold text-[#234394]">Speech Therapy</h3>
                <p class="text-xs md:text-sm text-gray-600 mt-1">Speech clarity, language &amp; communication</p>
              </div>
              <div
                class="bg-white border border-[#ADADAD] rounded-3xl shadow-md p-5 flex flex-col items-center text-center"
              >
                <div class="w-12 h-12 rounded-full bg-[#FFF8E0] flex items-center justify-center text-2xl mb-3">🤲</div>
                <h3 class="text-sm md:text-base font-semibold text-[#234394]">Occupational Therapy</h3>
                <p class="text-xs md:text-sm text-gray-600 mt-1">Motor, sensory &amp; daily living skills</p>
              </div>
            </div>
          </div>
        </section>

        <!-- CTA Section -->
        <section
          class="bg-gradient-to-b from-[#F1E6FF] to-[#FEF9FC] py-16 md:py-12 w-full flex overflow-hidden justify-center relative"
        >
          <div class="bg-[#D82D7E87] h-14 w-14 rounded-full absolute -top-[10%] right-[5%] md:right-[15%]"></div>
          <div class="bg-[#FAC600] h-12 w-12 rounded-full absolute -bottom-[10%] left-[5%] md:left-[38%]"></div>
          <div class="w-full md:w-[60%] flex flex-col items-center justify-center gap-4 md:gap-6 px-4">
            <h2 class="text-xl md:text-2xl 2xl:text-3xl font-bold text-center">Find the Right Therapist for You</h2>
            <p class="2xl:text-2xl font-medium text-base md:text-lg text-center text-[var(--text-gray)] italic">
              Browse our <span class="text-[#234394]">full team of experts</span> and book a consultation today
            </p>
            <div class="flex flex-col sm:flex-row gap-4 mt-2">
              <a
                href="/userListing.php"
                class="2xl:text-2xl px-8 py-2 rounded-full bg-[var(--blue-fig)] text-white font-medium cursor-pointer text-center"
                >Browse All Therapists</a
              >
              <a
                href="/contact-us.php"
                class="2xl:text-2xl px-8 py-2 rounded-full border-2 border-[var(--blue-fig)] text-[var(--blue-fig)] font-medium cursor-pointer text-center"
                >Contact Us</a
              >
            </div>
          </div>
        </section>
      </main>
      <!-- LOCATION-LINKS:START (generated by generate-location-links.js — do not edit by hand) -->
<div class="px-6 md:px-16 bg-white">
<div class="max-w-7xl mx-auto">
<section class="emb-nearby" aria-labelledby="emb-nearby-title">
  <h2 class="emb-nearby__title" id="emb-nearby-title">Child Psychologist across Delhi NCR</h2>
  <p class="emb-nearby__sub">We offer child psychology consultations at eMbrace centres throughout Delhi and the wider NCR. Choose the location closest to you.</p>
  <div class="emb-nearby__cols">
    <div class="emb-nearby__group">
      <ul class="emb-nearby__list emb-nearby__list--wide">
      <li><a href="/locations/child-psychologist-in-delhi">Child Psychologist in Delhi</a></li>
      <li><a href="/locations/child-psychologist-in-south-delhi">Child Psychologist in South Delhi</a></li>
      <li><a href="/locations/child-psychologist-in-saket">Child Psychologist in Saket</a></li>
      <li><a href="/locations/child-psychologist-in-hauz-khas">Child Psychologist in Hauz Khas</a></li>
      <li><a href="/locations/child-psychologist-in-green-park">Child Psychologist in Green Park</a></li>
      <li><a href="/locations/child-psychologist-in-greater-kailash">Child Psychologist in Greater Kailash</a></li>
      <li><a href="/locations/child-psychologist-in-defence-colony">Child Psychologist in Defence Colony</a></li>
      <li><a href="/locations/child-psychologist-in-vasant-kunj">Child Psychologist in Vasant Kunj</a></li>
      <li><a href="/locations/child-psychologist-in-gurgaon">Child Psychologist in Gurgaon</a></li>
      <li><a href="/locations/child-psychologist-in-noida">Child Psychologist in Noida</a></li>
      </ul>
    </div>
  </div>
  <a class="emb-nearby__more" href="/locations">View all eMbrace locations &rsaquo;</a>
</section>
</div>
</div>
<!-- LOCATION-LINKS:END -->
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  </body>
</html>
