<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="Complete SEO sitemap for eMbrace Lives – all website pages organized by service cluster." name="description" />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/seo_sitemap" rel="canonical" />
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/seo_sitemap" property="og:url" />
    <meta content="SEO Sitemap | eMbrace Lives" property="og:title" />
    <meta content="Complete SEO sitemap for eMbrace Lives – all website pages organized by service cluster." property="og:description" />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="SEO Sitemap | eMbrace Lives" name="twitter:title" />
    <meta content="Complete SEO sitemap for eMbrace Lives – all website pages organized by service cluster." name="twitter:description" />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <title>SEO Sitemap | eMbrace Lives</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />
    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style>
      body { font-family: system-ui, -apple-system, sans-serif; background: #f8fafc; }
      .sitemap-container { max-width: 1200px; margin: 0 auto; padding: 2rem 1rem; }
      h1 { color: #234394; font-size: 2rem; margin-bottom: 0.5rem; }
      .cluster { background: white; border-radius: 12px; padding: 1.5rem; margin-bottom: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
      .cluster h2 { color: #234394; font-size: 1.3rem; margin-bottom: 1rem; border-bottom: 2px solid #e0e6f0; padding-bottom: 0.5rem; }
      .cluster h2 span { font-size: 0.85rem; color: #6b7280; font-weight: 400; }
      .url-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 0.5rem; }
      .url-grid a { color: #403d3d; text-decoration: none; font-size: 0.875rem; padding: 0.4rem 0.6rem; border-radius: 6px; transition: all 0.15s; }
      .url-grid a:hover { background: #e7f7ff; color: #234394; }
      .done { background: #dcfce7; border-radius: 4px; padding: 0 0.3rem; font-size: 0.7rem; color: #166534; margin-left: 0.3rem; }
      .pending-badge { background: #fef3c7; border-radius: 4px; padding: 0 0.3rem; font-size: 0.7rem; color: #92400e; margin-left: 0.3rem; }
    </style>
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "CollectionPage",
        "@id": "https://embracelives.com/seo_sitemap#webpage",
        "url": "https://embracelives.com/seo_sitemap",
        "name": "SEO Sitemap | eMbrace Lives",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Complete SEO sitemap for eMbrace Lives – all website pages organized by service cluster."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div class="sitemap-container">
        <h1>eMbrace Lives – SEO Sitemap</h1>
        <p style="color: #6b7280; margin-bottom: 2rem;">Target Domain: https://embracelives.com/ &bull; Generated: 2026-06-30</p>

        <div class="cluster">
          <h2>Core Pages <span>(18 pages)</span></h2>
          <div class="url-grid">
            <a href="/index.php">/</a>
            <a href="/about.php">/about-us</a>
            <a href="/careers.php">/careers</a>
            <a href="/contact-us.php">/contact-us</a>
            <a href="/faq.php">/faq</a>
            <a href="/appointment.php">/appointment</a>
            <a href="/appointment__confirmation.php">/appointment/confirmation</a>
            <a href="/bookingandCancellation.php">/bookingandCancellation</a>
            <a href="/privacypolicy.php">/privacypolicy</a>
            <a href="/terms_and_conditions.php">/terms_and_conditions</a>
            <a href="/giftatherapy.php">/giftatherapy</a>
            <a href="/media.php">/media</a>
            <a href="/practitioner.php">/our-team</a>
            <a href="/userListing.php">/userListing</a>
          </div>
        </div>

        <div class="cluster">
          <h2>Autism Cluster <span>(45 pages) ✅ Done</span></h2>
          <div class="url-grid">
            <a href="/autism/autism.php">/autism</a>
            <a href="/autism/what-is-autism.php">/what-is-autism</a>
            <a href="/autism/autism-spectrum-disorder.php">/autism-spectrum-disorder</a>
            <a href="/autism/signs-of-autism.php">/signs-of-autism</a>
            <a href="/autism/autism-symptoms.php">/autism-symptoms</a>
            <a href="/autism/social-communication-deficits.php">/social-communication-deficits</a>
            <a href="/autism/restricted-repetitive-behaviours.php">/restricted-repetitive-behaviours</a>
            <a href="/autism/autism-in-toddlers.php">/autism-in-toddlers</a>
            <a href="/autism/autism-in-preschoolers.php">/autism-in-preschoolers</a>
            <a href="/autism/autism-in-school-age-children.php">/autism-in-school-age-children</a>
            <a href="/autism/autism-in-adolescents.php">/autism-in-adolescents</a>
            <a href="/autism/autism-in-adults.php">/autism-in-adults</a>
            <a href="/autism/autism-in-girls.php">/autism-in-girls</a>
            <a href="/autism/autism-in-boys.php">/autism-in-boys</a>
            <a href="/autism/late-autism-diagnosis.php">/late-autism-diagnosis</a>
            <a href="/autism/high-functioning-autism.php">/high-functioning-autism</a>
            <a href="/autism/level-1-autism.php">/level-1-autism</a>
            <a href="/autism/level-2-autism.php">/level-2-autism</a>
            <a href="/autism/level-3-autism.php">/level-3-autism</a>
            <a href="/autism/autism-screening.php">/autism-screening</a>
            <a href="/autism/autism-testing.php">/autism-testing</a>
            <a href="/autism/autism-assessment.php">/autism-assessment</a>
            <a href="/autism/ados-2-assessment.php">/ados-2-assessment</a>
            <a href="/autism/autism-diagnostic-evaluation.php">/autism-diagnostic-evaluation</a>
            <a href="/autism/autism-treatment.php">/autism-treatment</a>
            <a href="/autism/autism-therapy.php">/autism-therapy</a>
            <a href="/autism/autism-behaviour-therapy.php">/autism-behaviour-therapy</a>
            <a href="/autism/autism-occupational-therapy.php">/autism-occupational-therapy</a>
            <a href="/autism/autism-speech-therapy.php">/autism-speech-therapy</a>
            <a href="/autism/autism-social-skills.php">/autism-social-skills</a>
            <a href="/autism/autism-parent-training.php">/autism-parent-training</a>
            <a href="/autism/autism-sensory-needs.php">/autism-sensory-needs</a>
            <a href="/autism/autism-school-support.php">/autism-school-support</a>
            <a href="/autism/autism-inclusive-education.php">/autism-inclusive-education</a>
            <a href="/autism/autism-transition-to-adulthood.php">/autism-transition-to-adulthood</a>
            <a href="/autism/autism-workplace-support.php">/autism-workplace-support</a>
            <a href="/autism/autism-and-anxiety.php">/autism-and-anxiety</a>
            <a href="/autism/autism-and-adhd.php">/autism-and-adhd</a>
            <a href="/autism/autism-and-learning-disabilities.php">/autism-and-learning-disabilities</a>
            <a href="/autism/autism-and-sleep.php">/autism-and-sleep</a>
            <a href="/autism/autism-and-feeding.php">/autism-and-feeding</a>
            <a href="/autism/autism-and-emotional-regulation.php">/autism-and-emotional-regulation</a>
            <a href="/autism/autism-faq.php">/autism-faq</a>
            <a href="/autism/autism-resources.php">/autism-resources</a>
            <a href="/autism/autism-support-groups.php">/autism-support-groups</a>
          </div>
        </div>

        <div class="cluster">
          <h2>ADHD Cluster <span>(35 pages)</span></h2>
          <div class="url-grid">
            <a href="/adhd/adhd.php">/adhd</a>
            <a href="/adhd/what-is-adhd.php">/what-is-adhd</a>
            <a href="/adhd/adhd-symptoms.php">/adhd-symptoms</a>
            <a href="/adhd/adhd-in-children.php">/adhd-in-children</a>
            <a href="/adhd/adhd-in-teens.php">/adhd-in-teens</a>
            <a href="/adhd/adult-adhd.php">/adult-adhd</a>
            <a href="/adhd/adhd-in-women.php">/adhd-in-women</a>
            <a href="/adhd/adhd-in-men.php">/adhd-in-men</a>
            <a href="/adhd/adhd-screening.php">/adhd-screening</a>
            <a href="/adhd/adhd-assessment.php">/adhd-assessment</a>
            <a href="/adhd/conners-3-assessment.php">/conners-3-assessment</a>
            <a href="/adhd/adhd-testing.php">/adhd-testing</a>
            <a href="/adhd/adhd-treatment.php">/adhd-treatment</a>
            <a href="/adhd/adhd-counselling.php">/adhd-counselling</a>
            <a href="/adhd/adhd-coaching.php">/adhd-coaching</a>
            <a href="/adhd/executive-function-coaching.php">/executive-function-coaching</a>
            <a href="/adhd/adhd-faq.php">/adhd-faq</a>
            <a href="/adhd/adhd-resources.php">/adhd-resources</a>
            <a href="/adhd/adhd-at-work.php">/adhd-at-work</a>
            <a href="/adhd/adhd-and-anxiety.php">/adhd-and-anxiety</a>
            <a href="/adhd/adhd-and-autism.php">/adhd-and-autism</a>
            <a href="/adhd/adhd-and-depression.php">/adhd-and-depression</a>
            <a href="/adhd/attention-difficulties.php">/attention-difficulties</a>
            <a href="/adhd/focus-and-concentration.php">/focus-and-concentration</a>
            <a href="/adhd/impulse-control.php">/impulse-control</a>
            <a href="/adhd/hyperactivity.php">/hyperactivity</a>
            <a href="/adhd/adhd-parent-support.php">/adhd-parent-support</a>
            <a href="/adhd/adhd-teacher-support.php">/adhd-teacher-support</a>
            <a href="/adhd/adhd-classroom-accommodations.php">/adhd-classroom-accommodations</a>
            <a href="/adhd/adhd-workplace-accommodations.php">/adhd-workplace-accommodations</a>
            <a href="/adhd/adhd-time-management.php">/adhd-time-management</a>
            <a href="/adhd/adhd-study-skills.php">/adhd-study-skills</a>
            <a href="/adhd/adhd-organization-skills.php">/adhd-organization-skills</a>
            <a href="/adhd/adhd-and-school.php">/adhd-and-school</a>
            <a href="/adhd/adhd-and-college.php">/adhd-and-college</a>
          </div>
        </div>

        <div class="cluster">
          <h2>Learning Disabilities Cluster <span>(26 pages)</span></h2>
          <div class="url-grid">
            <a href="/learning-disabilities/specific-learning-disability.php">/specific-learning-disability</a>
            <a href="/learning-disabilities/learning-disabilities.php">/learning-disabilities</a>
            <a href="/learning-disabilities/dyslexia.php">/dyslexia</a>
            <a href="/learning-disabilities/dysgraphia.php">/dysgraphia</a>
            <a href="/learning-disabilities/dyscalculia.php">/dyscalculia</a>
            <a href="/learning-disabilities/reading-disorder.php">/reading-disorder</a>
            <a href="/learning-disabilities/writing-disorder.php">/writing-disorder</a>
            <a href="/learning-disabilities/math-learning-disorder.php">/math-learning-disorder</a>
            <a href="/learning-disabilities/learning-difficulties.php">/learning-difficulties</a>
            <a href="/learning-disabilities/school-performance-problems.php">/school-performance-problems</a>
            <a href="/learning-disabilities/learning-disability-assessment.php">/learning-disability-assessment</a>
            <a href="/learning-disabilities/psychoeducational-assessment.php">/psychoeducational-assessment</a>
            <a href="/learning-disabilities/school-readiness-assessment.php">/school-readiness-assessment</a>
            <a href="/learning-disabilities/wisc-v-testing.php">/wisc-v-testing</a>
            <a href="/learning-disabilities/academic-intervention.php">/academic-intervention</a>
            <a href="/learning-disabilities/special-education-support.php">/special-education-support</a>
            <a href="/learning-disabilities/inclusive-education.php">/inclusive-education</a>
            <a href="/learning-disabilities/iep-support.php">/iep-support</a>
            <a href="/learning-disabilities/school-accommodations.php">/school-accommodations</a>
            <a href="/learning-disabilities/exam-accommodations.php">/exam-accommodations</a>
            <a href="/learning-disabilities/learning-disability-support.php">/learning-disability-support</a>
            <a href="/learning-disabilities/dyslexia-therapy.php">/dyslexia-therapy</a>
            <a href="/learning-disabilities/reading-intervention.php">/reading-intervention</a>
            <a href="/learning-disabilities/writing-intervention.php">/writing-intervention</a>
            <a href="/learning-disabilities/study-skills-training.php">/study-skills-training</a>
            <a href="/learning-disabilities/executive-function-training.php">/executive-function-training</a>
          </div>
        </div>

        <div class="cluster">
          <h2>Speech & Communication Cluster <span>(17 pages)</span></h2>
          <div class="url-grid">
            <a href="/speech-therapy/speech-therapy.php">/speech-therapy</a>
            <a href="/speech-therapy/speech-delay.php">/speech-delay</a>
            <a href="/speech-therapy/language-delay.php">/language-delay</a>
            <a href="/speech-therapy/expressive-language-disorder.php">/expressive-language-disorder</a>
            <a href="/speech-therapy/receptive-language-disorder.php">/receptive-language-disorder</a>
            <a href="/speech-therapy/speech-sound-disorders.php">/speech-sound-disorders</a>
            <a href="/speech-therapy/articulation-therapy.php">/articulation-therapy</a>
            <a href="/speech-therapy/stuttering-therapy.php">/stuttering-therapy</a>
            <a href="/speech-therapy/pragmatic-language-disorder.php">/pragmatic-language-disorder</a>
            <a href="/speech-therapy/communication-skills-training.php">/communication-skills-training</a>
            <a href="/speech-therapy/speech-assessment.php">/speech-assessment</a>
            <a href="/speech-therapy/language-assessment.php">/language-assessment</a>
            <a href="/speech-therapy/speech-therapy-for-autism.php">/speech-therapy-for-autism</a>
            <a href="/speech-therapy/speech-therapy-for-adhd.php">/speech-therapy-for-adhd</a>
            <a href="/speech-therapy/speech-therapy-for-children.php">/speech-therapy-for-children</a>
            <a href="/speech-therapy/speech-therapy-for-adults.php">/speech-therapy-for-adults</a>
            <a href="/speech-therapy/social-communication-disorder.php">/social-communication-disorder</a>
          </div>
        </div>

        <div class="cluster">
          <h2>Occupational Therapy Cluster <span>(16 pages)</span></h2>
          <div class="url-grid">
            <a href="/occupational-therapy/occupational-therapy.php">/occupational-therapy</a>
            <a href="/occupational-therapy/sensory-processing-disorder.php">/sensory-processing-disorder</a>
            <a href="/occupational-therapy/sensory-integration-therapy.php">/sensory-integration-therapy</a>
            <a href="/occupational-therapy/fine-motor-skills.php">/fine-motor-skills</a>
            <a href="/occupational-therapy/gross-motor-skills.php">/gross-motor-skills</a>
            <a href="/occupational-therapy/handwriting-difficulties.php">/handwriting-difficulties</a>
            <a href="/occupational-therapy/daily-living-skills.php">/daily-living-skills</a>
            <a href="/occupational-therapy/self-care-training.php">/self-care-training</a>
            <a href="/occupational-therapy/motor-planning.php">/motor-planning</a>
            <a href="/occupational-therapy/sensory-seeking-behaviour.php">/sensory-seeking-behaviour</a>
            <a href="/occupational-therapy/sensory-avoidance.php">/sensory-avoidance</a>
            <a href="/occupational-therapy/sensory-regulation.php">/sensory-regulation</a>
            <a href="/occupational-therapy/occupational-therapy-assessment.php">/occupational-therapy-assessment</a>
            <a href="/occupational-therapy/ot-for-autism.php">/ot-for-autism</a>
            <a href="/occupational-therapy/ot-for-adhd.php">/ot-for-adhd</a>
            <a href="/occupational-therapy/ot-for-learning-disabilities.php">/ot-for-learning-disabilities</a>
          </div>
        </div>

        <div class="cluster">
          <h2>Child Psychology Cluster <span>(20 pages)</span></h2>
          <div class="url-grid">
            <a href="/child-psychology/child-psychologist.php">/child-psychologist</a>
            <a href="/child-psychology/child-counselling.php">/child-counselling</a>
            <a href="/child-psychology/child-anxiety.php">/child-anxiety</a>
            <a href="/child-psychology/child-depression.php">/child-depression</a>
            <a href="/child-psychology/child-stress.php">/child-stress</a>
            <a href="/child-psychology/child-behaviour-problems.php">/child-behaviour-problems</a>
            <a href="/child-psychology/temper-tantrums.php">/temper-tantrums</a>
            <a href="/child-psychology/emotional-regulation.php">/emotional-regulation</a>
            <a href="/child-psychology/anger-management-for-children.php">/anger-management-for-children</a>
            <a href="/child-psychology/social-skills-training.php">/social-skills-training</a>
            <a href="/child-psychology/peer-relationship-problems.php">/peer-relationship-problems</a>
            <a href="/child-psychology/bullying-support.php">/bullying-support</a>
            <a href="/child-psychology/school-refusal.php">/school-refusal</a>
            <a href="/child-psychology/academic-stress.php">/academic-stress</a>
            <a href="/child-psychology/low-self-esteem.php">/low-self-esteem</a>
            <a href="/child-psychology/confidence-building.php">/confidence-building</a>
            <a href="/child-psychology/grief-counselling-for-children.php">/grief-counselling-for-children</a>
            <a href="/child-psychology/trauma-support-for-children.php">/trauma-support-for-children</a>
            <a href="/child-psychology/play-therapy.php">/play-therapy</a>
            <a href="/child-psychology/expressive-arts-therapy.php">/expressive-arts-therapy</a>
          </div>
        </div>

<!-- LOCATIONS-SEOMAP:START (generated by generate-locations-nav.js — do not edit by hand) -->
        <div class="cluster">
          <h2>Locations &ndash; Delhi <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-delhi">/child-psychologist-in-delhi</a>
            <a href="/locations/child-counselling-in-delhi">/child-counselling-in-delhi</a>
            <a href="/locations/teen-counselling-in-delhi">/teen-counselling-in-delhi</a>
            <a href="/locations/adult-counselling-in-delhi">/adult-counselling-in-delhi</a>
            <a href="/locations/autism-assessment-in-delhi">/autism-assessment-in-delhi</a>
            <a href="/locations/autism-therapy-in-delhi">/autism-therapy-in-delhi</a>
            <a href="/locations/adhd-assessment-in-delhi">/adhd-assessment-in-delhi</a>
            <a href="/locations/learning-disability-assessment-in-delhi">/learning-disability-assessment-in-delhi</a>
            <a href="/locations/speech-therapy-in-delhi">/speech-therapy-in-delhi</a>
            <a href="/locations/occupational-therapy-in-delhi">/occupational-therapy-in-delhi</a>
            <a href="/locations/special-education-in-delhi">/special-education-in-delhi</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; South Delhi <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-south-delhi">/child-psychologist-in-south-delhi</a>
            <a href="/locations/child-counselling-in-south-delhi">/child-counselling-in-south-delhi</a>
            <a href="/locations/teen-counselling-in-south-delhi">/teen-counselling-in-south-delhi</a>
            <a href="/locations/adult-counselling-in-south-delhi">/adult-counselling-in-south-delhi</a>
            <a href="/locations/autism-assessment-in-south-delhi">/autism-assessment-in-south-delhi</a>
            <a href="/locations/autism-therapy-in-south-delhi">/autism-therapy-in-south-delhi</a>
            <a href="/locations/adhd-assessment-in-south-delhi">/adhd-assessment-in-south-delhi</a>
            <a href="/locations/learning-disability-assessment-in-south-delhi">/learning-disability-assessment-in-south-delhi</a>
            <a href="/locations/speech-therapy-in-south-delhi">/speech-therapy-in-south-delhi</a>
            <a href="/locations/occupational-therapy-in-south-delhi">/occupational-therapy-in-south-delhi</a>
            <a href="/locations/special-education-in-south-delhi">/special-education-in-south-delhi</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Saket <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-saket">/child-psychologist-in-saket</a>
            <a href="/locations/child-counselling-in-saket">/child-counselling-in-saket</a>
            <a href="/locations/teen-counselling-in-saket">/teen-counselling-in-saket</a>
            <a href="/locations/adult-counselling-in-saket">/adult-counselling-in-saket</a>
            <a href="/locations/autism-assessment-in-saket">/autism-assessment-in-saket</a>
            <a href="/locations/autism-therapy-in-saket">/autism-therapy-in-saket</a>
            <a href="/locations/adhd-assessment-in-saket">/adhd-assessment-in-saket</a>
            <a href="/locations/learning-disability-assessment-in-saket">/learning-disability-assessment-in-saket</a>
            <a href="/locations/speech-therapy-in-saket">/speech-therapy-in-saket</a>
            <a href="/locations/occupational-therapy-in-saket">/occupational-therapy-in-saket</a>
            <a href="/locations/special-education-in-saket">/special-education-in-saket</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Hauz Khas <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-hauz-khas">/child-psychologist-in-hauz-khas</a>
            <a href="/locations/child-counselling-in-hauz-khas">/child-counselling-in-hauz-khas</a>
            <a href="/locations/teen-counselling-in-hauz-khas">/teen-counselling-in-hauz-khas</a>
            <a href="/locations/adult-counselling-in-hauz-khas">/adult-counselling-in-hauz-khas</a>
            <a href="/locations/autism-assessment-in-hauz-khas">/autism-assessment-in-hauz-khas</a>
            <a href="/locations/autism-therapy-in-hauz-khas">/autism-therapy-in-hauz-khas</a>
            <a href="/locations/adhd-assessment-in-hauz-khas">/adhd-assessment-in-hauz-khas</a>
            <a href="/locations/learning-disability-assessment-in-hauz-khas">/learning-disability-assessment-in-hauz-khas</a>
            <a href="/locations/speech-therapy-in-hauz-khas">/speech-therapy-in-hauz-khas</a>
            <a href="/locations/occupational-therapy-in-hauz-khas">/occupational-therapy-in-hauz-khas</a>
            <a href="/locations/special-education-in-hauz-khas">/special-education-in-hauz-khas</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Green Park <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-green-park">/child-psychologist-in-green-park</a>
            <a href="/locations/child-counselling-in-green-park">/child-counselling-in-green-park</a>
            <a href="/locations/teen-counselling-in-green-park">/teen-counselling-in-green-park</a>
            <a href="/locations/adult-counselling-in-green-park">/adult-counselling-in-green-park</a>
            <a href="/locations/autism-assessment-in-green-park">/autism-assessment-in-green-park</a>
            <a href="/locations/autism-therapy-in-green-park">/autism-therapy-in-green-park</a>
            <a href="/locations/adhd-assessment-in-green-park">/adhd-assessment-in-green-park</a>
            <a href="/locations/learning-disability-assessment-in-green-park">/learning-disability-assessment-in-green-park</a>
            <a href="/locations/speech-therapy-in-green-park">/speech-therapy-in-green-park</a>
            <a href="/locations/occupational-therapy-in-green-park">/occupational-therapy-in-green-park</a>
            <a href="/locations/special-education-in-green-park">/special-education-in-green-park</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Greater Kailash <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-greater-kailash">/child-psychologist-in-greater-kailash</a>
            <a href="/locations/child-counselling-in-greater-kailash">/child-counselling-in-greater-kailash</a>
            <a href="/locations/teen-counselling-in-greater-kailash">/teen-counselling-in-greater-kailash</a>
            <a href="/locations/adult-counselling-in-greater-kailash">/adult-counselling-in-greater-kailash</a>
            <a href="/locations/autism-assessment-in-greater-kailash">/autism-assessment-in-greater-kailash</a>
            <a href="/locations/autism-therapy-in-greater-kailash">/autism-therapy-in-greater-kailash</a>
            <a href="/locations/adhd-assessment-in-greater-kailash">/adhd-assessment-in-greater-kailash</a>
            <a href="/locations/learning-disability-assessment-in-greater-kailash">/learning-disability-assessment-in-greater-kailash</a>
            <a href="/locations/speech-therapy-in-greater-kailash">/speech-therapy-in-greater-kailash</a>
            <a href="/locations/occupational-therapy-in-greater-kailash">/occupational-therapy-in-greater-kailash</a>
            <a href="/locations/special-education-in-greater-kailash">/special-education-in-greater-kailash</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Defence Colony <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-defence-colony">/child-psychologist-in-defence-colony</a>
            <a href="/locations/child-counselling-in-defence-colony">/child-counselling-in-defence-colony</a>
            <a href="/locations/teen-counselling-in-defence-colony">/teen-counselling-in-defence-colony</a>
            <a href="/locations/adult-counselling-in-defence-colony">/adult-counselling-in-defence-colony</a>
            <a href="/locations/autism-assessment-in-defence-colony">/autism-assessment-in-defence-colony</a>
            <a href="/locations/autism-therapy-in-defence-colony">/autism-therapy-in-defence-colony</a>
            <a href="/locations/adhd-assessment-in-defence-colony">/adhd-assessment-in-defence-colony</a>
            <a href="/locations/learning-disability-assessment-in-defence-colony">/learning-disability-assessment-in-defence-colony</a>
            <a href="/locations/speech-therapy-in-defence-colony">/speech-therapy-in-defence-colony</a>
            <a href="/locations/occupational-therapy-in-defence-colony">/occupational-therapy-in-defence-colony</a>
            <a href="/locations/special-education-in-defence-colony">/special-education-in-defence-colony</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Vasant Kunj <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-vasant-kunj">/child-psychologist-in-vasant-kunj</a>
            <a href="/locations/child-counselling-in-vasant-kunj">/child-counselling-in-vasant-kunj</a>
            <a href="/locations/teen-counselling-in-vasant-kunj">/teen-counselling-in-vasant-kunj</a>
            <a href="/locations/adult-counselling-in-vasant-kunj">/adult-counselling-in-vasant-kunj</a>
            <a href="/locations/autism-assessment-in-vasant-kunj">/autism-assessment-in-vasant-kunj</a>
            <a href="/locations/autism-therapy-in-vasant-kunj">/autism-therapy-in-vasant-kunj</a>
            <a href="/locations/adhd-assessment-in-vasant-kunj">/adhd-assessment-in-vasant-kunj</a>
            <a href="/locations/learning-disability-assessment-in-vasant-kunj">/learning-disability-assessment-in-vasant-kunj</a>
            <a href="/locations/speech-therapy-in-vasant-kunj">/speech-therapy-in-vasant-kunj</a>
            <a href="/locations/occupational-therapy-in-vasant-kunj">/occupational-therapy-in-vasant-kunj</a>
            <a href="/locations/special-education-in-vasant-kunj">/special-education-in-vasant-kunj</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Gurgaon <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-gurgaon">/child-psychologist-in-gurgaon</a>
            <a href="/locations/child-counselling-in-gurgaon">/child-counselling-in-gurgaon</a>
            <a href="/locations/teen-counselling-in-gurgaon">/teen-counselling-in-gurgaon</a>
            <a href="/locations/adult-counselling-in-gurgaon">/adult-counselling-in-gurgaon</a>
            <a href="/locations/autism-assessment-in-gurgaon">/autism-assessment-in-gurgaon</a>
            <a href="/locations/autism-therapy-in-gurgaon">/autism-therapy-in-gurgaon</a>
            <a href="/locations/adhd-assessment-in-gurgaon">/adhd-assessment-in-gurgaon</a>
            <a href="/locations/learning-disability-assessment-in-gurgaon">/learning-disability-assessment-in-gurgaon</a>
            <a href="/locations/speech-therapy-in-gurgaon">/speech-therapy-in-gurgaon</a>
            <a href="/locations/occupational-therapy-in-gurgaon">/occupational-therapy-in-gurgaon</a>
            <a href="/locations/special-education-in-gurgaon">/special-education-in-gurgaon</a>
          </div>
        </div>
        <div class="cluster">
          <h2>Locations &ndash; Noida <span>(11 pages)</span></h2>
          <div class="url-grid">
            <a href="/locations">/locations</a>
            <a href="/locations/child-psychologist-in-noida">/child-psychologist-in-noida</a>
            <a href="/locations/child-counselling-in-noida">/child-counselling-in-noida</a>
            <a href="/locations/teen-counselling-in-noida">/teen-counselling-in-noida</a>
            <a href="/locations/adult-counselling-in-noida">/adult-counselling-in-noida</a>
            <a href="/locations/autism-assessment-in-noida">/autism-assessment-in-noida</a>
            <a href="/locations/autism-therapy-in-noida">/autism-therapy-in-noida</a>
            <a href="/locations/adhd-assessment-in-noida">/adhd-assessment-in-noida</a>
            <a href="/locations/learning-disability-assessment-in-noida">/learning-disability-assessment-in-noida</a>
            <a href="/locations/speech-therapy-in-noida">/speech-therapy-in-noida</a>
            <a href="/locations/occupational-therapy-in-noida">/occupational-therapy-in-noida</a>
            <a href="/locations/special-education-in-noida">/special-education-in-noida</a>
          </div>
        </div>
<!-- LOCATIONS-SEOMAP:END -->

      </div>
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    <script src="/assets/interactive.js"></script>
  </body>
</html>
