<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="Read the eMbrace terms &amp; conditions governing use of our mental health services, platform, bookings &amp; therapy sessions."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/terms_and_conditions" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/terms_and_conditions" property="og:url" />
    <meta content="Terms &amp; Conditions | eMbrace Lives – SMD Wellness" property="og:title" />
    <meta
      content="Read the eMbrace terms &amp; conditions governing use of our mental health services, platform, bookings &amp; therapy sessions."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="Terms &amp; Conditions | eMbrace Lives – SMD Wellness" name="twitter:title" />
    <meta
      content="Read the eMbrace terms &amp; conditions governing use of our mental health services, platform, bookings &amp; therapy sessions."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>Terms &amp; Conditions | eMbrace Lives – SMD Wellness</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  
  
  
  
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "WebPage",
        "@id": "https://embracelives.com/terms_and_conditions#webpage",
        "url": "https://embracelives.com/terms_and_conditions",
        "name": "Terms & Conditions | eMbrace Lives – SMD Wellness",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Read the eMbrace terms & conditions governing use of our mental health services, platform, bookings & therapy sessions."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  </head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div
        class="md:min-h-fit overflow-hidden flex flex-col items-center px-4 md:px-8 lg:px-16 xl:px-30 py-6 md:py-6 relative"
      >
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Terms &amp; Conditions</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >These terms and conditions (“Terms of Use” or “Terms of Service” or “Terms”) are a computer-generated
              electronic record published under Rule 3 of the Information Technology (Intermediary Guidelines and
              Digital Media Ethics Code) Rules, 2021 (as amended from time to time) read with Information Technology
              Act, 2000 (as amended from time to time) and does not require any physical or digital signatures. These
              Terms are legally binding and govern your access and use of our Services and Platform, owned and operated
              by SMD Wellness Private Limited, a company incorporated under the Companies Act, 2013, having its
              registered office at Shop No. 2, First floor, CSC Sector-C, Pocket-1, Vasant Kunj, Delhi, 110070 and
              represented by its Founder, Dr. Supriya Malik (“SMD Wellness” or “eMbrace”). eMbrace is the brand name
              owned by SMD Wellness Pvt Ltd.<br />Please read these Terms carefully before accessing or using the
              Platform and/or using our Services. By doing so, you agree to be bound by these Terms and our Privacy
              Policy (insert hyperlink). If you do not agree to be bound by them, you shall not access/use the Platform
              and our Services in any manner whatsoever. These Terms are in addition to and not in derogation of any
              other terms stipulated by SMD Wellness from time to time. In case of any conflict between the Terms and
              such other terms, these Terms shall prevail. Throughout the Terms, “we”, “us” and “our” shall refer to SMD
              Wellness and “you” and “your” shall refer to you, i.e., the User of the Platform. Both SMD Wellness and
              the User are collectively referred to as “Parties” and individually referred to as “Party” hereof.<br />Notwithstanding
              anything contained elsewhere, SMD Wellness reserves the right to modify, alter, amend, revise the Terms,
              update the Platform or its Services, at any time without prior notice, to improve your experience on the
              Platform and on account of changes in Applicable Law, if any. It is strongly recommended that you visit
              the Platform periodically to review the latest and updated version of the Terms. If you do not agree with
              any changes made by us, you may stop using the Platform and our Services. Your continued access or use of
              the Platform and/or use of our Services after such modifications/updation shall constitute your acceptance
              of the modifications/updation</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Definitions</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >For the purpose of the Terms, the following words and phrases shall have the meaning assigned to them
              hereinbelow:<br />“Account” shall mean a User’s registered account on the Platform for using the
              Services;<br />“Applicable Law” shall mean and include any law, statute, rule, regulation, order,
              circular, decree, directive, judgment, decision or other similar mandate of any applicable central,
              national, state or local governmental/regulatory authority having competent jurisdiction and force of law
              over, or applicable to you, SMD Wellness or the subject matter in question, as may be amended from time to
              time;<br />“Confidential Information” shall mean information which (a) is or can be considered to be of
              confidential nature, whether or not such information is expressly marked as confidential; (b) is obtained
              (without limitation) in graphic, written, electronic or machine-readable form or any media; and includes
              (c) Intellectual Property;<br />“Intellectual Property” shall mean and include (a) all patents,
              trademarks, copyrights and works of authorship, designs, domain names, business processes, utility models,
              whether registered or unregistered, which are owned and/or developed by either Party; (b) all processes,
              inventions, ideas, computer programs, codes, algorithms, discoveries, trade secrets, databases, know-how,
              User lists, User reviews and testimonials, recording, whether audio or visual or both, or any other form
              of interaction between the SMD Wellness and the User, creations or improvements or any research effort
              relating to any of the above, whether registrable or not;<br />“Platform” shall mean, including but not
              limited to, eMbrace website accessible at
              <a href="https://www.embracelives.com/">https://www.embracelives.com/</a> , any other linked web pages,
              mobile application (Android and iOS), mobile site services, API keys, features and content hosted on the
              Platform.<br />“Services” shall mean and include without limitation, online therapy, counselling, online
              self-care guides/modules, assessments related to neurodevelopmental and psychiatric disorders, including
              but not limited to, autism spectrum disorder, hyperactivity disorder, cognitive functioning, specific
              learning disability, social communication difficulties, executive functioning difficulties, personality
              disorders, mood disorders, anxiety disorders and phobias, obsessive compulsive disorder, gender and
              sexuality and post-traumatic stress disorder.<br />“Users” shall mean and include individuals, body
              corporate, partnership, limited liability partnership, etc., who are visiting, browsing, accessing and/or
              using the Platform and/or Services.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Acceptance</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >By browsing, accessing, signing-up, registering and/or accepting or using the Platform or ordering,
              purchasing, subscribing to our Services in any manner whatsoever, you acknowledge that you have read these
              Terms and agree to be bound by them. You also acknowledge that you have read our Privacy Policy and agree
              to be bound by it as well. By accessing or using the Platform and/or Services, you represent that you have
              provided us with valid credentials which may be used to verify your identity. We reserve the right to
              restrict, suspend, or terminate your access to the Platform and/or Services, at any time without prior
              notice, if we believe that you are in breach of the Terms. For the security of your account and to enhance
              your overall experience on the Platform, we may use certain technologies (cookies) to monitor your
              activities on the Platform. SMD Wellness may contact you for information and other enquiries through
              email, telephone and/or SMS. You agree to receive promotional materials and/or special offers on our
              Services. These promotional materials and/or special offers will be consent based and you will have the
              option to unsubscribe.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">User Representations</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >By accessing or using the Platform, you represent and warrant that:<br />(a) you are 18 years or above
              and competent to enter into legally binding contracts as per Applicable Law; provided however, if you are
              between 15-18 years, you may access or use the Platform and Services upon consent of your parent or legal
              guardian;<br />(b) the personal information submitted by you are the time of creation of an Account or
              availing our Services, is true, accurate, updated and complete;<br />(c) you will maintain the accuracy of
              your personal information and promptly update it, as required;<br />(d) you are using a secure computer
              resource and internet connection which is free from viruses and malware;<br />(e) you will not use the
              Platform and Services for any illegal or unauthorized purpose;<br />(f) your use of the Platform and
              Services shall not violate any Applicable Law.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">General Disclaimers</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >(a) SMD Wellness aims to make mental healthcare accessible to all. However, we do not provide any
              medical, psychiatric or other treatment or care for severe mental or other illnesses.<br />(b) The
              Platform is not a suicide prevention or crisis intervention helpline. In case you have suicidal thoughts,
              are victim of physical or sexual abuse or at risk of harming self or others, please seek immediate medical
              support using these Helpline numbers.<br />(c) While our Services are provided by qualified and competent
              psychologists, we do not claim to provide any kind of medical advice or diagnosis of any medical,
              psychiatric or other condition.<br />(d) The Users agree that SMD Wellness shall not be liable for the
              outcome of any interaction between them and the psychologists. If the User accepts any psychologist’s
              advice during therapy sessions, it shall be at her sole risk and responsibility.<br />(e) SMD Wellness is
              not responsible if any content, posts or information made available on the Platform is not accurate,
              complete or updated. The content, posts or information is provided for general information and educational
              purposes only and should not be relied upon or used as the sole basis for making decisions without
              consulting primary, more accurate, more complete or more timely sources of information. Any reliance on
              the content, posts or information on the Platform is at the User’s own risk. We reserve the right to
              modify the contents of this site at any time, but we have no obligation to update any information on our
              site. You agree that it is your responsibility to monitor changes to our site</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Platform Registartions</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >The Users can access and use the Services and features of the Platform after creating an account.
              Registration can either be done through existing Google account or by providing personal data such as
              name, e-mail ID, mobile number, date of birth and password. The User shall be solely liable for
              maintaining confidentiality of the password.<br />Once registered on the Platform, the Users can login
              through their registered email ID and password. It is expressly noted that SMD Wellness reserves the right
              to alter, reclaim, or modify any chosen username at its sole discretion, contingent upon determination of
              the username’s unsuitability, obscenity, or objectionability in accordance Applicable Law. Please note
              that children below the age of 15 years are prohibited from accessing and using the Platform and our
              Services.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Booking &amp; Cancellation of Services</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >Users can book therapy sessions using their registered Account. Users can opt for different therapy
              packages depending on their needs and requirements. All payments are to be made in advance. Every therapy
              session is time bound and can last up to 50 minutes depending on the User’s needs and requirements. In
              case the duration of a session is extended, User shall be liable to pay additional fee for the extended
              duration. Please note that the fee paid needs to be used within 1 month of payment done. In case of any
              emergencies or other unforeseen reasons, you can cancel an appointment by giving a 12-hour prior written
              notice through email at info@embracelives.com. If the session cannot be scheduled or continued due to a
              technical glitch, we may reschedule the session to a later date mutually agreeable to you and the
              psychologist. We do not allow refunds for therapy sessions.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Optional Tools</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >We may provide you access to third-party tools on an “as is” and “as available” basis without any
              warranties, representations or conditions of any kind and without any endorsement. You agree that SMD
              Wellness does not monitor these third-party tools and we do not have control over them. We shall have no
              liability whatsoever arising from or relating to your use of the optional third-party tools. Any use by
              you of these tools offered through the Platform, is entirely at your own risk and discretion and you will
              ensure that you are familiar with and approve of the terms on which tools are provided by the relevant
              third-party provider(s). We may also, in the future, offer new services and/or features through the
              Platform (including, the release of new tools and resources). Such new features and/or services shall also
              be subject to these Terms.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Third-Party Sites</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >The Platform may include links or references to third-party websites or services solely for User’s
              convenience (“Reference Sites”). SMD Wellness has no control over the Reference Sites and does not endorse
              them or the information, materials, products, or services contained on or accessible through them.
              Correspondence or business dealings between Users and the concerned Reference Sites are solely between
              such User and the concerned Reference Site. Access and use of Reference Sites, including the information,
              materials, products, and services on or available through Reference Sites is solely at the concerned
              User’s own risk. You acknowledge and agree that SMD Wellness shall not be liable, directly, or indirectly,
              for any loss or damage caused or alleged to be caused by your use of or reliance on any materials,
              products, and services on or available through Reference Sites.<br />It is also clarified that SMD
              Wellness shall have no liability with respect to any acts, omissions, errors, representations, warranties,
              breaches, or negligence of the Reference Sites or for any personal injuries, death, property damage, or
              other damages or expenses resulting from your interactions with the Reference Sites.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Privacy Policy</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >All information collected from a User pursuant to provision of Services under these Terms is subject to
              our Privacy Policy. By using our Platform and/or Services, you hereby consent to the use of your
              information as outlined in our Privacy Policy.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Errors, Inaccuracies &amp; Warranties</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >Occasionally, there may be information on our Platform that contains typographical errors, inaccuracies
              or omissions that may relate to description of Services, pricing, promotions, offers and availability. We
              reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or
              cancel orders if any information on the Platform is inaccurate at any time without prior notice (including
              after you have subscribed to any Service).</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Prohibited Uses</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >In addition to any other prohibitions as set forth in the Terms, you are prohibited from using the
              Platform or its content:<br />(a) for any unlawful purpose;<br />(b) to solicit others to perform or
              participate in any unlawful acts;<br />(c) to violate Applicable Law;<br />(d) to infringe upon or violate
              our Intellectual Property rights or the intellectual property rights of others;<br />(e) to harass, abuse,
              insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation,
              religion, ethnicity, race, age, national origin, or disability;<br />(f) to submit false or misleading
              information;<br />(g) to upload or transmit viruses or any other type of malicious code that will or may
              be used in any way that will affect the functionality or operation of the Platform;<br />(h) to collect or
              track personal information of others;<br />(i) to spam, phish, pharm, pretext, spider, crawl, or
              scrape;<br />(j) for any obscene or immoral purpose;<br />(k) to interfere with or circumvent the security
              features of the Platform.<br />We reserve the right to immediately terminate your access and use of the
              Platform in case it is found that you are accessing the Platform for any of the aforementioned prohibited
              uses.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Disclaimer of Warranties</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >We do not guarantee, represent or warrant that your use of our Platform will be uninterrupted, timely,
              secure or error-free. We do not warrant that the results that may be obtained from the use of the Services
              will be accurate or reliable. You agree that from time to time we may remove any Service for indefinite
              periods of time or cancel any Service at any time, without prior notice to you.<br />You expressly agree
              that your use of, or inability to use the Platform is at your sole risk. The Platform and all Services
              delivered to you through it are provided on an “as is” and “as available” basis use, without
              representations, warranties or conditions of any kind, either express or implied, including all implied
              warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose,
              durability, title, and non-infringement.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Confidentiality &amp; Intellectual Property</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >Either Party shall keep the Confidential Information of the other Party strictly confidential.
              Notwithstanding anything contained elsewhere, SMD Wellness reserves the right to disclose User’s
              Confidential Information to its employees, agents, representatives, psychologists, and any other
              third-party service provider, if they have “need to know” such Confidential Information in order to
              provide the Services. We may also disclose your Confidential Information to your family or relevant
              government authorities, if (a) you show symptoms of self-harm or harm to others; (b) there is reasonable
              suspicion of physical or sexual abuse; (c) such information is sought under Applicable Law.<br />The
              Platform is owned and operated by SMD Wellness and third-party licensors, if any. The visual interfaces,
              graphics, design, compilation, information, computer code (including source code and object code),
              software, Services, and all other elements of the Platform provided by SMD Wellness to the User
              (“Materials”) are protected by Applicable Law.<br />All Materials and SMD Wellness’ Intellectual Property
              are the property of SMD Wellness and/or third-party licensors or suppliers as applicable. You agree not to
              reproduce, duplicate, copy, sell, resell or exploit any portion of the Platform, use of the Platform, or
              access to the Platform or any contact through which any Service is provided, without express written
              permission from us. For removal of doubts, it is clarified that unlimited or wholesale reproduction,
              copying of the Platform’s content for commercial or non-commercial purposes, and unwarranted modification
              of data and information within the content of Platform are prohibited.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Limitation of Liability and Indemnity</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >SMD Wellness shall not be liable for any injury, loss, claim, or any direct, indirect, incidental,
              punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost
              revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract,
              tort (including negligence), strict liability or otherwise, arising from the User’s access and/or use of
              the Platform and/or Services.<br />The User agrees to indemnify, defend and hold harmless SMD Wellness,
              its directors, officers, employees, affiliates, agents and representatives from all claims, actions,
              losses, damages, demands, costs, fees (including reasonable attorneys’ fees), arising out of or in
              connection with the User’s breach of the Terms, or violation of the Applicable Law or intellectual
              property rights of any third-party.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Termination</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >SMD Wellness reserves the right to terminate/suspend the Terms or User’s access to the Platform and
              Services without prior notice and without any liability to the User or any third-party. In the event the
              User wants to terminate the Terms, it can email at info@embracelives.com with a prior notice of 24 hours.
              Any suspension/termination of the User’s access to the Platform and Services shall be without prejudice to
              SMD Wellness’ right to exercise any other remedy available to it under the Applicable Law. The User will
              continue to remain liable for all amounts due up to and including the date of termination</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Governing Law &amp; Dispute Resolution</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >The Terms shall be governed by and construed in accordance with the laws of India, without regard to its
              conflict of law provisions. Any dispute arising out of or in connection with the Terms shall be subject to
              exclusive jurisdiction of competent courts at New Delhi.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Miscellaneous</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >(i) SEVERABILITY<br />If any provision of the Terms is held to be unlawful, void, invalid or otherwise
              unenforceable, then such provision shall be limited or eliminated from the Terms to the minimum extent
              required under Applicable Law, and the remaining provisions shall remain valid and enforceable.<br />(ii)
              ASSIGNMENT<br />The Terms and any rights and obligations hereunder, shall not be assignable by the User to
              any third-party, but may be assigned by SMD Wellness without any restriction.<br />(iii) ENTIRE
              AGREEMENT<br />The Terms, Privacy Policy and any disclaimers on the Platform constitute the entire
              agreement and understanding between the Parties and supersede any prior or contemporaneous agreements,
              communications and proposals, whether oral or written, on the subject matter hereof.<br />(iv) NOTICE<br />SMD
              Wellness may provide Users with notices and communications through registered e-mail, regular mail, or
              posts on the Platform or by any other reasonable means. Except as otherwise set forth herein, notice to
              SMD Wellness must be sent by courier or registered post at Shop No. 2, First floor, CSC Sector-C,
              Pocket-1, Vasant Kunj, Delhi, 110070.<br />(v) WAIVER<br />The failure of SMD Wellness to exercise or
              enforce any right or provision of the Terms will not constitute a waiver of such right or provision. Any
              waiver of any provision of the Terms, express or implied, shall be effective only if in writing and signed
              by SMD Wellness.<br />(vi) RELATIONSHIP BETWEEN THE PARTIES<br />The Terms are not intended to create a
              joint venture, employment, partnership, agency, or formal business organization of any kind between the
              Parties. SMD Wellness and the User are independent contractors for all purposes and at all times and their
              relationship is on a principal-to-principal basis. Neither Party shall act as or hold itself out as an
              agent or representative of the other Party.<br />(vii) QUERIES<br />Any queries about the Terms should be
              sent to us at
              <a class="underline text-[var(--blue-fig)]" href="mailto:info@embracelives.com"
                >info@embracelives.com</a
              ></span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Cancellation and Refund Policy</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              >We understand that sometimes plans change and you may need to cancel a scheduled therapy session. To do
              so, please contact us at least 24 hours in advance of your appointment to reschedule the booked
              appointment. Please note cancellations made with less than 24 hours’ notice will be taken as No-Show and
              charged in full.<br />We DO NOT offer refunds for sessions booked unless exceptional circumstances.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Disclaimer</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              ><a class="underline text-[var(--blue-fig)]" href="http://www.embracelives.com">www.embracelives.com</a> 
              is not equipped to handle medical or psychological emergencies. Our services are not intended for crisis
              situations, which may include, but are not limited to, thoughts of self-harm, suicidal ideation, or
              symptoms of severe clinical disorders such as schizophrenia and other psychotic conditions. In such
              instances, immediate in-person medical attention is the most suitable form of assistance.<br />If you find
              yourself facing any of these challenges, or if you are contemplating suicide or feel that you pose a risk
              to yourself or others, we implore you to seek immediate help. Please call at the mentioned helplines
              numbers or proceed to the nearest hospital or emergency room to connect with medical professionals like
              psychiatrists, social workers, counselors, or therapists face-to-face. In the event of any medical or
              psychological health emergency, it is also advisable to involve a trusted family member or friend who can
              provide support during this critical time. Remember, your safety is paramount, and professional in-person
              support is essential in an emergency.</span
            >
          </div>
        </div>
        <div class="mb-8 w-full max-w-4xl flex flex-col items-center">
          <h2 class="text-3xl font-bold mb-10 text-center">Emergency Helplines</h2>
          <div class="text-sm text-[var(--text-gray)] leading-relaxed mb-15 font-medium text-justify">
            <span
              ><span class="font-semibold text-[var(--blue-fig)]">Sangath, 01141198666</span><br /><span
                class="underline"
                ><a href="https://outlive.in/get-help-now" target="_blank">https://outlive.in/get-help-now</a></span
              >
              - Sangath Well-being Center- Sangath’s tele-counselling services offer free phone-based counselling for
              frontline workers and young people in need of psychological support. You can call or Whatsapp the number
              to be connected to a trained counsellor who are proficient in Hindi, English, Marathi, Tamil and Konkani.
              https://sangath.in/tele-counselling/ 10AM-6PM, DAILY<br /><br /><span
                class="font-semibold text-[var(--blue-fig)]"
                >iCall 9372048501, 022-25521111</span
              ><br /><span class="underline"><a href="mailto:ICALL@TISS.EDU">ICALL@TISS.EDU</a></span> - iCall is a
              service from TISS, run by trained mental health professionals. iCALL provides emotional support,
              information and referral services to individuals in psycho-social distress, across the lifespan and across
              different gender and sexual identities.
              <a class="underline" href="https://icallhelpline.org/" target="_blank">http://icallhelpline.org/ </a>
              MONDAY TO SATURDAY, 8 AM - 10 PM<br /><br /><span class="font-semibold text-[var(--blue-fig)]"
                >National Helpline (NIMHANS), 080 46110007</span
              ><br />NIMHANS- This is a helpline for anyone experiencing mental health distress during the COVID 19
              crisis by National Institute of Mental Health &amp; Neuro Sciences Bengaluru.</span
            >
          </div>
        </div>
      </div>
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  </body>
</html>
