<!doctype html>
<html lang="en-IN">
  <head>
    <meta charset="utf-8" />
    
    <link href="/Favicon.png" rel="icon" type="image/svg+xml" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta
      content="Mental health services for universities — student counselling, faculty training, internship programs &amp; campus well-being initiatives with eMbrace."
      name="description"
    />
    <meta content="index, follow" name="robots" />
    <link href="https://embracelives.com/university" rel="canonical" />
    <!-- Open Graph -->
    <meta content="website" property="og:type" />
    <meta content="https://embracelives.com/university" property="og:url" />
    <meta content="University Counselling &amp; Campus Mental Health | eMbrace Lives" property="og:title" />
    <meta
      content="Mental health services for universities — student counselling, faculty training, internship programs &amp; campus well-being initiatives with eMbrace."
      property="og:description"
    />
    <meta content="https://embracelives.com/og-image.png" property="og:image" />
    <meta content="1200" property="og:image:width" />
    <meta content="630" property="og:image:height" />
    <meta content="eMbrace Lives" property="og:site_name" />
    <meta content="en_IN" property="og:locale" />
    <!-- Twitter Card -->
    <meta content="summary_large_image" name="twitter:card" />
    <meta content="University Counselling &amp; Campus Mental Health | eMbrace Lives" name="twitter:title" />
    <meta
      content="Mental health services for universities — student counselling, faculty training, internship programs &amp; campus well-being initiatives with eMbrace."
      name="twitter:description"
    />
    <meta content="https://embracelives.com/og-image.png" name="twitter:image" />
    <!-- JSON-LD Structured Data -->
<title>University Counselling &amp; Campus Mental Health | eMbrace Lives</title>
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" />
    <link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet" />

    <link href="/assets/index-B-kGA3UA.css" rel="stylesheet" />
    <style></style>
  <!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "ImageObject",
        "@id": "https://embracelives.com/#logo",
        "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
        "caption": "eMbrace"
      },
      {
        "@type": [
          "MedicalBusiness",
          "MedicalOrganization"
        ],
        "@id": "https://embracelives.com/#organization",
        "name": "eMbrace",
        "alternateName": "eMbrace Lives",
        "legalName": "eMbrace, a unit of SMD Wellness",
        "url": "https://embracelives.com/",
        "logo": {
          "@id": "https://embracelives.com/#logo"
        },
        "image": {
          "@id": "https://embracelives.com/#logo"
        },
        "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
        "telephone": "+91-9971576800",
        "email": "info@embracelives.com",
        "priceRange": "$$",
        "currenciesAccepted": "INR",
        "areaServed": [
          {
            "@type": "AdministrativeArea",
            "name": "Delhi NCR"
          },
          {
            "@type": "Place",
            "name": "Delhi"
          },
          {
            "@type": "Place",
            "name": "South Delhi"
          },
          {
            "@type": "Place",
            "name": "Saket"
          },
          {
            "@type": "Place",
            "name": "Hauz Khas"
          },
          {
            "@type": "Place",
            "name": "Green Park"
          },
          {
            "@type": "Place",
            "name": "Greater Kailash"
          },
          {
            "@type": "Place",
            "name": "Defence Colony"
          },
          {
            "@type": "Place",
            "name": "Vasant Kunj"
          },
          {
            "@type": "Place",
            "name": "Gurgaon"
          },
          {
            "@type": "Place",
            "name": "Noida"
          }
        ],
        "medicalSpecialty": [
          "Psychiatric",
          "Pediatric"
        ],
        "availableService": [
          {
            "@type": "MedicalTherapy",
            "name": "Child Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Clinical Psychology"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Autism Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "ADHD Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Learning Disability Assessment"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Speech and Language Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Occupational Therapy"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Special Education"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Teen Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Adult Counselling"
          },
          {
            "@type": "MedicalTherapy",
            "name": "Couples Therapy"
          }
        ],
        "address": {
          "@type": "PostalAddress",
          "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
          "addressLocality": "New Delhi",
          "addressRegion": "Delhi",
          "postalCode": "110070",
          "addressCountry": "IN"
        },
        "location": [
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#vasant-kunj",
            "name": "eMbrace — Vasant Kunj Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110070",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#gurugram",
            "name": "eMbrace — Gurugram Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
              "addressLocality": "Gurugram",
              "addressRegion": "Haryana",
              "postalCode": "122002",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          },
          {
            "@type": "MedicalClinic",
            "@id": "https://embracelives.com/contact-us#malviya-nagar",
            "name": "eMbrace — Malviya Nagar Centre",
            "parentOrganization": {
              "@id": "https://embracelives.com/#organization"
            },
            "telephone": "+91-9971576800",
            "email": "info@embracelives.com",
            "url": "https://embracelives.com/contact-us",
            "address": {
              "@type": "PostalAddress",
              "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
              "addressLocality": "New Delhi",
              "addressRegion": "Delhi",
              "postalCode": "110017",
              "addressCountry": "IN"
            },
            "openingHoursSpecification": [
              {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday"
                ],
                "opens": "10:00",
                "closes": "18:00"
              }
            ]
          }
        ],
        "openingHoursSpecification": [
          {
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": [
              "Monday",
              "Tuesday",
              "Wednesday",
              "Thursday",
              "Friday",
              "Saturday"
            ],
            "opens": "10:00",
            "closes": "18:00"
          }
        ],
        "sameAs": [
          "https://www.linkedin.com/company/embracelives/",
          "https://www.instagram.com/embracelives/",
          "https://www.facebook.com/embracelives22/"
        ]
      },
      {
        "@type": "WebSite",
        "@id": "https://embracelives.com/#website",
        "url": "https://embracelives.com/",
        "name": "eMbrace",
        "publisher": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN"
      },
      {
        "@type": "WebPage",
        "@id": "https://embracelives.com/university#webpage",
        "url": "https://embracelives.com/university",
        "name": "University Counselling & Campus Mental Health | eMbrace Lives",
        "isPartOf": {
          "@id": "https://embracelives.com/#website"
        },
        "about": {
          "@id": "https://embracelives.com/#organization"
        },
        "inLanguage": "en-IN",
        "description": "Mental health services for universities — student counselling, faculty training, internship programs & campus well-being initiatives with eMbrace."
      }
    ]
  }
  </script>
  <!-- SCHEMA:END -->
  <link href="/assets/lead-magnets.css" rel="stylesheet"/>
</head>
  <body>
    <div id="root">
      <?php include __DIR__ . '/components/header.php'; ?>
      <div
        class="md:min-h-[calc(100vh-4.4rem)] overflow-hidden flex flex-col items-center justify-center bg-gradient-to-b from-[#FFBDBD69] to-[#FFFFFF] px-4 md:px-8 lg:px-16 xl:px-30 py-6 relative"
      >
        <div class="bg-[#FFCC008A] w-14 h-14 rounded-full absolute bottom-4 -right-7 hidden md:block"></div>
        <div class="flex flex-col items-center justify-center">
          <h1 class="md:text-3xl text-lg font-bold text-center">eMbrace for Universities</h1>
          <p class="font-semibold text-sm md:text-lg text-[var(--text-gray)] italic text-center">
            Supporting Mentally Resilient, Career-Ready Campuses
          </p>
        </div>
        <div class="relative w-full flex flex-col items-center justify-center 2xl:mt-30 md:mt-14 -mt-6">
          <div class="flex items-center justify-center w-full gap-2 md:gap-6 relative h-56 md:h-60">
            <img
              alt="carousel-img-0"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-30 md:scale-95 scale-170 -translate-x-1/2 -translate-y-1/2 shadow-2xl"
              src="/assets/Hero1-C-qSiXdK.png"
              style="pointer-events: auto; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-1"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-20 md:scale-75 scale-150 -translate-x-1/2 -translate-y-1/2 -translate-x-[10%] md:translate-x-[0%]"
              src="/assets/Hero2-BRdQKI21.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-2"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-10 md:scale-50 scale-100 -translate-x-1/2 -translate-y-1/2 translate-x-[30%]"
              src="/assets/Hero3-H9DUJDHD.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-3"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-10 md:scale-50 scale-100 -translate-x-1/2 -translate-y-1/2 -translate-x-[130%]"
              src="/assets/Hero4-edEK0Oiq.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            /><img
              alt="carousel-img-4"
              class="rounded-xl object-cover w-[40%] absolute left-1/2 top-1/2 transition-all duration-700 ease-in-out z-20 md:scale-75 scale-150 -translate-x-1/2 -translate-y-1/2 -translate-x-[90%] md:-translate-x-[100%]"
              src="/assets/Hero5-BBP1R88F.png"
              style="pointer-events: none; transition: 0.7s cubic-bezier(0.4, 0, 0.2, 1)"
            />
          </div>
          <div class="flex items-center justify-center 2xl:mt-40 md:mt-14 -mt-5 gap-4 relative z-20">
            <button aria-label="Previous" class="cursor-pointer">
              <img
                alt="Previous"
                class="w-6 h-6"
                src="data:image/svg+xml,%3csvg%20width='50'%20height='50'%20viewBox='0%200%2050%2050'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20fill-rule='evenodd'%20clip-rule='evenodd'%20d='M16.917%2021.8752H43.7475V28.1252H16.917L27.2073%2038.4155L22.7878%2042.8349L4.95312%2025.0002L22.7878%207.16553L27.2073%2011.5849L16.917%2021.8752Z'%20fill='%23999999'/%3e%3c/svg%3e"
              />
            </button>
            <div class="flex gap-2">
              <span class="h-2 w-2 rounded-full bg-purple-500"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span
              ><span class="h-2 w-2 rounded-full bg-gray-300"></span>
            </div>
            <button aria-label="Next" class="cursor-pointer">
              <img
                alt="Next"
                class="rotate-180 w-6 h-6"
                src="data:image/svg+xml,%3csvg%20width='50'%20height='50'%20viewBox='0%200%2050%2050'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20fill-rule='evenodd'%20clip-rule='evenodd'%20d='M16.917%2021.8752H43.7475V28.1252H16.917L27.2073%2038.4155L22.7878%2042.8349L4.95312%2025.0002L22.7878%207.16553L27.2073%2011.5849L16.917%2021.8752Z'%20fill='%23999999'/%3e%3c/svg%3e"
              />
            </button>
          </div>
        </div>
        <div class="flex flex-col 2xl:mt-12 mt-4 items-center justify-center">
          <p class="font-medium text-sm text-[var(--text-gray)] text-center italic">
            Partner with eMbrace to bring expert-led mental health care, faculty support, and professional development
            to your university.
          </p>
          <p class="font-medium text-sm text-[var(--text-gray)] text-center italic mt-2">
            We work closely with academic institutions to support student well-being, reduce faculty burnout, and create
            pathways for mental health internships and careers.
          </p>
          <a
            class="w-[70%] md:w-[20%] py-2 rounded-full bg-[var(--blue-fig)] mt-4 md:mt-2 2xl:mt-6 text-white font-medium cursor-pointer flex items-center justify-center text-center"
            href="mailto:sam@embracelives.com"
            style="text-decoration: none"
            >Schedule Demo</a
          >
        </div>
      </div>
      <div class="overflow-hidden flex flex-col items-center px-4 md:px-8 lg:px-16 xl:px-20 py-6 relative">
        <div class="flex flex-col items-center">
          <h1 class="text-xl md:text-3xl font-bold text-center">Why Universities choose embrace?</h1>
          <div class="flex flex-col md:flex-row gap-6 md:gap-4 mt-6">
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img alt="Why Embrace 2" class="w-[90%] md:w-full mb-2" src="/assets/EvidenceBased-DPD1TwX2.svg" />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">
                  Evidence-Based Services
                </h2>
                <p class="text-sm text-center">
                  Globally validated therapy models, gold-standard assessments, and early intervention for student
                  well-being.
                </p>
              </div>
            </div>
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img
                alt="Why Embrace 2"
                class="w-[90%] md:w-full mb-2"
                src="/assets/StructuredInternship-erLWyaES.svg"
              />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">
                  Structured Internship &amp; Training Programs
                </h2>
                <p class="text-sm text-center">
                  Practical therapist training, soft skills workshops, and case-based exposure for psychology students.
                </p>
              </div>
            </div>
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img alt="Why Embrace 2" class="w-[90%] md:w-full mb-2" src="/assets/FacultyAndStaff-DJdEEIOh.svg" />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">
                  Faculty &amp; Staff Well-being Support
                </h2>
                <p class="text-sm text-center">
                  Workshops, burnout prevention, and emotional support tailored for educators and administrators.
                </p>
              </div>
            </div>
            <div
              class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
            >
              <img alt="Why Embrace 2" class="w-[90%] md:w-full mb-2" src="/assets/SeamlessCampus-Xzj0QDHk.svg" />
              <div class="text-start">
                <h2 class="text-base italic font-semibold mb-2 text-center text-[var(--blue-fig)]">
                  Seamless Campus Integration
                </h2>
                <p class="text-sm text-center">
                  Services embedded within academic schedules for minimal disruption and maximum participation.
                </p>
              </div>
            </div>
          </div>
          <h1 class="text-xl md:text-3xl font-bold mt-8 text-center">Trusted by Forward-Thinking Institutions</h1>
          <div class="flex flex-col md:flex-row gap-6 md:gap-16 mt-3 justify-center items-center flex-wrap mb-4">
            <div
              class="shadow-[0px_10px_24.5px_0px_#76C1D6D6] bg-[linear-gradient(180deg,_rgba(0,0,0,0)_0%,_rgba(0,0,0,0.09)_100%)] mt-4 rounded-full flex justify-center items-center w-35 h-35 md:w-30 md:h-30 2xl:w-50 2xl:h-50"
            >
              <img
                alt="Trusted 1"
                class="md:w-20 md:h-auto w-25 h-25 2xl:w-35 2xl:h-35 object-contain"
                src="/assets/Trusted1-DpyEm1Q7.svg"
              />
            </div>
            <div
              class="shadow-[0px_10px_24.5px_0px_#76C1D6D6] bg-[linear-gradient(180deg,_rgba(0,0,0,0)_0%,_rgba(0,0,0,0.09)_100%)] mt-4 rounded-full flex justify-center items-center w-35 h-35 md:w-30 md:h-30 2xl:w-50 2xl:h-50"
            >
              <img
                alt="Trusted 2"
                class="md:w-20 md:h-auto w-25 h-25 2xl:w-35 2xl:h-35 object-contain"
                src="/assets/Trusted2-CyirYRFn.svg"
              />
            </div>
            <div
              class="shadow-[0px_10px_24.5px_0px_#76C1D6D6] bg-[linear-gradient(180deg,_rgba(0,0,0,0)_0%,_rgba(0,0,0,0.09)_100%)] mt-4 rounded-full flex justify-center items-center w-35 h-35 md:w-30 md:h-30 2xl:w-50 2xl:h-50"
            >
              <img
                alt="Trusted 3"
                class="md:w-20 md:h-auto w-25 h-25 2xl:w-35 2xl:h-35 object-contain"
                src="data:image/svg+xml,%3csvg%20width='267'%20height='81'%20viewBox='0%200%20267%2081'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%20xmlns:xlink='http://www.w3.org/1999/xlink'%3e%3crect%20x='0.296875'%20y='0.351562'%20width='266.667'%20height='80'%20rx='10'%20fill='url(%23pattern0_1858_11839)'/%3e%3cdefs%3e%3cpattern%20id='pattern0_1858_11839'%20patternContentUnits='objectBoundingBox'%20width='1'%20height='1'%3e%3cuse%20xlink:href='%23image0_1858_11839'%20transform='scale(0.00243902%200.00813008)'/%3e%3c/pattern%3e%3cimage%20id='image0_1858_11839'%20width='410'%20height='123'%20preserveAspectRatio='none'%20xlink:href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZoAAAB7CAMAAAB6t7bCAAAArlBMVEUAAAD///8OwOIOxegOwOPU1NTZ2dnAwMAPyewOw+VUVFTMzMxvb29sbGyOjo5HR0cNsdERERHj4+OTk5MMoL0Ic4g5OTkGVGJbW1ssLCz39/e3t7fIyMjs7Oytra0kJCQKiaKFhYUHZHZkZGSfn59OTk4NudoKhZ15eXkCGh8NrcxBQUG7u7unp6cFSVYLnLcbGxsDJCoXFxcBERQGWmoEMz0JeI4LkasFP0sGTFlp85CPAAAIqklEQVR4nO2ce1ubSBSHSTAatK0xSa0Sc/OSpGqs2m613/+LrXDOmVsGAgSa3ef5vX/sOrcwM+8MDDA0CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqcDPpjFutuP84r+kHr2fDRbu9GC6favrB/wMnLS/TIDj3RJ/rggMV+cX5yYFZYqLjRxTzaB9ZMvzobjCjlJ+zMIyidrt9EIXdxbVxpJ6Ze3FvibvjCtxRcEqhjkq/oYhbDh6ZlY4PJzdmi7hw67MR96hyX2zt5GqM/Wo+DnfsiTYq3FGRJ9YPTp1fjM+dEtI7fbt0L+l8i+hHmvCnHZqx3R/6WNGBlT/s9n6ptE98/E8UFFOXkv6FwkccPHSbGhsj7pTjzEEYq5zrUh1enAw1x1vV6KrF5u9NNwuJm47toqCab10nOrxXB7PVJEVkpmk1PNKld1U/blPTah2q43jUvOp8eibWS1U1RtVaz/m/J+oqqXlRU0Z5CGdysA01H5PqN6dlqFHjaLuaVl/yetTcbLavbqqe0D57Y6XBH4z1L/P5vLSa4Uf0kKIPwvZ9r8tZuv9wGUON+ivkxAw16npRQI26EHnUmBdUc2jWyMhrJj7zqonVmTq49bQg0KZHSWAixSitkBpDUPQxAV7odHYQJReR7/ec543LsJr0vyGXlMQsNXK8ImpagV3YUHNl5DJXBw2weXBR41+AmCu7KxV7yTEdOxOtkoqoSWeKwVc6n4VfKcjSFpxKasL0HPY+5FNfRGlZaqS7/Wo+Kv58d6uuo3O7sNE75tnGGJoNcGbXJSFfTWxUbaxiVxyzoqCc9ahJVdS80VwIOTijYPc7BVkNe+M51X1PQ5lqBhThV3Nl1U1SPWqM5jtL1Lopq+bMrFpLRcsZ+IGCcmtEy6IqavhSI9NEJhH1vqPm2pphmWp4IOWqubTzbqq5MJvf1DqAKKvmxqyaziJqeL0sLaTbyhrVfKOgrYavS+EyDWWqSVafwRY1atrYhbUa67a6dZbZrzVQVg2vArh9A7fGrEZmzd9RE5CaaJYGstWQjXw1cpW3C2s19PAg5m6wHh3UTVk1VPVxYLdvz2qsJVq2Gurv3dRQ5U/4BlsNzSYoq2bM3Ur/V/dmGWrSpXTzasKCatJG7qaGwuvALtUIJdVw9oksjyXeURMMJusPJhT8Syc0fliQoyYdSTupuZPeoqGpl6gNUFLNheTmu0p+vLuhxqJpNe+cSI9qctSkC8id1HDhY2mTr7l1kaPm2JN9IElf7DrvVc1vTqSnz3lqkhPsTmoeJXWS3Ud1kaNmNCfMwx9J1Xj6yDuYImrGn4nYp6bdu2YotoSa77QKaHd/psE8NUmP76SGhlUcuEOzCXLUCOaN1VhinilN1gFF1Di4jzdDoktuiqiJ3t6fnv4s+QlnxO8MctWsdlRDwUN1f6eWqA1QUo2qmjyw4Pga1DBhcTXtKJUpk4bT/GpiqkRnNzUPFBxtDM0mKKeGk5LTGF8x+MnMftRY5eQlqF/NIY+l6U5q5hRMbmesfI1QTo3xEODKKrd3NaFaRmSpocvkeic1I/3T/ARalqgNUE7No67amv6km8o61EREiWuNQbRUR8tSc8yNme+ghk8VU52xwXVAjprOKMXcuNTXAlbS5JRCao4Iv5rFcpaypHVWMTVRJGsIfbQsNTzOL3ZRYyTaQ7MJctR45qpRtTvj7z3d17QXwyHnC/VWqEw1VMer2+pqeBWQXvvnxt/NUOppwKlRHSlIMvZ3y0nv0SK9EypTjfUWrJKalZHXHppNUErN3GwG3znSe839qVny4lmVzFZj7QasooYfAdB7Z0568LW4Fkqpka0enQ9kuwM993fVPF4lnNCDhEbVPFEKv30O8tRY65sqajhvnLRf3rnVtYV4k1JqpDomtFFjjy8F+G+1RMtWY225qKLG03xzA3HNlFLjqxotrff4Ko1yRj0pmaNGb5arpOay5UFv9aybMmp8+9R5M/Ee1UgSb7bJU2OOrQpqVi0PzW3dKKPGWzXa9r1HNf907eVznhpjIVBBzdrbfr17smbKqJl4q5auV/7Wjhr+WsN6KbBoW8vnPDWy4s1WI5sbrcL2fjqHVZFurkIZNdyK0etlwuvY6OI5l3H2od2aTaqyRdBRI5ueLTWcVZbPeWqMhUyGGr4l6FuFWQ2nDZ7T9sunEY2tA8q85XSGCc/92CzDaZ+sYBU1/Oayy0FnM6el5tqeUblq9ELAr2Zlp1pqnu3hJ+1o6lOOPDWDh1MhrY1MBbl3kY3paaBl9YBM/akZKqXmj2/Ps7wtc95yclZePueq0QsBR81hMJ1OT9XVxLfnWXYLSxX5wtXYOqDAk+eEZAatnKpJH6T75ERG+kZabk35tFBFTcAPMNOr+wvvag7lGxp7b0DPWj7nq1Gf+5X/UuDWapQemtMS3V2GgmqS7l87VZNrfXpB0Rtuje9r+PRWSY08gAkP9Pc10U9OtNVw1u5LGspXo95H56pZO7lTNSd2QfdAtVNCTcepmpwcrrKaKN1RSY18t2F8edOVfWeOmm+huXzOV+N+C+BVo7aXWWpkFSCJ1tBsgBJq3KpJK6khZ7FbJpbN2tXUPG18y6mfLvt3b1L6FjXz7WrGape5qUZWAXqfc8tuSN2cGQdnMtTIINFrarmBo5a4X0D3XyWf/roopaCa4Mn6Atr4kHZDjXy0lgb8X0Dr9ypb1RizQNQkw1FO2forQW5IY+uA2O1w76Oic/V9rVGRlRNjfuBgfuLNFym5AXjUzU2Y0df/v4MNkn83IKTX0mH33vy3Ae6pDD8bCK75HxBIA9KdvMblwa7fRq7tw1v30ePDiXXlMGcKOzaembnrgv80N+uT/njcP1nX9a8d/FoO73u94dvXl5p+EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAK/wLkqrBn8u+xyAAAAABJRU5ErkJggg=='/%3e%3c/defs%3e%3c/svg%3e"
              />
            </div>
          </div>
        </div>
        <img
          alt=""
          class="absolute bottom-1/3 left-0 rotate-x-180 hidden md:block"
          src="data:image/svg+xml,%3csvg%20width='50'%20height='80'%20viewBox='0%200%2050%2080'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20cx='26.1005'%20cy='27.2656'%20rx='26.1005'%20ry='27.2656'%20transform='matrix(0.154383%20-0.988011%200.989983%200.141189%20-12.043%2051.5752)'%20fill='%23B9F1DA'/%3e%3cellipse%20opacity='0.5'%20cx='26.1005'%20cy='27.2656'%20rx='26.1005'%20ry='27.2656'%20transform='matrix(0.154383%20-0.988011%200.989983%200.141189%20-30%2072.3008)'%20fill='%2390A7E1'/%3e%3c/svg%3e"
        /><img
          alt=""
          class="absolute bottom-0 right-0 rotate-x-180 hidden md:block"
          src="data:image/svg+xml,%3csvg%20width='66'%20height='80'%20viewBox='0%200%2066%2080'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20cx='26.1005'%20cy='27.2656'%20rx='26.1005'%20ry='27.2656'%20transform='matrix(0.154383%20-0.988011%200.989983%200.141189%2017.957%2051.5752)'%20fill='%23B9F1DA'/%3e%3cellipse%20opacity='0.5'%20cx='26.1005'%20cy='27.2656'%20rx='26.1005'%20ry='27.2656'%20transform='matrix(0.154383%20-0.988011%200.989983%200.141189%200%2072.3008)'%20fill='%2390A7E1'/%3e%3c/svg%3e"
        />
      </div>
      <div
        class="md:min-h-fit overflow-hidden flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-40 py-20 relative bg-gradient-to-b from-[#FCEEF3] to-[#FCEEF3]"
      >
        <img
          alt=""
          class="absolute bottom-0 right-5 w-14 hidden md:block"
          src="data:image/svg+xml,%3csvg%20width='174'%20height='167'%20viewBox='0%200%20174%20167'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20opacity='0.5'%20cx='57.6755'%20cy='60'%20rx='57.6755'%20ry='60'%20fill='%2390A7E1'/%3e%3cellipse%20cx='115.347'%20cy='107'%20rx='57.6755'%20ry='60'%20fill='%23B9F1DA'/%3e%3c/svg%3e"
        />
        <div class="w-14 h-14 bg-[#93CFEF] rounded-full absolute top-1/2 -left-6 hidden md:block"></div>
        <h1 class="text-xl md:text-3xl font-bold text-center">Student Programs</h1>
        <div class="flex flex-col md:flex-row gap-6 md:gap-4 mt-6">
          <div
            class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img alt="" class="w-[90%] md:w-full md:mb-12 mb-4" src="/assets/Counseling-BzBwEfbx.svg" />
            <div class="text-start">
              <h2 class="text-base italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Counseling &amp; Therapy
              </h2>
              <p class="text-sm text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Online &amp; On-campus support for Mental health support for anxiety, gaming, screen use, academic
                stress, depression, relationships, and life transitions.
              </p>
            </div>
          </div>
          <div
            class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img alt="" class="w-[90%] md:w-full md:mb-12 mb-4" src="/assets/Assessment-B_iWBW-P.svg" />
            <div class="text-start">
              <h2 class="text-base italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Assessment &amp; Screenings
              </h2>
              <p class="text-sm text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Early detection of emotional, academic stressors &amp; neurodivergent conditions with standardized
                tools.
              </p>
            </div>
          </div>
          <div
            class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img alt="" class="w-[90%] md:w-full md:mb-12 mb-4" src="/assets/CrisisIntervention-6_JbgQut.svg" />
            <div class="text-start">
              <h2 class="text-base italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Crisis Intervention &amp; Suicide Prevention
              </h2>
              <p class="text-sm text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Faculty training and mental health first-aid response systems.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div
        class="md:min-h-fit overflow-hidden flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-40 relative bg-gradient-to-b from-[#FCEEF3] via-[#F2FBFF] to-[#F2FBFF]"
      >
        <img
          alt=""
          class="absolute bottom-12 left-0 w-14 hidden md:block"
          src="data:image/svg+xml,%3csvg%20width='174'%20height='167'%20viewBox='0%200%20174%20167'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cellipse%20opacity='0.5'%20cx='57.6755'%20cy='60'%20rx='57.6755'%20ry='60'%20fill='%2390A7E1'/%3e%3cellipse%20cx='115.347'%20cy='107'%20rx='57.6755'%20ry='60'%20fill='%23B9F1DA'/%3e%3c/svg%3e"
        />
        <div class="w-14 h-14 bg-[#90A7E1] rounded-full absolute bottom-0 -right-6 hidden md:block"></div>
        <h1 class="text-xl md:text-3xl font-bold text-center">Faculty Staff Training &amp; Support</h1>
        <div class="flex flex-col md:flex-row gap-6 md:gap-4 mt-6">
          <div
            class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img
              alt="Why Embrace 2"
              class="w-[90%] md:w-full md:mb-12 mb-4"
              src="/assets/FacultyWellness-CZBuPeBQ.svg"
            />
            <div class="text-start">
              <h2 class="text-base md:text-lg italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Faculty Wellness Programs
              </h2>
              <p class="text-sm md:text-base text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Stress management, emotional health, and boundary setting in educator roles.
              </p>
            </div>
          </div>
          <div
            class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img alt="Why Embrace 2" class="w-[90%] md:w-full md:mb-12 mb-4" src="/assets/Classrooms-C7WypI4b.svg" />
            <div class="text-start">
              <h2 class="text-base md:text-lg italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Inclusive Classrooms Training
              </h2>
              <p class="text-sm md:text-base text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Understanding neurodiversity, managing academic accommodations, and emotional sensitivity in classrooms.
              </p>
            </div>
          </div>
          <div
            class="bg-white border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img alt="Why Embrace 2" class="w-[90%] md:w-full md:mb-12 mb-4" src="/assets/Emotional-C76VLMBu.svg" />
            <div class="text-start">
              <h2 class="text-base md:text-lg italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                DEI &amp; Emotional Intelligence Workshops
              </h2>
              <p class="text-sm md:text-base text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Practical guidance on creating empathetic, safe campus environments.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div
        class="md:min-h-fit overflow-hidden flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-40 py-20 relative bg-gradient-to-b from-[#F4FBFF] to-[#F8F2FF]"
      >
        <div class="w-15 h-15 rounded-full bg-[#2FB1EA6E] absolute -bottom-2 left-[10%] hidden md:block"></div>
        <h1 class="text-xl md:text-3xl font-bold text-center">Internship &amp; Career Readiness Programs</h1>
        <div class="flex flex-col md:flex-row gap-6 md:gap-4 mt-6">
          <div
            class="bg-white z-[1] border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img
              alt="Why Embrace 2"
              class="w-[90%] md:w-full md:mb-12 mb-4"
              src="/assets/TherapistTraining-o5_PPKWl.svg"
            />
            <div class="text-start">
              <h2 class="text-base md:text-lg italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Therapist Training &amp; Observerships
              </h2>
              <p class="text-sm md:text-base text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Live case-based learning, psychological assessment exposure, and supervised clinical hours.
              </p>
            </div>
          </div>
          <div
            class="bg-white z-[1] border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img
              alt="Why Embrace 2"
              class="w-[90%] md:w-full md:mb-12 mb-4"
              src="/assets/ProfessionalSkill-BkfF7AqI.svg"
            />
            <div class="text-start">
              <h2 class="text-base md:text-lg italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Professional Skill Building
              </h2>
              <p class="text-sm md:text-base text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Workshops on therapeutic communication, case documentation, and ethics.
              </p>
            </div>
          </div>
          <div
            class="bg-white z-[1] border-2 border-gray-200 rounded-4xl p-6 flex flex-col items-center mx-auto w-[90%] md:w-[50%] h-auto"
          >
            <img
              alt="Why Embrace 2"
              class="w-[90%] md:w-full md:mb-12 mb-4"
              src="/assets/CustomizedPrograms-Dbp6qECt.svg"
            />
            <div class="text-start">
              <h2 class="text-base md:text-lg italic font-semibold mb-4 md:mb-6 text-center text-[var(--blue-fig)]">
                Customized Programs for Psychology Departments
              </h2>
              <p class="text-sm md:text-base text-center mb-4 md:mb-6 w-[80%] mx-auto">
                Curriculum-linked training aligned with international frameworks and real-world requirements.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div
        class="md:min-h-screen overflow-hidden flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-20 py-6 relative bg-gradient-to-b from-[#FBF7F9] to-[#FBF7F9]"
      >
        <div class="w-15 h-15 rounded-full bg-[#BEEDB9] absolute -bottom-8 left-12 hidden md:block"></div>
        <div class="w-15 h-15 rounded-full bg-[#FF8E0078] absolute bottom-1/2 -right-8 hidden md:block"></div>
        <h1 class="text-xl md:text-3xl font-bold text-center">How it works?</h1>
        <div class="hidden md:flex justify-center w-full py-[3rem]">
          <div class="relative w-full max-w-4xl">
            <div
              class="absolute left-1/2 transform -translate-x-1/2 w-0.75 bg-[#7F7F7F] z-0 -mt-6 -mb-6 h-[calc(100%+3rem)]"
            >
              <div
                class="absolute top-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-3 h-3 bg-[#7F7F7F] rounded-full z-10"
              ></div>
              <div
                class="absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2 w-3 h-3 bg-[#7F7F7F] rounded-full z-10"
              ></div>
            </div>
            <div class="flex items-start mb-0 2xl:mb-6 relative z-10">
              <div class="w-1/2 pr-8 text-left">
                <h3 class="lg:text-xl 2xl:text-2xl font-bold text-[#4562AD]">Assessment of Campus:</h3>
                <p class="w-[70%] text-gray-600 text-md 2xl:text-lg">
                  Identify key gaps across student, faculty, and training programs.
                </p>
              </div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2"></div>
            </div>
            <div class="flex items-start mb-0 2xl:mb-6 relative z-10">
              <div class="w-1/2"></div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2 pl-8 text-right">
                <h3 class="lg:text-xl 2xl:text-2xl font-bold text-[#4562AD]">Program Customization:</h3>
                <div class="flex justify-end">
                  <p class="w-[70%] text-gray-600 text-md 2xl:text-lg">
                    Build from modular components therapy, training, internship, or research.
                  </p>
                </div>
              </div>
            </div>
            <div class="flex items-start mb-0 2xl:mb-6 relative z-10">
              <div class="w-1/2 pr-8 text-left">
                <h3 class="lg:text-xl 2xl:text-2xl font-bold text-[#4562AD]">On-Campus or Remote Deployment:</h3>
                <p class="w-[70%] text-gray-600 text-md 2xl:text-lg">
                  Schedule-based implementation to ensure smooth academic integration.
                </p>
              </div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2"></div>
            </div>
            <div class="flex items-start relative z-10">
              <div class="w-1/2"></div>
              <div class="w-0 relative flex flex-col items-center">
                <div class="flex items-center justify-center w-6 h-6 bg-[#90A7E1] rounded-full">
                  <div class="w-4 h-4 bg-[#4562AD] rounded-full z-10"></div>
                </div>
              </div>
              <div class="w-1/2 pl-8 text-right">
                <h3 class="lg:text-xl 2xl:text-2xl font-bold text-[#4562AD]">Ongoing Monitoring &amp; Feedback:</h3>
                <div class="flex justify-end">
                  <p class="w-[70%] text-gray-600 text-md 2xl:text-lg">
                    Monthly updates, feedback dashboards, and direct student/faculty input.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="block md:hidden px-6 py-12 mt-10 relative">
          <div class="absolute top-0 h-full w-0.75 bg-[#7F7F7F]">
            <div
              class="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 w-4 h-4 bg-[#7F7F7F] rounded-full z-10"
            ></div>
            <div
              class="absolute bottom-0 left-1/2 -translate-x-1/2 translate-y-1/2 w-4 h-4 bg-[#7F7F7F] rounded-full z-10"
            ></div>
          </div>
          <div class="flex items-start mb-10 relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">Assessment of Campus:</h3>
              <p class="text-gray-600 text-sm">Identify key gaps across student, faculty, and training programs.</p>
            </div>
          </div>
          <div class="flex items-start mb-10 relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">Program Customization:</h3>
              <p class="text-gray-600 text-sm">
                Build from modular components therapy, training, internship, or research.
              </p>
            </div>
          </div>
          <div class="flex items-start mb-10 relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">On-Campus or Remote Deployment:</h3>
              <p class="text-gray-600 text-sm">Schedule-based implementation to ensure smooth academic integration.</p>
            </div>
          </div>
          <div class="flex items-start relative z-10 right-2.5">
            <div class="flex-shrink-0 w-6 h-6 bg-[#90A7E1] rounded-full flex items-center justify-center mr-6 mt-1">
              <div class="w-3 h-3 bg-[#4562AD] rounded-full"></div>
            </div>
            <div>
              <h3 class="text-md font-bold text-[#4562AD]">Ongoing Monitoring &amp; Feedback:</h3>
              <p class="text-gray-600 text-sm">
                Monthly updates, feedback dashboards, and direct student/faculty input.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div
        class="md:min-h-screen overflow-visible flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-20 py-6 md:py-10 relative"
      >
        <h1 class="text-xl md:text-3xl font-bold text-center">See Wellbeing Spaces in Action</h1>
        <p class="font-medium text-[var(--text-gray)] italic text-center">
          Personalized, empathetic spaces designed for comfort and growth
        </p>
        <div class="relative flex mt-6 items-center justify-center w-full mx-auto">
          <img
            alt="carousel-1"
            class="md:w-[90%] 2xl:h-[50rem] h-[30rem] object-cover rounded-xl shadow"
            src="/assets/carousel1-BUqaO1dK.jpg"
          /><button
            class="absolute top-1/2 left-3 md:left-16 2xl:left-25 -translate-y-1/2 z-10 p-3 bg-white/70 rounded-full shadow hover:bg-white"
          >
            <img
              alt="Previous"
              class="md:w-6 md:h-6 w-3 h-3"
              src="data:image/svg+xml,%3csvg%20width='30'%20height='39'%20viewBox='0%200%2030%2039'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M1.694%2017.0118C-0.0713594%2018.2009%20-0.0713545%2020.7991%201.694%2021.9882L24.824%2037.568C26.8167%2038.9102%2029.5%2037.4824%2029.5%2035.0798L29.5%203.92019C29.5%201.51762%2026.8167%200.0897827%2024.824%201.432L1.694%2017.0118Z'%20fill='%23234394'/%3e%3c/svg%3e"
            /></button
          ><button
            class="absolute top-1/2 right-3 md:right-16 2xl:right-25 -translate-y-1/2 z-10 p-3 bg-white/70 rounded-full shadow hover:bg-white"
          >
            <img
              alt="Next"
              class="rotate-180 md:w-6 md:h-6 w-3 h-3"
              src="data:image/svg+xml,%3csvg%20width='30'%20height='39'%20viewBox='0%200%2030%2039'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M1.694%2017.0118C-0.0713594%2018.2009%20-0.0713545%2020.7991%201.694%2021.9882L24.824%2037.568C26.8167%2038.9102%2029.5%2037.4824%2029.5%2035.0798L29.5%203.92019C29.5%201.51762%2026.8167%200.0897827%2024.824%201.432L1.694%2017.0118Z'%20fill='%23234394'/%3e%3c/svg%3e"
            />
          </button>
        </div>
      </div>
      <div
        class="md:min-h-screen overflow-visible flex flex-col items-center justify-center px-4 md:px-8 lg:px-16 xl:px-20 py-6 md:py-10 relative bg-gradient-to-b from-[#E6FFFD99] to-[#FEF9FC]"
      >
        <div class="hidden md:block w-14 h-14 bg-[#90A7E19C] absolute -left-8 top-1/2 z-[10] rounded-full"></div>
        <div class="hidden md:block w-14 h-14 bg-[#6A56CF8F] absolute right-25 bottom-0 z-[10] rounded-full"></div>
        <h1 class="text-xl text-center md:text-3xl font-bold">Frequently asked questions</h1>
        <div class="space-y-4 mb-12 mt-12">
          <div class="md:w-[60%] mx-auto bg-white rounded-2xl shadow-md/10 overflow-hidden">
            <button
              class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
            >
              <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                >Can students access care both online and on campus? </span
              ><img
                alt="toggle"
                class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
              />
            </button>
            <div
              class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
              style="word-break: break-word"
            >
              <div class="pb-4 text-sm sm:text-base break-words">
                <div class="space-y-3">
                  <p class="text-[#234394] font-medium">
                     Yes! Our flexible hybrid model allows students to choose what suits them best.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="md:w-[60%] mx-auto bg-white rounded-2xl shadow-md/10 overflow-hidden">
            <button
              class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
            >
              <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                >Do you support internship or practicum credit requirements?</span
              ><img
                alt="toggle"
                class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
              />
            </button>
            <div
              class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
              style="word-break: break-word"
            >
              <div class="pb-4 text-sm sm:text-base break-words">
                <div class="space-y-3">
                  <p class="text-[#234394] font-medium">
                    Yes, our internship program is designed to align with university credit requirements and global
                    training standards.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="md:w-[60%] mx-auto bg-white rounded-2xl shadow-md/10 overflow-hidden">
            <button
              class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
            >
              <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                >Can we customize the training content for our faculty?</span
              ><img
                alt="toggle"
                class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
              />
            </button>
            <div
              class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
              style="word-break: break-word"
            >
              <div class="pb-4 text-sm sm:text-base break-words">
                <div class="space-y-3">
                  <p class="text-[#234394] font-medium">
                    Absolutely. All faculty development modules are designed in partnership with institutions based on
                    their needs.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="md:w-[60%] mx-auto bg-white rounded-2xl shadow-md/10 overflow-hidden">
            <button
              class="w-full px-4 sm:px-6 py-3 sm:py-4 text-left flex justify-between items-center focus:outline-none"
            >
              <span class="font-medium text-gray-800 md:text-base text-sm break-words"
                >Is your work recognized by regulatory bodies?</span
              ><img
                alt="toggle"
                class="w-5 h-5 sm:w-4 sm:h-4 transition-transform duration-200"
                src="data:image/svg+xml,%3csvg%20width='46'%20height='48'%20viewBox='0%200%2046%2048'%20fill='none'%20xmlns='http://www.w3.org/2000/svg'%3e%3cpath%20d='M43.125%2021H25.875V3C25.875%202.20435%2025.5721%201.44129%2025.0329%200.87868C24.4938%200.316071%2023.7625%200%2023%200C22.2375%200%2021.5062%200.316071%2020.9671%200.87868C20.4279%201.44129%2020.125%202.20435%2020.125%203V21H2.875C2.1125%2021%201.38124%2021.3161%200.842069%2021.8787C0.302901%2022.4413%200%2023.2044%200%2024C0%2024.7956%200.302901%2025.5587%200.842069%2026.1213C1.38124%2026.6839%202.1125%2027%202.875%2027H20.125V45C20.125%2045.7957%2020.4279%2046.5587%2020.9671%2047.1213C21.5062%2047.6839%2022.2375%2048%2023%2048C23.7625%2048%2024.4938%2047.6839%2025.0329%2047.1213C25.5721%2046.5587%2025.875%2045.7957%2025.875%2045V27H43.125C43.8875%2027%2044.6188%2026.6839%2045.1579%2026.1213C45.6971%2025.5587%2046%2024.7956%2046%2024C46%2023.2044%2045.6971%2022.4413%2045.1579%2021.8787C44.6188%2021.3161%2043.8875%2021%2043.125%2021Z'%20fill='%23403D3D'/%3e%3c/svg%3e"
              />
            </button>
            <div
              class="transition-all duration-300 ease-in-out overflow-hidden px-4 sm:px-6 max-h-0 opacity-0"
              style="word-break: break-word"
            >
              <div class="pb-4 text-sm sm:text-base break-words">
                <div class="space-y-3">
                  <p class="text-[#234394] font-medium">
                     Yes, our assessments and therapy models follow international standards (NICE UK, Pearson, WHO) and
                    are accepted by major educational and healthcare boards.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <p class="text-base font-semibold italic text-[var(--text-gray)] text-center">
          <span
            >Have more questions? Write to us at
            <span class="text-[var(--blue-fig)] cursor-pointer hover:underline">enquiries@embracelives.com</span></span
          >
        </p>
      </div>
      <!-- LOCATION-LINKS:START (generated by generate-location-links.js — do not edit by hand) -->
<div class="px-6 md:px-16 bg-white">
<div class="max-w-7xl mx-auto">
<section class="emb-nearby" aria-labelledby="emb-nearby-title">
  <h2 class="emb-nearby__title" id="emb-nearby-title">Teen Counselling across Delhi NCR</h2>
  <p class="emb-nearby__sub">We offer teen counselling at eMbrace centres throughout Delhi and the wider NCR. Choose the location closest to you.</p>
  <div class="emb-nearby__cols">
    <div class="emb-nearby__group">
      <ul class="emb-nearby__list emb-nearby__list--wide">
      <li><a href="/locations/teen-counselling-in-delhi">Teen Counselling in Delhi</a></li>
      <li><a href="/locations/teen-counselling-in-south-delhi">Teen Counselling in South Delhi</a></li>
      <li><a href="/locations/teen-counselling-in-saket">Teen Counselling in Saket</a></li>
      <li><a href="/locations/teen-counselling-in-hauz-khas">Teen Counselling in Hauz Khas</a></li>
      <li><a href="/locations/teen-counselling-in-green-park">Teen Counselling in Green Park</a></li>
      <li><a href="/locations/teen-counselling-in-greater-kailash">Teen Counselling in Greater Kailash</a></li>
      <li><a href="/locations/teen-counselling-in-defence-colony">Teen Counselling in Defence Colony</a></li>
      <li><a href="/locations/teen-counselling-in-vasant-kunj">Teen Counselling in Vasant Kunj</a></li>
      <li><a href="/locations/teen-counselling-in-gurgaon">Teen Counselling in Gurgaon</a></li>
      <li><a href="/locations/teen-counselling-in-noida">Teen Counselling in Noida</a></li>
      </ul>
    </div>
  </div>
  <a class="emb-nearby__more" href="/locations">View all eMbrace locations &rsaquo;</a>
</section>
</div>
</div>
<!-- LOCATION-LINKS:END -->
      <?php include __DIR__ . '/components/lead-magnet-band-adult.php'; ?>
      <?php include __DIR__ . '/components/footer.php'; ?>
    </div>
    
    <script src="/assets/interactive.js"></script>
  <script src="/assets/lead-magnets.js"></script>
</body>
</html>
