<!DOCTYPE html>
<html lang="en-IN" class="overflow-x-hidden">
<head>
<meta charset="utf-8"/>
<link href="/Favicon.png" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Free 3-minute ADHD and autism early-signs screener for parents. Four behaviour clusters profiled, plus a straight answer on whether an assessment is worth it." name="description"/>
<meta content="index, follow" name="robots"/>
<link href="https://embracelives.com/resources/adhd-autism-screener" rel="canonical"/>
<meta content="website" property="og:type"/>
<meta content="https://embracelives.com/resources/adhd-autism-screener" property="og:url"/>
<meta content="Free ADHD &amp; Autism Screener for Parents | eMbrace Delhi" property="og:title"/>
<meta content="Free 3-minute ADHD and autism early-signs screener for parents. Four behaviour clusters profiled, plus a straight answer on whether an assessment is worth it." property="og:description"/>
<meta content="https://embracelives.com/og-image.png" property="og:image"/>
<meta content="eMbrace Lives" property="og:site_name"/>
<meta content="en_IN" property="og:locale"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Free ADHD &amp; Autism Screener for Parents | eMbrace Delhi" name="twitter:title"/>
<meta content="Free 3-minute ADHD and autism early-signs screener for parents. Four behaviour clusters profiled, plus a straight answer on whether an assessment is worth it." name="twitter:description"/>
<meta content="https://embracelives.com/og-image.png" name="twitter:image"/>
<title>Free ADHD &amp; Autism Screener for Parents | eMbrace Delhi</title>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
<script src="https://unpkg.com/@phosphor-icons/web"></script>
<link href="/assets/index-B-kGA3UA.css" rel="stylesheet"/>
<link href="/assets/lead-magnets.css" rel="stylesheet"/>
<style>
  body, h1, h2, h3, h4, h5, h6, p, a, span, div, button, input { font-family: 'Outfit', sans-serif; }
</style>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "WebPage",
      "@id": "https://embracelives.com/resources/adhd-autism-screener#webpage",
      "url": "https://embracelives.com/resources/adhd-autism-screener",
      "name": "Free ADHD & Autism Screener for Parents | eMbrace Delhi",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "Free 3-minute ADHD and autism early-signs screener for parents. Four behaviour clusters profiled, plus a straight answer on whether an assessment is worth it."
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
<body class="overflow-x-hidden">
<div id="root" class="overflow-x-hidden">
<?php include __DIR__ . '/../components/header.php'; ?>

<!-- Hero -->
<section class="lm-section" style="padding-bottom:2rem;background:linear-gradient(180deg,#fff6fa,#ffffff)">
  <div class="lm-blob lm-blob--c"></div>
  <div class="lm-wrap lm-wrap--narrow lm-center">
    <span class="lm-eyebrow" style="background:#ffe7ee;color:#b03163"><i class="ph-fill ph-brain"></i> Free parent screener</span>
    <h1 class="lm-h2">ADHD &amp; Autism Early-Signs Screener</h1>
    <p class="lm-sub">
      Seventeen questions that profile four separate patterns — attention, impulsivity, social communication,
      and routines and sensory needs. You see the result immediately, with a straight answer on whether a
      formal assessment is worth booking or whether it is too early to tell.
    </p>
    <div style="display:flex;flex-wrap:wrap;gap:.6rem;justify-content:center;margin-top:1.5rem">
      <span class="lm-eyebrow" style="background:#e3faf0;color:#1d7d59"><i class="ph-fill ph-clock"></i> 3 minutes</span>
      <span class="lm-eyebrow" style="background:#fff3d9;color:#8a6100"><i class="ph-fill ph-eye-slash"></i> No sign-up to see results</span>
      <span class="lm-eyebrow"><i class="ph-fill ph-certificate"></i> DSM-5-informed behaviour domains</span>
    </div>
  </div>
</section>

<!-- Quiz -->
<section style="padding:0 1rem 3.5rem;background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <div id="lm-quiz"></div>
  </div>
</section>

<!-- Honest framing -->
<section class="lm-section" style="background:linear-gradient(180deg,#f8faff,#ffffff)">
  <div class="lm-wrap">
    <div class="lm-center">
      <span class="lm-eyebrow">Read this before you read your result</span>
      <h2 class="lm-h2">A screener narrows the question. It cannot answer it.</h2>
      <p class="lm-sub">
        ADHD and autism share surface behaviours with anxiety, hearing difficulty, sleep deprivation,
        learning disorders and plain developmental variation. That overlap is exactly why screening online is
        useful for deciding whether to act — and useless for deciding what your child has.
      </p>
    </div>
    <div class="lm-grid">
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--neuro"><i class="ph-fill ph-magnifying-glass"></i></div>
        <h3 class="lm-card__title">What this tool does</h3>
        <ul class="lm-card__list">
          <li>Sorts behaviour into four recognised clusters</li>
          <li>Shows which cluster is driving your concern</li>
          <li>Weighs how much daily life is affected</li>
          <li>Tells you whether a clinician should look</li>
        </ul>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--adult"><i class="ph-fill ph-prohibit"></i></div>
        <h3 class="lm-card__title">What it cannot do</h3>
        <ul class="lm-card__list">
          <li>Diagnose ADHD, autism or anything else</li>
          <li>Replace observation across home and school</li>
          <li>Rule out hearing, vision or sleep causes</li>
          <li>Support a school accommodation request on its own</li>
        </ul>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--child"><i class="ph-fill ph-clipboard-text"></i></div>
        <h3 class="lm-card__title">What a real assessment adds</h3>
        <ul class="lm-card__list">
          <li>Standardised tools — ADOS-2, Vineland, Conners, WISC-V</li>
          <li>Teacher and parent reports, side by side</li>
          <li>Direct clinical observation of your child</li>
          <li>A written report schools and boards accept</li>
        </ul>
      </div>
    </div>
  </div>
</section>

<!-- Assessment pathway -->
<section class="lm-section" style="background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <span class="lm-eyebrow">If you do go ahead</span>
    <h2 class="lm-h2">What an assessment at eMbrace actually looks like</h2>
    <div class="lm-actions" style="margin-top:1.5rem">
      <h4>Four steps, typically over two to three weeks</h4>
      <ol>
        <li><strong>Intake call (15 minutes, free).</strong> We work out whether an assessment is even the right next step. Plenty of families leave this call with home strategies instead of an appointment.</li>
        <li><strong>Developmental history (60–90 minutes).</strong> A clinical psychologist takes a full history with you — pregnancy, milestones, medical history, school reports, family patterns.</li>
        <li><strong>Direct assessment (2–4 sessions).</strong> Standardised, age-appropriate tools with your child. For autism that usually includes ADOS-2; for ADHD, Conners rating scales plus attention testing; where learning is a concern, a WISC-V cognitive profile.</li>
        <li><strong>Feedback and written report.</strong> A sit-down explanation in plain language, a report you can give to school or a board, and a specific therapy plan — speech, occupational therapy, behaviour support, or nothing at all if that is the honest answer.</li>
      </ol>
    </div>
    <p class="lm-disclaimer" style="margin-top:1.5rem">
      Assessments at eMbrace are conducted by RCI-certified clinical psychologists across our Vasant Kunj,
      Gurugram and Malviya Nagar centres, with a developmental paediatrician involved where a medical opinion
      is needed. Ask us for the current fee schedule on your intake call — we quote it upfront, in writing.
    </p>
  </div>
</section>

<!-- FAQ -->
<section class="lm-section" style="background:linear-gradient(180deg,#ffffff,#fff6fa)">
  <div class="lm-wrap lm-wrap--narrow">
    <div class="lm-center"><h2 class="lm-h2">Questions parents ask us</h2></div>
    <div style="margin-top:2rem;display:grid;gap:.85rem">
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">My child scored high on both ADHD and autism patterns. Is that possible?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">Yes, and it is common — the two co-occur in a substantial share of cases, and since 2013 they can be formally diagnosed together. It is also possible for one to imitate the other: a child who cannot follow classroom language may look inattentive, and a child with severe attention difficulties may miss the social cues that build friendships. Untangling that is exactly what a proper assessment is for.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">Is my child too young to be assessed?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">Autism can be reliably identified in many children from around 18–24 months, and early support in those years makes a measurable difference. ADHD is usually diagnosed from about six, because before that the behaviours overlap heavily with normal preschool development — but younger children with significant difficulties are still assessed and supported, just under a different framework.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">Will a diagnosis label my child for life?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">A diagnosis is a key, not a label. In practice it is what unlocks school accommodations, board exam concessions under CBSE and IB provisions, a UDID card where applicable, and therapy that is actually targeted rather than generic. Families who wait usually tell us later that the delay cost their child more than the diagnosis ever did.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">My school suggested we get "tested". What do they need?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">Schools generally need a formal psychological report from an RCI-certified clinical psychologist, listing the assessment tools used and the recommended accommodations. Your free guide includes a ready-to-send letter template for requesting classroom accommodations, and our reports are written in the format Delhi NCR schools and examination boards expect.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">Can we do this online?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">History-taking, feedback and most therapy work well online, and we support families across India and abroad this way. The direct assessment components — especially ADOS-2 — need to be done in person, at one of our three centres.</p>
      </details>
    </div>
  </div>
</section>

<?php include __DIR__ . '/../components/lead-magnet-cta.php'; ?>

<?php include __DIR__ . '/../components/footer.php'; ?>
</div>
<script src="/assets/lead-magnets.js"></script>
<script>
(function () {
  var FREQ = [
    { key: '1', label: 'Never or rarely', value: 0 },
    { key: '2', label: 'Sometimes', value: 1 },
    { key: '3', label: 'Often', value: 2 },
    { key: '4', label: 'Very often', value: 3 },
  ];

  var ATTENTION = 'Attention & focus';
  var IMPULSE = 'Activity & impulsivity';
  var SOCIAL = 'Social communication';
  var ROUTINE = 'Routines, interests & sensory';
  var IMPACT = 'Impact on daily life';

  var ITEMS = [
    { d: ATTENTION, t: 'Loses focus on schoolwork or tasks that need sustained mental effort.' },
    { d: ATTENTION, t: 'Seems not to listen even when spoken to directly.' },
    { d: ATTENTION, t: 'Loses or forgets things needed for daily activities — books, water bottle, homework.' },
    { d: ATTENTION, t: 'Starts tasks but leaves them unfinished, and gets easily sidetracked.' },
    { d: IMPULSE, t: 'Fidgets, squirms, or leaves their seat when they are expected to stay put.' },
    { d: IMPULSE, t: 'Blurts out answers or interrupts conversations and games.' },
    { d: IMPULSE, t: 'Finds waiting for a turn genuinely hard.' },
    { d: IMPULSE, t: 'Is "always on the go", as if driven by a motor.' },
    { d: SOCIAL, t: 'Makes limited eye contact during conversation, even with familiar people.' },
    { d: SOCIAL, t: 'Finds it hard to start or keep a back-and-forth conversation going.' },
    { d: SOCIAL, t: 'Prefers to play alone, or plays near other children rather than with them.' },
    { d: SOCIAL, t: 'Misses social cues — tone of voice, facial expression, personal space.' },
    { d: ROUTINE, t: 'Becomes very distressed by small changes to routine or plans.' },
    { d: ROUTINE, t: 'Has intense, narrow interests they return to again and again.' },
    { d: ROUTINE, t: 'Repeats movements or phrases — hand-flapping, rocking, lining things up, echoing.' },
    { d: ROUTINE, t: 'Is unusually sensitive to sound, texture, light, food or clothing — or seeks those sensations out.' },
  ];

  var AGE_STEP = {
    id: 'age',
    text: 'How old is your child?',
    help: 'Age changes what counts as expected behaviour, so we factor it into the interpretation.',
    options: [
      { key: '1', label: 'Under 3 years', value: 'under3' },
      { key: '2', label: '3–5 years', value: '3to5' },
      { key: '3', label: '6–9 years', value: '6to9' },
      { key: '4', label: '10–13 years', value: '10to13' },
      { key: '5', label: '14–18 years', value: '14to18' },
    ],
  };

  var IMPACT_STEP = {
    id: 'impact',
    domain: IMPACT,
    text: 'How much do these behaviours affect school, friendships or home life?',
    help: 'This matters as much as the behaviours themselves. Clinically, difficulty only counts when it interferes with daily functioning.',
    options: [
      { key: '1', label: 'Not at all — we manage fine', value: 0 },
      { key: '2', label: 'A little — occasional friction', value: 1 },
      { key: '3', label: 'Quite a lot — regular problems at school or home', value: 2 },
      { key: '4', label: 'A great deal — it dominates our days', value: 3 },
    ],
  };

  var AGE_LABEL = {
    under3: 'under 3', '3to5': '3–5 years', '6to9': '6–9 years',
    '10to13': '10–13 years', '14to18': '14–18 years',
  };

  var steps = [AGE_STEP];
  ITEMS.forEach(function (item, i) {
    steps.push({ id: 'q' + i, domain: item.d, text: item.t, options: FREQ });
  });
  steps.push(IMPACT_STEP);

  EmbraceLM.init({
    mount: '#lm-quiz',
    id: 'adhd-autism-screener',
    name: 'ADHD & Autism Early-Signs Screener',
    minutes: 3,
    // Matches the appointment form's select values; interpret() overrides the
    // condition with whichever cluster actually dominates.
    specialtyTag: 'child_psychologist',
    conditionTag: 'adhd',
    disclaimer: 'This screener is educational and does not diagnose anything. ADHD and autism can only be ' +
      'diagnosed by a qualified clinician after a structured assessment across settings. Anxiety, hearing ' +
      'difficulty, sleep problems and learning disorders can all produce these same behaviours.',

    steps: steps,

    interpret: function (state) {
      var age = state.answers.age.value;
      var impact = state.answers.impact.value;
      var groups = {};
      groups[ATTENTION] = { score: 0, max: 0 };
      groups[IMPULSE] = { score: 0, max: 0 };
      groups[SOCIAL] = { score: 0, max: 0 };
      groups[ROUTINE] = { score: 0, max: 0 };

      Object.keys(state.answers).forEach(function (key) {
        if (key === 'age' || key === 'impact') return;
        var a = state.answers[key];
        groups[a.domain].score += a.value;
        groups[a.domain].max += 3;
      });

      function pct(g) { return Math.round((g.score / g.max) * 100); }
      function level(p) { return p >= 60 ? 'red' : (p >= 35 ? 'amber' : 'green'); }
      function levelLabel(p) { return p >= 60 ? 'Strong signal' : (p >= 35 ? 'Some signal' : 'Little signal'); }

      var attentionPct = pct(groups[ATTENTION]);
      var impulsePct = pct(groups[IMPULSE]);
      var socialPct = pct(groups[SOCIAL]);
      var routinePct = pct(groups[ROUTINE]);

      var adhdPct = Math.round((attentionPct + impulsePct) / 2);
      var autismPct = Math.round((socialPct + routinePct) / 2);
      var peak = Math.max(adhdPct, autismPct);

      var meters = [
        { label: ATTENTION, pct: attentionPct, level: level(attentionPct), levelLabel: levelLabel(attentionPct),
          note: 'Inattention, distractibility and follow-through — the first of the two ADHD presentations.' },
        { label: IMPULSE, pct: impulsePct, level: level(impulsePct), levelLabel: levelLabel(impulsePct),
          note: 'Restlessness, waiting and self-control — the second ADHD presentation.' },
        { label: SOCIAL, pct: socialPct, level: level(socialPct), levelLabel: levelLabel(socialPct),
          note: 'Reciprocal interaction and reading social cues — a core autism domain.' },
        { label: ROUTINE, pct: routinePct, level: level(routinePct), levelLabel: levelLabel(routinePct),
          note: 'Sameness, focused interests, repetitive movement and sensory response — the second autism domain.' },
        { label: IMPACT, pct: Math.round((impact / 3) * 100), level: level(Math.round((impact / 3) * 100)),
          levelLabel: impact >= 2 ? 'Significant' : (impact === 1 ? 'Mild' : 'Minimal'),
          note: 'Clinically, behaviour only becomes a disorder when it interferes with everyday functioning.' },
      ];

      var pattern;
      if (adhdPct >= 45 && autismPct >= 45) {
        pattern = 'Your answers show signal in <strong>both</strong> the attention/impulsivity cluster and the social communication/sensory cluster. That combination is common, and it is also the situation where an online screener is least able to separate cause from consequence.';
      } else if (adhdPct > autismPct + 10) {
        pattern = 'The signal in your answers sits mainly in the <strong>attention and impulsivity</strong> cluster.';
      } else if (autismPct > adhdPct + 10) {
        pattern = 'The signal in your answers sits mainly in the <strong>social communication and sensory</strong> cluster.';
      } else {
        pattern = 'The signal in your answers is spread fairly evenly across the clusters, without one clear pattern standing out.';
      }

      var result;
      if (peak >= 60 || (peak >= 45 && impact >= 2)) {
        result = {
          band: 'red', bandLabel: 'Assessment recommended',
          title: 'There is enough signal here to warrant a formal assessment.',
          summary: pattern + ' Combined with the impact you reported on daily life, this is the point at which we would advise a structured assessment rather than more waiting.',
          plain: 'High signal (ADHD cluster ' + adhdPct + '%, autism cluster ' + autismPct + '%, impact ' + impact + '/3) at age ' + AGE_LABEL[age] + '.',
          actions: [
            'Book a free 15-minute intake call. We will tell you honestly whether an assessment is the right spend, and which one.',
            'Ask your child\'s class teacher to write down what they observe — frequency, situations, what helps. Teacher input carries real weight in an assessment.',
            'Get hearing and vision checked if that has not been done in the last year. Both mimic these behaviours convincingly.',
            'Read the assessment guide below before you book anything, anywhere, so you know what you should be paying for.',
          ],
        };
      } else if (peak >= 35 || impact >= 2) {
        result = {
          band: 'amber', bandLabel: 'Worth a conversation',
          title: 'Some signal, but not yet a clear picture.',
          summary: pattern + ' At this level, the honest answer is that it could be an emerging difficulty or it could be developmentally normal for ' + AGE_LABEL[age] + '. What separates the two is how it looks across settings, and whether it is changing over time.',
          plain: 'Moderate signal (ADHD cluster ' + adhdPct + '%, autism cluster ' + autismPct + '%, impact ' + impact + '/3) at age ' + AGE_LABEL[age] + '.',
          actions: [
            'Keep a two-week behaviour diary — situation, what happened, how long it lasted. Patterns show up fast on paper.',
            'Ask the school whether they see the same behaviours. Difficulty in only one setting usually points somewhere other than ADHD or autism.',
            'Try the structured home strategies in the free guide below for four to six weeks.',
            'Take a free 15-minute call if it is not improving, or sooner if it is affecting your child\'s confidence.',
          ],
        };
      } else {
        result = {
          band: 'green', bandLabel: 'Low signal right now',
          title: 'Your answers do not show a strong ADHD or autism pattern.',
          summary: pattern + ' Behaviours at this level and this impact are within the range we would expect for ' + AGE_LABEL[age] + '. That does not dismiss your concern — it just means the likely explanation is somewhere else.',
          plain: 'Low signal (ADHD cluster ' + adhdPct + '%, autism cluster ' + autismPct + '%, impact ' + impact + '/3) at age ' + AGE_LABEL[age] + '.',
          actions: [
            'If something still feels off, look at sleep, screen time, anxiety and school stress first — they explain a large share of the concerns parents bring to us.',
            'Re-take this screener in three months if the behaviour changes or intensifies.',
            'Use the guide below to build the home routines that protect attention and emotional regulation.',
            'You are always welcome on a free 15-minute call, including just for reassurance.',
          ],
        };
      }

      result.score = peak;
      result.meters = meters;
      result.actionsTitle = 'Your next four steps';
      result.conditionTag = autismPct > adhdPct ? 'autism_asd' : 'adhd';
      return result;
    },

    offer: {
      title: 'Get your screener report + the ADHD & Autism Assessment Guide',
      subtitle: 'Your four cluster scores in writing, plus the guide we wish every parent had before booking an assessment anywhere.',
      bullets: [
        'What each assessment tool actually measures — ADOS-2, Conners, Vineland, WISC-V',
        'The questions to ask before you pay for any assessment',
        'A ready-to-send letter template for requesting school accommodations',
        'Home strategies for attention, transitions and sensory overload',
        'A free 15-minute intake call with our clinical team',
      ],
      button: 'Send me my report + free guide',
    },

    guide: {
      url: '/resources/guides/adhd-autism-next-steps.php',
      title: 'the Assessment Guide',
    },
  });
})();
</script>
</body>
</html>
