<!DOCTYPE html>
<html lang="en-IN" class="overflow-x-hidden">
<head>
<meta charset="utf-8"/>
<link href="/Favicon.png" rel="icon" type="image/svg+xml"/>
<meta content="Free 3-minute self-check giving four separate scores: worry, mood, body and sleep, and burnout. Private, instant, and paired with a free 7-Day Reset Plan." name="description"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="index, follow" name="robots"/>
<link href="https://embracelives.com/resources/adult-stress-check" rel="canonical"/>
<meta content="website" property="og:type"/>
<meta content="https://embracelives.com/resources/adult-stress-check" property="og:url"/>
<meta content="Free Stress, Anxiety &amp; Burnout Self-Check | eMbrace" property="og:title"/>
<meta content="Free 3-minute self-check giving four separate scores: worry, mood, body and sleep, and burnout. Private, instant, and paired with a free 7-Day Reset Plan." property="og:description"/>
<meta content="https://embracelives.com/og-image.png" property="og:image"/>
<meta content="eMbrace Lives" property="og:site_name"/>
<meta content="en_IN" property="og:locale"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Free Stress, Anxiety &amp; Burnout Self-Check | eMbrace" name="twitter:title"/>
<meta content="Free 3-minute self-check giving four separate scores: worry, mood, body and sleep, and burnout. Private, instant, and paired with a free 7-Day Reset Plan." name="twitter:description"/>
<meta content="https://embracelives.com/og-image.png" name="twitter:image"/>
<title>Free Stress, Anxiety &amp; Burnout Self-Check | eMbrace</title>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
<link href="https://unpkg.com" rel="preconnect" crossorigin />
<script src="https://unpkg.com/@phosphor-icons/web" defer></script>
<link href="/assets/index-B-kGA3UA.css" rel="stylesheet"/>
<link href="/assets/lead-magnets.css" rel="stylesheet"/>
<style>
  body, h1, h2, h3, h4, h5, h6, p, a, span, div, button, input { font-family: 'Outfit', sans-serif; }
</style>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "WebPage",
      "@id": "https://embracelives.com/resources/adult-stress-check#webpage",
      "url": "https://embracelives.com/resources/adult-stress-check",
      "name": "Free Stress, Anxiety & Burnout Self-Check | eMbrace",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "Free 3-minute self-check giving four separate scores: worry, mood, body and sleep, and burnout. Private, instant, and paired with a free 7-Day Reset Plan."
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
<body class="overflow-x-hidden">
<div id="root" class="overflow-x-hidden">
<?php include __DIR__ . '/../components/header.php'; ?>

<!-- Hero -->
<section class="lm-section" style="padding-bottom:2rem;background:linear-gradient(180deg,#fffaf2,#ffffff)">
  <div class="lm-blob lm-blob--b"></div>
  <div class="lm-wrap lm-wrap--narrow lm-center">
    <span class="lm-eyebrow" style="background:#fff3d9;color:#8a6100"><i class="ph-fill ph-heartbeat"></i> Free self-check</span>
    <h1 class="lm-h2">Stress, Anxiety &amp; Burnout Self-Check</h1>
    <p class="lm-sub">
      Seventeen questions about the last two weeks. You get four separate scores — worry, mood, body and
      sleep, and burnout — because "stressed" is a word that hides four very different problems with four
      very different fixes.
    </p>
    <div style="display:flex;flex-wrap:wrap;gap:.6rem;justify-content:center;margin-top:1.5rem">
      <span class="lm-eyebrow" style="background:#e3faf0;color:#1d7d59"><i class="ph-fill ph-clock"></i> 3 minutes</span>
      <span class="lm-eyebrow"><i class="ph-fill ph-lock-key"></i> Answers stay in your browser</span>
      <span class="lm-eyebrow" style="background:#ffe7ee;color:#b03163"><i class="ph-fill ph-users-three"></i> Used in our corporate wellness programmes</span>
    </div>
  </div>
</section>

<!-- Quiz -->
<section style="padding:0 1rem 3.5rem;background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <div id="lm-quiz"></div>
  </div>
</section>

<!-- Four scores -->
<section class="lm-section" style="background:linear-gradient(180deg,#f8faff,#ffffff)">
  <div class="lm-wrap">
    <div class="lm-center">
      <span class="lm-eyebrow">Why four scores, not one</span>
      <h2 class="lm-h2">Burnout and anxiety look identical from the outside. They are not.</h2>
      <p class="lm-sub">
        Burnout is depletion — you have been running a system at capacity for too long, and rest genuinely
        helps. Anxiety is anticipation — your threat system is firing ahead of events, and rest alone does
        very little. Give both the same advice and you will fix neither.
      </p>
    </div>
    <div class="lm-grid" style="grid-template-columns:repeat(auto-fit,minmax(15rem,1fr))">
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--neuro"><i class="ph-fill ph-wind"></i></div>
        <h3 class="lm-card__title">Worry &amp; anxiety</h3>
        <p class="lm-card__desc">Racing thoughts, anticipating the worst, restlessness, difficulty switching off.</p>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--child"><i class="ph-fill ph-cloud-rain"></i></div>
        <h3 class="lm-card__title">Mood &amp; motivation</h3>
        <p class="lm-card__desc">Low mood, loss of interest, self-criticism, feeling flat about things you used to enjoy.</p>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--adult"><i class="ph-fill ph-moon-stars"></i></div>
        <h3 class="lm-card__title">Body &amp; sleep</h3>
        <p class="lm-card__desc">Sleep quality, appetite, tension, headaches and the physical load stress leaves behind.</p>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--neuro"><i class="ph-fill ph-battery-low"></i></div>
        <h3 class="lm-card__title">Burnout &amp; capacity</h3>
        <p class="lm-card__desc">Exhaustion, cynicism about work, and the sense that your effort no longer produces results.</p>
      </div>
    </div>
  </div>
</section>

<!-- Support options -->
<section class="lm-section" style="background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <span class="lm-eyebrow">If you want support</span>
    <h2 class="lm-h2">What therapy at eMbrace looks like for adults</h2>
    <p class="lm-sub" style="margin-left:0">
      Sessions are with RCI-certified clinical psychologists, in English or Hindi, online or at our Vasant
      Kunj, Gurugram and Malviya Nagar centres. Most adults working on anxiety, low mood or burnout see the
      shape of the problem change within six to eight sessions of structured CBT — this is not open-ended
      talk therapy with no endpoint.
    </p>
    <div class="lm-actions" style="margin-top:1.75rem">
      <h4>Three ways people start</h4>
      <ol>
        <li><strong>Individual therapy.</strong> Structured, goal-led sessions for anxiety, depression, stress, grief, trauma or relationship difficulty. <a href="/individuals" style="color:#234394;font-weight:600">Individual therapy &rarr;</a></li>
        <li><strong>Couples work.</strong> When the pressure is showing up in the relationship rather than in you alone. <a href="/couples" style="color:#234394;font-weight:600">Couples therapy &rarr;</a></li>
        <li><strong>Through your employer.</strong> If your organisation runs an EAP or wellness programme with us, sessions may already be covered. <a href="/corporate" style="color:#234394;font-weight:600">Corporate wellness &rarr;</a></li>
      </ol>
    </div>
  </div>
</section>

<!-- Crisis support -->
<section class="lm-section" style="background:linear-gradient(180deg,#ffffff,#fffaf2)">
  <div class="lm-wrap lm-wrap--narrow">
    <div class="lm-guide__box lm-guide__box--warn" style="margin:0">
      <p><strong>If you are in crisis right now, please do not wait for an email.</strong></p>
      <p style="margin:.6rem 0 0">
        Tele-MANAS, the Government of India's 24×7 mental health helpline: <strong>14416</strong> or
        1-800-891-4416. AASRA: <strong>+91 98204 66726</strong>, 24 hours. iCall (TISS):
        <strong>+91 91529 87821</strong>, Monday to Saturday, 10am–8pm. If there is immediate danger to life,
        call <strong>112</strong> or go to your nearest emergency department.
      </p>
    </div>
  </div>
</section>

<!-- FAQ -->
<section class="lm-section" style="background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <div class="lm-center"><h2 class="lm-h2">Common questions</h2></div>
    <div style="margin-top:2rem;display:grid;gap:.85rem">
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">Is this the same as a clinical diagnosis?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">No. This is a structured self-reflection tool covering domains clinicians assess, but a diagnosis of an anxiety or depressive disorder requires a clinical interview, a history, and ruling out medical causes — thyroid issues, vitamin B12 and D deficiency, sleep apnoea and medication side effects all produce these symptoms.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">Will my employer find out if I take this?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">No. Even where eMbrace runs your organisation's wellness programme, individual responses and session content are confidential. Employers receive only anonymised, aggregate utilisation data — never names, never scores.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">I scored low but still feel awful. What now?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">Trust that, not the number. This check covers the last two weeks and four common domains; it does not cover trauma, grief, relationship distress, ADHD in adults, or the specific pressure of caring for someone else. Any of those is reason enough to talk to someone.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">How much does therapy cost, and how long does it take?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">We quote fees upfront on your first call — no surprises later. Most structured work for anxiety, low mood or burnout runs six to twelve sessions, usually weekly to start and then spaced out. You are told at the outset roughly what to expect, and it is reviewed with you as you go.</p>
      </details>
    </div>
  </div>
</section>

<?php include __DIR__ . '/../components/lead-magnet-cta.php'; ?>

<?php include __DIR__ . '/../components/footer.php'; ?>
</div>
<script src="/assets/lead-magnets.js"></script>
<script>
(function () {
  var FREQ = [
    { key: '1', label: 'Not at all', value: 0 },
    { key: '2', label: 'Several days', value: 1 },
    { key: '3', label: 'More than half the days', value: 2 },
    { key: '4', label: 'Nearly every day', value: 3 },
  ];

  var WORRY = 'Worry & anxiety';
  var MOOD = 'Mood & motivation';
  var BODY = 'Body & sleep';
  var BURN = 'Burnout & capacity';

  var ITEMS = [
    { d: WORRY, t: 'Worrying more than the situation deserves, and finding it hard to stop.' },
    { d: WORRY, t: 'Feeling on edge, restless, or unable to settle.' },
    { d: WORRY, t: 'Your mind jumping to the worst outcome before you have the facts.' },
    { d: WORRY, t: 'Avoiding calls, emails, or conversations because of the anxiety they bring.' },
    { d: MOOD, t: 'Feeling low, flat, or hopeless.' },
    { d: MOOD, t: 'Losing interest or pleasure in things you normally enjoy.' },
    { d: MOOD, t: 'Being unusually hard on yourself, or feeling like a failure.' },
    { d: MOOD, t: 'Withdrawing from people you would normally want to see.' },
    { d: BODY, t: 'Trouble falling asleep, staying asleep, or sleeping far too much.' },
    { d: BODY, t: 'Waking up tired no matter how long you slept.' },
    { d: BODY, t: 'Headaches, jaw or neck tension, stomach trouble, or a racing heart with no medical cause.' },
    { d: BODY, t: 'Eating noticeably more or less than usual.' },
    { d: BURN, t: 'Feeling emotionally drained by the end of a normal working day.' },
    { d: BURN, t: 'Feeling cynical or detached about work you used to care about.' },
    { d: BURN, t: 'Doubting whether your effort is making any difference.' },
    { d: BURN, t: 'Struggling to concentrate or make decisions you would usually make easily.' },
  ];

  var CONTEXT_STEP = {
    id: 'context',
    text: 'Which best describes you at the moment?',
    help: 'This shapes the recommendations, not the score.',
    options: [
      { key: '1', label: 'Working professional', value: 'professional' },
      { key: '2', label: 'Business owner or self-employed', value: 'founder' },
      { key: '3', label: 'Student or early career', value: 'student' },
      { key: '4', label: 'Parent or caregiver at home', value: 'caregiver' },
      { key: '5', label: 'None of these', value: 'other' },
    ],
  };

  var SAFETY_STEP = {
    id: 'safety',
    domain: 'Safety',
    text: 'Over the last two weeks, have you had thoughts that you would be better off not being here, or of hurting yourself?',
    help: 'You can answer honestly. Whatever you choose, you will see support options immediately and nothing is sent anywhere unless you ask for your report.',
    options: [
      { key: '1', label: 'Not at all', value: 0 },
      { key: '2', label: 'Several days', value: 1 },
      { key: '3', label: 'More than half the days', value: 2 },
      { key: '4', label: 'Nearly every day', value: 3 },
    ],
  };

  var CONTEXT_TIP = {
    professional: 'Protect one hard boundary in your calendar this week — a genuine lunch break, or a fixed logoff time — and treat it as an appointment you cannot move.',
    founder: 'Separate the two things running you down: the workload and the uncertainty. They need different responses, and founders usually treat both as "just push harder".',
    student: 'Sleep debt looks exactly like anxiety at your stage. Fix the sleep window for two weeks before you conclude anything about your mental health.',
    caregiver: 'Caregiver depletion is real and under-recognised. Our <a href="/parent-hub/caregiver-support" style="color:#234394;font-weight:600">caregiver support</a> resources were written for exactly this.',
    other: 'Pick the single domain that scored highest and work only on that for two weeks. Broad self-improvement plans fail; narrow ones do not.',
  };

  var steps = [CONTEXT_STEP];
  ITEMS.forEach(function (item, i) {
    steps.push({ id: 'q' + i, domain: item.d, text: item.t, options: FREQ });
  });
  steps.push(SAFETY_STEP);

  EmbraceLM.init({
    mount: '#lm-quiz',
    id: 'adult-stress-check',
    name: 'Adult Stress, Anxiety & Burnout Self-Check',
    minutes: 3,
    // Matches the appointment form's select values; interpret() sharpens the
    // condition to whichever domain scored highest.
    specialtyTag: 'clinical_psychologist',
    conditionTag: 'anxiety_stress',
    disclaimer: 'This self-check is educational and is not a diagnosis. Anxiety and depressive disorders are ' +
      'diagnosed by a clinician after a full interview, and several medical conditions produce identical ' +
      'symptoms. If you are in distress right now, call Tele-MANAS on 14416 (24×7) or our team on ' +
      '<a href="tel:+919971576800">+91 99715 76800</a>.',

    steps: steps,

    interpret: function (state) {
      var context = state.answers.context.value;
      var safety = state.answers.safety.value;
      var groups = {};
      groups[WORRY] = { score: 0, max: 0 };
      groups[MOOD] = { score: 0, max: 0 };
      groups[BODY] = { score: 0, max: 0 };
      groups[BURN] = { score: 0, max: 0 };
      var total = 0, max = 0;

      Object.keys(state.answers).forEach(function (key) {
        if (key === 'context' || key === 'safety') return;
        var a = state.answers[key];
        groups[a.domain].score += a.value;
        groups[a.domain].max += 3;
        total += a.value;
        max += 3;
      });

      function pct(g) { return Math.round((g.score / g.max) * 100); }
      function level(p) { return p >= 55 ? 'red' : (p >= 30 ? 'amber' : 'green'); }
      function levelLabel(p) { return p >= 55 ? 'High' : (p >= 30 ? 'Moderate' : 'Low'); }

      var notes = {};
      notes[WORRY] = 'Anticipation and threat. Responds to structured CBT work, not to rest alone.';
      notes[MOOD] = 'Low mood and lost interest. Behavioural activation is usually the first lever here.';
      notes[BODY] = 'The physical load. Sleep is the highest-yield fix and the one most people skip.';
      notes[BURN] = 'Depletion and cynicism. This one is about demand and recovery, not personal weakness.';

      var meters = [WORRY, MOOD, BODY, BURN].map(function (name) {
        var p = pct(groups[name]);
        return { label: name, pct: p, level: level(p), levelLabel: levelLabel(p), note: notes[name] };
      });

      var overall = Math.round((total / max) * 100);
      var highest = meters.slice().sort(function (a, b) { return b.pct - a.pct; })[0];

      var result;
      if (overall >= 55 || safety >= 1) {
        result = {
          band: 'red', bandLabel: 'Significant load',
          title: 'You are carrying more than most people can carry unsupported.',
          summary: 'Your answers point to a sustained level of distress across the last two weeks, with <strong>' + highest.label + '</strong> the heaviest domain. At this level, self-help alone tends to buy relief rather than change. Talking to a clinical psychologist is a proportionate response, not an overreaction.',
          plain: 'High load (' + overall + '% overall, highest: ' + highest.label + ' at ' + highest.pct + '%).',
          actions: [
            'Book a session with a clinical psychologist — or a free 15-minute call first if you want to know what you would be signing up for.',
            'See your GP to rule out thyroid, B12, vitamin D and sleep apnoea. These produce identical symptoms and are cheap to check.',
            'Tell one person in your life where you are. Isolation is what turns a difficult month into a difficult year.',
            'Start with the sleep window in the 7-day reset plan below — it is the change that makes every other change possible.',
          ],
        };
      } else if (overall >= 30) {
        result = {
          band: 'amber', bandLabel: 'Elevated stress',
          title: 'You are stretched, and it is showing in specific places.',
          summary: 'Your scores sit in the range where things are manageable but no longer comfortable, with <strong>' + highest.label + '</strong> carrying the most weight. This is the point where a structured two-week intervention usually works — and the point most people push past instead.',
          plain: 'Elevated (' + overall + '% overall, highest: ' + highest.label + ' at ' + highest.pct + '%).',
          actions: [
            'Work on the highest-scoring domain only, for two weeks. The reset plan below has a specific track for each one.',
            CONTEXT_TIP[context],
            'Re-take this check in two weeks. If nothing has moved, that is your signal to book a session.',
            'Consider four to six sessions of structured therapy — that is often the whole intervention at this level.',
          ],
        };
      } else {
        result = {
          band: 'green', bandLabel: 'Manageable range',
          title: 'Your load looks manageable at the moment.',
          summary: 'Nothing in your answers points to clinical-level distress in the last two weeks. Your highest domain is <strong>' + highest.label + '</strong>, which is worth keeping an eye on but is well within the normal range of a demanding life.',
          plain: 'Manageable (' + overall + '% overall, highest: ' + highest.label + ' at ' + highest.pct + '%).',
          actions: [
            'Use the reset plan below as maintenance — the habits are far easier to build now than during a crisis.',
            CONTEXT_TIP[context],
            'Re-check in three months, or sooner if something significant changes at work or at home.',
            'If you feel worse than this result suggests, believe yourself and talk to someone. A questionnaire does not know your life.',
          ],
        };
      }

      if (safety >= 1) {
        result.alert =
          '<p><strong>Before anything else.</strong> You told us you have had thoughts of not being here or of ' +
          'hurting yourself. Please talk to someone today — not eventually.</p>' +
          '<p style="margin:.6rem 0 0">Tele-MANAS (24×7, free): <strong>14416</strong> &nbsp;·&nbsp; ' +
          'AASRA (24×7): <strong>+91 98204 66726</strong> &nbsp;·&nbsp; ' +
          'eMbrace: <strong><a href="tel:+919971576800">+91 99715 76800</a></strong>. ' +
          'If you are in immediate danger, call <strong>112</strong> or go to the nearest emergency department. ' +
          'If you leave your number below, our clinical team will prioritise your call.</p>';
      }

      result.score = overall;
      result.meters = meters;
      result.actionsTitle = 'What we would do first';
      result.conditionTag = highest.label === MOOD ? 'depression' : 'anxiety_stress';
      return result;
    },

    offer: {
      title: 'Get your full report + the 7-Day Reset Plan',
      subtitle: 'Your four domain scores in writing, plus the structured week our psychologists give adults who are stretched but not yet in therapy.',
      bullets: [
        'A separate track for anxiety, low mood, sleep and burnout — you follow one, not all four',
        'Day-by-day actions that take under 20 minutes each',
        'The sleep window protocol that fixes most stress-related insomnia',
        'When self-help is enough, and the exact point at which it is not',
        'A free 15-minute call with a clinical psychologist if you want one',
      ],
      button: 'Send me my report + reset plan',
    },

    guide: {
      url: '/resources/guides/7-day-reset-plan',
      title: 'the 7-Day Reset Plan',
    },
  });
})();
</script>
</body>
</html>
