<!DOCTYPE html>
<html lang="en-IN" class="overflow-x-hidden">
<head>
<meta charset="utf-8"/>
<link href="/Favicon.png" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Free 2-minute milestone checker for ages 0-12, covering speech, motor, social and learning skills. Instant domain-by-domain result and a free parent guide." name="description"/>
<meta content="index, follow" name="robots"/>
<link href="https://embracelives.com/resources/child-milestone-checker" rel="canonical"/>
<meta content="website" property="og:type"/>
<meta content="https://embracelives.com/resources/child-milestone-checker" property="og:url"/>
<meta content="Free Child Milestone Checker (0-12) | eMbrace Delhi" property="og:title"/>
<meta content="Free 2-minute milestone checker for ages 0-12, covering speech, motor, social and learning skills. Instant domain-by-domain result and a free parent guide." property="og:description"/>
<meta content="https://embracelives.com/og-image.png" property="og:image"/>
<meta content="eMbrace Lives" property="og:site_name"/>
<meta content="en_IN" property="og:locale"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Free Child Milestone Checker (0-12) | eMbrace Delhi" name="twitter:title"/>
<meta content="Free 2-minute milestone checker for ages 0-12, covering speech, motor, social and learning skills. Instant domain-by-domain result and a free parent guide." name="twitter:description"/>
<meta content="https://embracelives.com/og-image.png" name="twitter:image"/>
<title>Free Child Milestone Checker (0-12) | eMbrace Delhi</title>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
<link href="https://unpkg.com" rel="preconnect" crossorigin />
<script src="https://unpkg.com/@phosphor-icons/web" defer></script>
<link href="/assets/index-B-kGA3UA.css" rel="stylesheet"/>
<link href="/assets/lead-magnets.css" rel="stylesheet"/>
<style>
  body, h1, h2, h3, h4, h5, h6, p, a, span, div, button, input { font-family: 'Outfit', sans-serif; }
</style>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "WebPage",
      "@id": "https://embracelives.com/resources/child-milestone-checker#webpage",
      "url": "https://embracelives.com/resources/child-milestone-checker",
      "name": "Free Child Milestone Checker (0-12) | eMbrace Delhi",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "Free 2-minute milestone checker for ages 0-12, covering speech, motor, social and learning skills. Instant domain-by-domain result and a free parent guide."
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
<body class="overflow-x-hidden">
<div id="root" class="overflow-x-hidden">
<?php include __DIR__ . '/../components/header.php'; ?>

<!-- Hero -->
<section class="lm-section" style="padding-bottom:2rem">
  <div class="lm-blob lm-blob--a"></div>
  <div class="lm-blob lm-blob--b"></div>
  <div class="lm-wrap lm-wrap--narrow lm-center">
    <span class="lm-eyebrow"><i class="ph-fill ph-gift"></i> Free parent tool</span>
    <h1 class="lm-h2">Is My Child on Track? Milestone Checker for Ages 0–12</h1>
    <p class="lm-sub">
      Eight quick questions, mapped to the developmental milestones our child psychologists use every day.
      You get an instant, domain-by-domain snapshot — speech, motor, social, play and learning — with no
      sign-up needed to see your result.
    </p>
    <div style="display:flex;flex-wrap:wrap;gap:.6rem;justify-content:center;margin-top:1.5rem">
      <span class="lm-eyebrow" style="background:#e3faf0;color:#1d7d59"><i class="ph-fill ph-clock"></i> 2 minutes</span>
      <span class="lm-eyebrow" style="background:#fff3d9;color:#8a6100"><i class="ph-fill ph-lock-key"></i> Private</span>
      <span class="lm-eyebrow" style="background:#ffe7ee;color:#b03163"><i class="ph-fill ph-first-aid-kit"></i> Built by RCI-certified clinicians</span>
    </div>
  </div>
</section>

<!-- Quiz -->
<section style="padding:0 1rem 3.5rem;background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <div id="lm-quiz"></div>
  </div>
</section>

<!-- What it covers -->
<section class="lm-section" style="background:linear-gradient(180deg,#f8faff,#ffffff)">
  <div class="lm-wrap">
    <div class="lm-center">
      <span class="lm-eyebrow">What the checker looks at</span>
      <h2 class="lm-h2">Five developmental domains, one snapshot</h2>
      <p class="lm-sub">
        Development is never a single line. A child can race ahead with movement and still need help with
        language. The checker reports each domain separately so you know where to look — and where not to worry.
      </p>
    </div>
    <div class="lm-grid" style="grid-template-columns:repeat(auto-fit,minmax(15rem,1fr))">
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--child"><i class="ph-fill ph-chat-teardrop-dots"></i></div>
        <h3 class="lm-card__title">Communication &amp; speech</h3>
        <p class="lm-card__desc">Babbling, first words, sentence length, clarity to strangers, and understanding of instructions.</p>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--neuro"><i class="ph-fill ph-person-simple-run"></i></div>
        <h3 class="lm-card__title">Motor skills</h3>
        <p class="lm-card__desc">Sitting, walking, running and climbing, alongside fine-motor work like pencil grip and buttons.</p>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--adult"><i class="ph-fill ph-users-three"></i></div>
        <h3 class="lm-card__title">Social &amp; emotional</h3>
        <p class="lm-card__desc">Eye contact, joint attention, friendships, separation, and how quickly your child recovers when upset.</p>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--child"><i class="ph-fill ph-puzzle-piece"></i></div>
        <h3 class="lm-card__title">Play &amp; learning</h3>
        <p class="lm-card__desc">Pretend play, imitation, attention span, reading and writing demands at school age.</p>
      </div>
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--neuro"><i class="ph-fill ph-house-line"></i></div>
        <h3 class="lm-card__title">Daily living &amp; behaviour</h3>
        <p class="lm-card__desc">Feeding, dressing, toileting, sleep, transitions, and meltdown frequency and intensity.</p>
      </div>
    </div>
  </div>
</section>

<!-- Why early matters -->
<section class="lm-section" style="background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <span class="lm-eyebrow">Why parents use this</span>
    <h2 class="lm-h2">"Wait and watch" is advice, not a plan</h2>
    <p class="lm-sub" style="margin-left:0">
      Most families who come to eMbrace tell us the same thing: they noticed something months — sometimes
      years — before anyone acted on it. The brain is most responsive to support in the early years, and the
      same difficulty usually takes fewer sessions to shift at three than it does at eight.
    </p>
    <div class="lm-actions" style="margin-top:1.75rem">
      <h4>What a result actually means</h4>
      <ol>
        <li><strong>On track</strong> — your child is meeting the expected pattern for their age. Keep an eye on it, re-check in six months.</li>
        <li><strong>Worth watching</strong> — one or two domains are emerging more slowly. Targeted home strategies often close the gap; a screening call tells you whether more is needed.</li>
        <li><strong>Worth a professional check-in</strong> — several skills are delayed relative to age. This is not a diagnosis, it is a reason to have one conversation with a clinician.</li>
      </ol>
    </div>
    <p class="lm-disclaimer" style="margin-top:1.5rem">
      This checker is an educational screening tool based on widely used developmental milestone frameworks.
      It cannot diagnose autism, ADHD, a speech-language disorder or a learning disability. Only a qualified
      clinician can, after a full assessment.
    </p>
  </div>
</section>

<!-- FAQ -->
<section class="lm-section" style="background:linear-gradient(180deg,#ffffff,#f4f7ff)">
  <div class="lm-wrap lm-wrap--narrow">
    <div class="lm-center"><h2 class="lm-h2">Questions parents ask us</h2></div>
    <div style="margin-top:2rem;display:grid;gap:.85rem">
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">My child is late in one area only. Should I worry?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">Uneven development is common and often resolves. What matters more is the size of the gap, whether it is widening, and whether it is affecting daily life — school, friendships, sleep, family routines. A single delayed domain with everything else on track usually calls for targeted strategies and a re-check in three to six months, not a full assessment.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">Does a low score mean my child has autism or ADHD?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">No. A screening tool can only flag that a conversation is worth having. Many children who screen low have a hearing issue, a language delay, or simply a late-blooming profile. Diagnosis in India requires a structured assessment by an RCI-certified clinical psychologist, usually alongside a developmental paediatrician — which is exactly what our team does at our Vasant Kunj, Gurugram and Malviya Nagar centres.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">My child is bilingual — does that change the milestones?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">Growing up with Hindi, English and a third home language does not cause a language delay. Count words across all languages your child uses, not just English. Bilingual children may mix languages and have a smaller vocabulary in each one individually, but their total vocabulary should track the milestones.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">What happens after I get my report?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">You get the report and the parent guide by email — yours to keep, print, or share with your paediatrician or school. If your result suggests a check-in, our intake team will offer a free 15-minute call to help you decide whether an assessment is warranted. There is no obligation and no hard sell.</p>
      </details>
      <details style="background:#fff;border:1px solid #e6e8f0;border-radius:1rem;padding:1.1rem 1.35rem">
        <summary style="cursor:pointer;font-weight:700;color:#16203c">Is my information private?</summary>
        <p style="margin:.8rem 0 0;color:#55596b;line-height:1.7">Your answers stay in your browser until you ask for the report. If you do, your details go only to eMbrace's clinical intake team and are handled under our <a href="/privacypolicy" style="color:#234394;font-weight:600">privacy policy</a>. We never sell or share your data.</p>
      </details>
    </div>
  </div>
</section>

<?php include __DIR__ . '/../components/lead-magnet-cta.php'; ?>

<?php include __DIR__ . '/../components/footer.php'; ?>
</div>
<script src="/assets/lead-magnets.js"></script>
<script>
(function () {
  var SCALE = [
    { key: 'A', label: 'Yes, consistently', value: 2 },
    { key: 'B', label: 'Sometimes — it is emerging', value: 1 },
    { key: 'C', label: 'Not yet', value: 0 },
  ];

  var BANDS = {
    infant: [
      { d: 'Communication', t: 'Turns towards sounds and voices, and quietens or brightens when you speak.' },
      { d: 'Communication', t: 'Babbles with varied sounds — "ba-ba", "da-da" — by around 9 months.' },
      { d: 'Social & emotional', t: 'Makes eye contact and smiles back at familiar faces.' },
      { d: 'Social & emotional', t: 'Responds to their own name by around 9 months.' },
      { d: 'Motor', t: 'Holds head steady, and sits without support by around 9 months.' },
      { d: 'Motor', t: 'Reaches for a toy, grasps it, and passes it from one hand to the other.' },
      { d: 'Play & learning', t: 'Enjoys back-and-forth games like peek-a-boo.' },
      { d: 'Play & learning', t: 'Follows your gaze or looks where you point.' },
    ],
    toddler: [
      { d: 'Communication', t: 'Uses at least 10–20 single words meaningfully by 18 months.' },
      { d: 'Communication', t: 'Points at things to show you, or to ask for them.' },
      { d: 'Communication', t: 'Follows a simple one-step instruction like "give me the ball".' },
      { d: 'Motor', t: 'Walks independently and climbs onto furniture.' },
      { d: 'Motor', t: 'Scribbles with a crayon and stacks two to four blocks.' },
      { d: 'Social & emotional', t: 'Brings objects to show you and checks your reaction.' },
      { d: 'Play & learning', t: 'Copies what you do — sweeping, talking on the phone, feeding a doll.' },
      { d: 'Daily living & behaviour', t: 'Settles with comfort from a familiar adult within a few minutes when upset.' },
    ],
    preschool: [
      { d: 'Communication', t: 'Joins two or three words together — "more juice", "mumma go park".' },
      { d: 'Communication', t: 'Familiar adults understand at least half of what your child says.' },
      { d: 'Communication', t: 'Follows a two-step instruction like "pick up your shoes and put them in the box".' },
      { d: 'Motor', t: 'Runs, kicks a ball, and walks up stairs holding the rail.' },
      { d: 'Motor', t: 'Turns book pages, uses a spoon, and helps with undressing.' },
      { d: 'Social & emotional', t: 'Notices other children and plays happily alongside them.' },
      { d: 'Play & learning', t: 'Shows pretend play — feeds a doll, makes engine sounds for a toy car.' },
      { d: 'Daily living & behaviour', t: 'Handles small changes in routine without a long meltdown.' },
    ],
    kinder: [
      { d: 'Communication', t: 'Speaks in full sentences that people outside the family can mostly understand.' },
      { d: 'Communication', t: 'Asks and answers "what", "where" and "why" questions.' },
      { d: 'Communication', t: 'Tells a simple story or recounts part of their day in order.' },
      { d: 'Motor', t: 'Hops, pedals a tricycle, and catches a large ball.' },
      { d: 'Motor', t: 'Draws a person with two to four body parts and holds a pencil with fingers, not a fist.' },
      { d: 'Social & emotional', t: 'Separates at school or playgroup without prolonged distress.' },
      { d: 'Play & learning', t: 'Takes turns and shares with a little adult prompting.' },
      { d: 'Daily living & behaviour', t: 'Manages daytime toileting independently and recovers from frustration within a few minutes.' },
    ],
    primary: [
      { d: 'Play & learning', t: 'Reads text at their class level and understands what they have read.' },
      { d: 'Play & learning', t: 'Writes legibly and finishes written classwork in a reasonable time.' },
      { d: 'Play & learning', t: 'Handles number work — addition and subtraction — at their grade level.' },
      { d: 'Attention & executive skills', t: 'Stays with a task for 15–20 minutes with occasional reminders.' },
      { d: 'Attention & executive skills', t: 'Follows school routines and multi-step instructions without constant supervision.' },
      { d: 'Social & emotional', t: 'Has at least one or two steady friendships.' },
      { d: 'Social & emotional', t: 'Talks about feelings and asks for help when upset.' },
      { d: 'Daily living & behaviour', t: 'Goes to school willingly, without frequent stomach aches, headaches or refusal.' },
    ],
    tween: [
      { d: 'Play & learning', t: 'Keeps up with the reading and writing demands of their class.' },
      { d: 'Attention & executive skills', t: 'Organises books, homework and deadlines with only occasional reminders.' },
      { d: 'Attention & executive skills', t: 'Sustains attention on homework for around 30 minutes.' },
      { d: 'Social & emotional', t: 'Maintains friendships and works through minor conflicts.' },
      { d: 'Social & emotional', t: 'Names worries out loud rather than only showing them as headaches or stomach aches.' },
      { d: 'Social & emotional', t: 'Mood is broadly steady — no persistent sadness or irritability lasting more than two weeks.' },
      { d: 'Daily living & behaviour', t: 'Sleeps 9–11 hours and wakes reasonably rested on most days.' },
      { d: 'Daily living & behaviour', t: 'Accepts screen-time limits without extreme conflict.' },
    ],
  };

  var AGE_STEP = {
    id: 'age_band',
    resets: true,
    text: 'How old is your child?',
    help: 'Milestones are age-specific, so the questions change based on your answer. For premature babies under two, use the corrected age.',
    options: [
      { key: '1', label: '0–12 months', value: 'infant' },
      { key: '2', label: '1–2 years', value: 'toddler' },
      { key: '3', label: '2–3 years', value: 'preschool' },
      { key: '4', label: '3–5 years', value: 'kinder' },
      { key: '5', label: '6–8 years', value: 'primary' },
      { key: '6', label: '9–12 years', value: 'tween' },
    ],
  };

  var AGE_LABEL = {
    infant: '0–12 months', toddler: '1–2 years', preschool: '2–3 years',
    kinder: '3–5 years', primary: '6–8 years', tween: '9–12 years',
  };

  EmbraceLM.init({
    mount: '#lm-quiz',
    id: 'child-milestone-checker',
    name: 'Child Development Milestone Checker',
    minutes: 2,
    estimatedSteps: 9,
    // Matches the appointment form's select values, so the lead lands in the
    // shared inbox already categorised.
    specialtyTag: 'child_psychologist',
    conditionTag: 'child_adolescent',

    buildSteps: function (state) {
      var steps = [AGE_STEP];
      var band = state.answers.age_band && state.answers.age_band.value;
      if (!band) return steps;
      BANDS[band].forEach(function (q, i) {
        steps.push({ id: band + '_' + i, domain: q.d, text: q.t, options: SCALE });
      });
      return steps;
    },

    interpret: function (state) {
      var band = state.answers.age_band.value;
      var domains = {};
      var total = 0, max = 0;

      Object.keys(state.answers).forEach(function (key) {
        if (key === 'age_band') return;
        var a = state.answers[key];
        domains[a.domain] = domains[a.domain] || { score: 0, max: 0, missed: [] };
        domains[a.domain].score += a.value;
        domains[a.domain].max += 2;
        if (a.value < 2) domains[a.domain].missed.push(a.text);
        total += a.value;
        max += 2;
      });

      var pct = Math.round((total / max) * 100);
      var meters = Object.keys(domains).map(function (name) {
        var d = domains[name];
        var p = Math.round((d.score / d.max) * 100);
        var level = p >= 85 ? 'green' : (p >= 55 ? 'amber' : 'red');
        return {
          label: name,
          pct: p,
          level: level,
          levelLabel: level === 'green' ? 'On track' : (level === 'amber' ? 'Emerging' : 'Needs a look'),
          note: level === 'green'
            ? 'Skills here are tracking as expected for ' + AGE_LABEL[band] + '.'
            : d.missed.length + ' of ' + (d.max / 2) + (d.max === 2 ? ' skill' : ' skills') +
              ' in this area ' + (d.missed.length === 1 ? 'is' : 'are') + ' not yet consistent.',
        };
      });

      var result;
      if (pct >= 85) {
        result = {
          band: 'green', bandLabel: 'On track',
          title: 'Your child is meeting the milestones we would expect at ' + AGE_LABEL[band] + '.',
          summary: 'Nothing in your answers suggests a developmental concern right now. Development is uneven by nature, so the useful thing is to keep a light eye on the areas that scored lower and re-check in about six months.',
          plain: 'On track for ' + AGE_LABEL[band] + ' (' + pct + '%).',
          actions: [
            'Keep the checker result and repeat it in six months — a widening gap matters far more than a single snapshot.',
            'Use the free parent guide below for age-specific play and language activities that build on where your child already is.',
            'If a teacher or grandparent raises a concern that you have not seen at home, it is still worth a 15-minute call.',
          ],
        };
      } else if (pct >= 60) {
        result = {
          band: 'amber', bandLabel: 'A few areas worth watching',
          title: 'Most milestones are in place, but some skills are still emerging.',
          summary: 'This pattern is common and often resolves with targeted support at home. What we look at next is whether the gap is closing over the coming months, and whether it is affecting school, friendships or family routines.',
          plain: 'Some emerging areas at ' + AGE_LABEL[band] + ' (' + pct + '%).',
          actions: [
            'Focus on the one or two domains marked "Emerging" above rather than on everything at once.',
            'Download the parent guide for the specific home strategies that match those domains.',
            'Book a free 15-minute screening call so a clinician can tell you whether a formal assessment is warranted — most families in this band do not need one immediately.',
            'Re-take this checker in three months and compare.',
          ],
        };
      } else {
        result = {
          band: 'red', bandLabel: 'Worth a professional check-in',
          title: 'Several skills are behind what we would expect at ' + AGE_LABEL[band] + '.',
          summary: 'This is not a diagnosis and it does not predict your child\'s future. It does mean one conversation with a clinician is worth having sooner rather than later — hearing, language, attention and sensory factors all produce this pattern, and they respond very differently to support.',
          plain: 'Multiple delayed areas at ' + AGE_LABEL[band] + ' (' + pct + '%).',
          actions: [
            'Book a free 15-minute screening call with our intake team — the fastest way to know what, if anything, to do next.',
            'Ask your paediatrician for a hearing check if speech or response to name scored low. Undetected hearing loss mimics several developmental delays.',
            'Bring the report below to that appointment — it saves the first ten minutes of every consultation.',
            'Start the home strategies in the parent guide today; they help regardless of what the assessment eventually shows.',
          ],
        };
      }

      result.score = pct;
      result.meters = meters;
      result.actionsTitle = 'What we suggest next';
      return result;
    },

    offer: {
      title: 'Get your full milestone report + The Delhi Parent\'s Milestone Guide',
      subtitle: 'A written breakdown of your result, plus our 0–12 milestone guide — the same reference our clinicians hand parents at their first appointment.',
      bullets: [
        'Age-by-age milestone tables you can print and stick on the fridge',
        'The red flags that genuinely warrant an assessment (and the ones that do not)',
        'Home activities for speech, motor, play and attention',
        'A free 15-minute screening call if your result suggests one',
      ],
      button: 'Send me my report + free guide',
    },

    guide: {
      url: '/resources/guides/child-milestone-guide.php',
      title: 'the Milestone Guide',
    },
  });
})();
</script>
</body>
</html>
