<!DOCTYPE html>
<html lang="en-IN" class="overflow-x-hidden">
<head>
<meta charset="utf-8"/>
<link href="/Favicon.png" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Three free clinician-built screeners: child milestones, ADHD and autism early signs, and adult stress and burnout. Instant results, no sign-up needed." name="description"/>
<meta content="index, follow" name="robots"/>
<link href="https://embracelives.com/resources" rel="canonical"/>
<meta content="website" property="og:type"/>
<meta content="https://embracelives.com/resources" property="og:url"/>
<meta content="Free Mental Health Tools &amp; Screeners | eMbrace Delhi" property="og:title"/>
<meta content="Three free clinician-built screeners: child milestones, ADHD and autism early signs, and adult stress and burnout. Instant results, no sign-up needed." property="og:description"/>
<meta content="https://embracelives.com/og-image.png" property="og:image"/>
<meta content="eMbrace Lives" property="og:site_name"/>
<meta content="en_IN" property="og:locale"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Free Mental Health Tools &amp; Screeners | eMbrace Delhi" name="twitter:title"/>
<meta content="Three free clinician-built screeners: child milestones, ADHD and autism early signs, and adult stress and burnout. Instant results, no sign-up needed." name="twitter:description"/>
<meta content="https://embracelives.com/og-image.png" name="twitter:image"/>
<title>Free Mental Health Tools &amp; Screeners | eMbrace Delhi</title>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
<link href="https://unpkg.com" rel="preconnect" crossorigin />
<script src="https://unpkg.com/@phosphor-icons/web" defer></script>
<link href="/assets/index-B-kGA3UA.css" rel="stylesheet"/>
<link href="/assets/lead-magnets.css" rel="stylesheet"/>
<style>
  body, h1, h2, h3, h4, h5, h6, p, a, span, div, button, input { font-family: 'Outfit', sans-serif; }
</style>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "WebPage",
      "@id": "https://embracelives.com/resources#webpage",
      "url": "https://embracelives.com/resources",
      "name": "Free Mental Health Tools & Screeners | eMbrace Delhi",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "Three free clinician-built screeners: child milestones, ADHD and autism early signs, and adult stress and burnout. Instant results, no sign-up needed."
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
<body class="overflow-x-hidden">
<div id="root" class="overflow-x-hidden">
<?php include __DIR__ . '/../components/header.php'; ?>

<section class="lm-section">
  <div class="lm-blob lm-blob--a"></div>
  <div class="lm-blob lm-blob--c"></div>
  <div class="lm-wrap">
    <div class="lm-center">
      <span class="lm-eyebrow"><i class="ph-fill ph-gift"></i> Free, no sign-up to see results</span>
      <h1 class="lm-h2">Free tools from our clinical team</h1>
      <p class="lm-sub">
        Three screeners built by the psychologists who run our assessments — the same domains, the same
        thresholds, the same honesty about what a questionnaire can and cannot tell you. Answer, see your
        result immediately, and get a written report plus a full guide if you want one.
      </p>
    </div>

    <div class="lm-grid">
      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--child"><i class="ph-fill ph-baby"></i></div>
        <span class="lm-card__tag">For parents &middot; 0–12 years</span>
        <h2 class="lm-card__title">Child Development Milestone Checker</h2>
        <p class="lm-card__desc">
          "Is my child on track?" — answered domain by domain against the milestones our child psychologists
          use, with an age-specific question set.
        </p>
        <ul class="lm-card__list">
          <li>Speech, motor, social, play and behaviour</li>
          <li>Age-specific — six separate question sets</li>
          <li>Free milestone &amp; early-support guide included</li>
        </ul>
        <div class="lm-card__foot">
          <a class="lm-btn lm-btn--primary lm-btn--wide" href="/resources/child-milestone-checker"
             data-lm-cta="child-milestone-checker" data-lm-placement="resources_hub">Start the 2-minute check</a>
          <p class="lm-card__meta">2 minutes &middot; 8 questions &middot; instant result</p>
        </div>
      </div>

      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--neuro"><i class="ph-fill ph-brain"></i></div>
        <span class="lm-card__tag">For parents &middot; 2–18 years</span>
        <h2 class="lm-card__title">ADHD &amp; Autism Early-Signs Screener</h2>
        <p class="lm-card__desc">
          Four behaviour clusters profiled separately, weighted by how much daily life is affected — and a
          straight answer on whether an assessment is worth booking.
        </p>
        <ul class="lm-card__list">
          <li>Attention, impulsivity, social communication, sensory</li>
          <li>Explains what ADOS-2, Conners and WISC-V measure</li>
          <li>Includes a school accommodations letter template</li>
        </ul>
        <div class="lm-card__foot">
          <a class="lm-btn lm-btn--primary lm-btn--wide" href="/resources/adhd-autism-screener"
             data-lm-cta="adhd-autism-screener" data-lm-placement="resources_hub">Start the 3-minute screener</a>
          <p class="lm-card__meta">3 minutes &middot; 17 questions &middot; instant result</p>
        </div>
      </div>

      <div class="lm-card">
        <div class="lm-card__icon lm-card__icon--adult"><i class="ph-fill ph-heartbeat"></i></div>
        <span class="lm-card__tag">For adults &middot; 18+</span>
        <h2 class="lm-card__title">Stress, Anxiety &amp; Burnout Self-Check</h2>
        <p class="lm-card__desc">
          Four separate scores instead of one vague verdict, because burnout and anxiety look identical from
          the outside and need completely different responses.
        </p>
        <ul class="lm-card__list">
          <li>Worry, mood, body and sleep, burnout</li>
          <li>Free 7-Day Reset Plan with a track for each</li>
          <li>Confidential — even under employer programmes</li>
        </ul>
        <div class="lm-card__foot">
          <a class="lm-btn lm-btn--primary lm-btn--wide" href="/resources/adult-stress-check"
             data-lm-cta="adult-stress-check" data-lm-placement="resources_hub">Start the 3-minute check</a>
          <p class="lm-card__meta">3 minutes &middot; 17 questions &middot; instant result</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="lm-section" style="background:#fff">
  <div class="lm-wrap lm-wrap--narrow">
    <span class="lm-eyebrow">How we built these</span>
    <h2 class="lm-h2">Screeners we would be comfortable handing a patient</h2>
    <p class="lm-sub" style="margin-left:0">
      Every item maps to a domain our clinicians assess formally. The thresholds are deliberately
      conservative — we would rather tell you a result is unclear than manufacture alarm to fill a diary.
      Where the honest answer is "this looks fine, come back in three months", that is what the tool says.
    </p>
    <div class="lm-actions" style="margin-top:1.75rem">
      <h4>Three commitments</h4>
      <ol>
        <li><strong>Your result is never held hostage.</strong> You see it in full before any form appears. The email is for the written report and the guide, not for the answer.</li>
        <li><strong>No manufactured urgency.</strong> A green result says so plainly, and we will tell you on the phone if you do not need us.</li>
        <li><strong>Your data stays with the clinical team.</strong> Held under our <a href="/privacypolicy" style="color:#234394;font-weight:600">privacy policy</a>, never sold, never shared with third parties. Unsubscribe in one click.</li>
      </ol>
    </div>
  </div>
</section>

<?php include __DIR__ . '/../components/lead-magnet-cta.php'; ?>

<?php include __DIR__ . '/../components/footer.php'; ?>
</div>
<script src="/assets/lead-magnets.js"></script>
</body>
</html>
