<?php
require_once __DIR__.'/../components/publish-gate.php'; embrace_require_published('2026-10-08');
$article=['date'=>'2026-10-08','slug'=>'adhd-and-sleep-in-children','tag'=>'ADHD','category'=>'ADHD','breadcrumb'=>'ADHD and Sleep','meta_title'=>'ADHD and Sleep in Children: Why Bedtime Is So Hard','description'=>'Understand ADHD and sleep in children, why bedtime can become a battle, what else may disrupt sleep, and practical steps families can discuss with a clinician.','h1'=>'ADHD and Sleep Problems: Why Bedtime Is Often the Hardest Part of the Day','dek'=>'Bedtime combines stopping, switching, waiting and settling, precisely the tasks many children with ADHD find hardest.','body'=><<<'HTML'
<p class="text-lg text-gray-700 leading-relaxed font-light">ADHD and sleep in children can interact in both directions. ADHD traits may make the transition to bed difficult, while insufficient or disrupted sleep can worsen attention, irritability and impulse control the next day. A bedtime battle is therefore worth understanding, not simply punishing.</p>
<h2>Why bedtime places heavy demands on executive skills</h2><p>A child must stop a rewarding activity, remember several steps, estimate time, resist distractions and shift into a low-stimulation state. Difficulties with inhibition, time awareness and transitions can turn each step into negotiation.</p><p>This does not mean every refusal is involuntary or that boundaries are unnecessary. It means routines work better when the environment carries some of the planning load.</p>
<h2>ADHD is not the only possible cause</h2><p>Anxiety, restless legs, sleep-disordered breathing, inconsistent schedules, pain, screen use and other conditions can disturb sleep. Medication timing can matter for some children, but parents should not change prescribed medication without speaking with the prescriber.</p><p>Snoring, pauses in breathing, unusual movements, persistent daytime sleepiness or a major change in sleep deserves medical discussion.</p>
<h2>Build a routine the child can follow</h2><ul><li><strong>Anchor waking time:</strong> a reasonably consistent morning supports the sleep-wake rhythm.</li><li><strong>Externalise the sequence:</strong> use a short visual list for toilet, teeth, clothes, story and lights out.</li><li><strong>Warn before transitions:</strong> give predictable countdowns before a preferred activity ends.</li><li><strong>Reduce decisions:</strong> prepare clothes and choose the story before the child is exhausted.</li><li><strong>Lower stimulation gradually:</strong> dim lights and move from active to calmer tasks.</li></ul>
<h2>Track sleep before changing everything</h2><p>For two weeks, record bedtime, estimated sleep onset, waking, night waking, naps, medication timing and notable events. A diary helps separate a delayed schedule from repeated waking or anxiety around the routine.</p>
<h2>What not to do</h2><p>Avoid adding a new strategy every night. Inconsistency makes it harder to see what helps. Avoid using the bedroom as punishment, and do not give supplements or sleep medicines without medical guidance. Even products available without prescription can have risks or interact with other treatment.</p>
<div class="callout-card"><h3>Make bedtime boringly predictable</h3><p>The goal is not a perfect evening. It is the same small sequence, in the same order, with fewer verbal reminders and fewer opportunities for the routine to expand.</p></div>
<h2>When to ask for help</h2><p>Seek professional advice when sleep problems persist, affect daytime functioning, create safety concerns or exhaust the family despite a consistent routine. Assessment should consider sleep itself rather than assuming ADHD explains everything. Learn more about <a href="/adhd/adhd-in-children">ADHD in children</a>.</p>
HTML,
'faqs'=>[['Can lack of sleep look like ADHD?','Yes. Insufficient or disrupted sleep can cause inattention, irritability and impulsive behaviour. A thorough ADHD evaluation considers sleep and other possible explanations.'],['Should children with ADHD take melatonin?','Do not start melatonin without medical guidance. A clinician should first review sleep habits, health conditions and medicines, then discuss expected benefits, timing and risks.'],['Why does my child become energetic at bedtime?','Overtiredness, stimulation, transition difficulty or a delayed sleep schedule may look like renewed energy. Track the pattern and discuss persistent difficulties with a clinician.'],['How long should a bedtime routine be?','There is no universal length. Keep it short enough to repeat consistently, with a clear sequence and calm ending that suits your child&rsquo;s developmental needs.']],
'cta_title'=>'Look at the whole ADHD picture','cta_text'=>'Explore assessment and support that considers sleep, learning, home routines and school functioning together.','cta_url'=>'/adhd/adhd-in-children','cta_label'=>'Explore Childhood ADHD Support']; require __DIR__.'/../components/scheduled-blog-renderer.php';

