<?php require_once __DIR__.'/../components/publish-gate.php'; embrace_require_published('2026-11-12');
$article=['date'=>'2026-11-12','slug'=>'sensory-sensitivity-in-children','tag'=>'Occupational Therapy','category'=>'Occupational Therapy & Sensory Processing','breadcrumb'=>'Sensory Sensitivity in Children','meta_title'=>'Sensory Sensitivity in Children: Clothes, Sounds and Touch','description'=>'Understand sensory sensitivity in children, why ordinary clothes, sounds or textures may feel overwhelming, and what can make daily routines more manageable.','h1'=>'Why Does My Child Avoid Certain Textures, Sounds, or Clothes?','dek'=>'A routine sensation can be uncomfortable or painful to one child even when everyone else barely notices it.','body'=><<<'HTML'
<p class="text-lg text-gray-700 leading-relaxed font-light">Sensory sensitivity in children means the nervous system responds strongly to particular input. Clothing seams, a mixer, toothpaste or light touch may feel far more intense than an adult expects. The child&rsquo;s distress is real even when the sensation seems ordinary.</p>
<h2>Why mornings can unravel</h2><p>A morning combines sound, touch, smell, time pressure, transitions and social demands. An itchy uniform, hair brushing and a hurried instruction can accumulate until the final small demand triggers a large response.</p>
<h2>Notice the sensory pattern</h2><ul><li><strong>Touch:</strong> avoiding labels, socks, hair care, messy play or unexpected contact.</li><li><strong>Sound:</strong> covering ears around appliances, traffic, assemblies or crowded rooms.</li><li><strong>Taste and smell:</strong> gagging, avoiding mixed textures or reacting to cooking smells.</li><li><strong>Visual input:</strong> distress under bright light or in cluttered spaces.</li><li><strong>Movement:</strong> fear of swings, escalators or feet leaving the ground.</li></ul>
<h2>Adjust the routine without making life smaller</h2><p>Offer tolerable clothing choices, remove labels, prepare items the night before and allow extra transition time. Warn before loud sounds and create a quiet recovery option. The goal is participation with manageable input, not forcing tolerance during distress.</p>
<h2>Respond to overload first</h2><p>Reduce language and demands, move to a calmer place and protect safety. Discuss what happened after regulation returns. Reasoning or consequences during overload rarely teach the intended skill.</p>
<h2>When does sensitivity need assessment?</h2><p>Seek advice when sensory responses repeatedly prevent dressing, eating, sleeping, attending school, playing or joining family activities. Sudden changes or possible pain need medical review. An OT connects sensory observations with functional participation rather than treating a checklist score alone.</p>
<p>Explore support for <a href="/occupational-therapy/sensory-avoidance">sensory avoidance and daily routines</a>.</p>
HTML,'faqs'=>[['Is sensory sensitivity the same as autism?','No. Sensory differences may occur with autism and other developmental profiles or on their own. Autism diagnosis requires a broader pattern beyond sensory responses.'],['Should I make my child tolerate uncomfortable clothes?','Forcing exposure during distress can increase fear. Start with workable clothing, identify specific triggers and seek professional guidance when sensitivity restricts daily participation.'],['Why can my child cope one day but not another?','Sensory tolerance changes with sleep, illness, hunger, stress, predictability and accumulated demands. Variation does not mean the child is inventing or controlling the response.'],['Can occupational therapy help sensory sensitivity?','An occupational therapist can assess how sensory responses affect daily activities and develop individualised environmental adjustments and skill-building strategies tied to meaningful participation.']],
'cta_title'=>'Make daily routines more manageable','cta_text'=>'Explore occupational therapy support based on your child&rsquo;s individual sensory pattern and participation needs.','cta_url'=>'/occupational-therapy/sensory-avoidance','cta_label'=>'Explore Sensory Avoidance Support']; require __DIR__.'/../components/scheduled-blog-renderer.php';
