<!DOCTYPE html>
<html lang="en-IN">
<head>
<meta charset="utf-8"/>
<link href="/Favicon.png" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="noindex, nofollow" name="robots"/>
<meta content="The 7-Day Reset Plan — a structured week for adults dealing with stress, anxiety, low mood or burnout, from eMbrace's clinical psychologists in Delhi." name="description"/>
<title>The 7-Day Reset Plan | eMbrace</title>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
<link href="/assets/lead-magnets.css" rel="stylesheet"/>
<style>body { margin: 0; background: #fff; }</style>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "WebPage",
      "@id": "https://embracelives.com/resources/guides/7-day-reset-plan#webpage",
      "url": "https://embracelives.com/resources/guides/7-day-reset-plan",
      "name": "The 7-Day Reset Plan | eMbrace",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "The 7-Day Reset Plan — a structured week for adults dealing with stress, anxiety, low mood or burnout, from eMbrace's clinical psychologists in Delhi."
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
<body>

<div class="lm-guide__bar lm-noprint">
  <p>Your free plan — yours to keep, print and share.</p>
  <div style="display:flex;gap:.6rem;flex-wrap:wrap">
    <button class="lm-btn lm-btn--gold" style="padding:.5rem 1.1rem;font-size:.85rem" onclick="window.print()">Save as PDF / Print</button>
    <a class="lm-btn lm-btn--ghost" style="padding:.5rem 1.1rem;font-size:.85rem" href="/appointment.php">Book a session</a>
  </div>
</div>

<article class="lm-guide">

  <div class="lm-guide__brand">
    <img src="/assets/Logo-DrHvIBUF.svg" alt="eMbrace"/>
    <span>eMbrace &middot; Psychology &amp; mental health care &middot; Delhi NCR</span>
  </div>

  <h1>The 7-Day Reset Plan</h1>
  <p class="lm-guide__lede">
    One week, one track, under 20 minutes a day. Built for adults who are stretched but not yet in therapy —
    and honest about the point at which a plan like this is not enough.
  </p>

  <div class="lm-guide__box">
    <p><strong>Pick one track.</strong> Look at your self-check result and choose the domain that scored
    highest. Work on that one only. Plans that try to fix worry, mood, sleep and burnout simultaneously fail
    in about four days — this is the most common reason self-help does not stick.</p>
  </div>

  <h2>The daily spine — all four tracks</h2>
  <p>Do these three things every day regardless of your track. Everything else is track-specific.</p>
  <table>
    <tr><th style="width:26%">Anchor</th><th>What it is</th></tr>
    <tr><td><strong>Fixed wake time</strong></td><td>Same time every day including the weekend, within 30 minutes. Wake time — not bedtime — is what stabilises the body clock, and it is the lever almost everyone skips.</td></tr>
    <tr><td><strong>Ten minutes of daylight</strong></td><td>Outdoors, within an hour of waking. Balcony counts. This does more for mood and sleep than any app.</td></tr>
    <tr><td><strong>One line at night</strong></td><td>Write one sentence: what took energy today, and what returned some. Seven lines is enough data to see your own pattern by Sunday.</td></tr>
  </table>

  <h2>Track A — Worry &amp; anxiety</h2>
  <table>
    <tr><th style="width:14%">Day</th><th>Action</th></tr>
    <tr><td>Day 1</td><td><strong>Name the loop.</strong> Write down the worry in one sentence, then answer: is this a problem I can act on, or a fear I am rehearsing? Only the first kind deserves planning time.</td></tr>
    <tr><td>Day 2</td><td><strong>Worry window.</strong> Book 15 minutes at a fixed time to worry deliberately. Outside it, note the thought and postpone it to the window. This feels artificial and works anyway.</td></tr>
    <tr><td>Day 3</td><td><strong>Slow the exhale.</strong> Four seconds in, six to eight out, for two minutes, three times today. A longer exhale is the fastest physiological brake you own.</td></tr>
    <tr><td>Day 4</td><td><strong>Do one avoided thing.</strong> The smallest item on your avoidance list — a call, an email, a message. Avoidance is what converts anxiety from an episode into a habit.</td></tr>
    <tr><td>Day 5</td><td><strong>Check the forecast.</strong> Write your predicted catastrophe, then what actually happened. Do this daily for a month and the loop starts to lose its authority.</td></tr>
    <tr><td>Day 6</td><td><strong>Cut the inputs.</strong> No news or work email for 90 minutes before bed. Note what happens to sleep onset.</td></tr>
    <tr><td>Day 7</td><td><strong>Review.</strong> Which of the six actually shifted something? Keep two, drop the rest, and run them for a month.</td></tr>
  </table>

  <h2>Track B — Mood &amp; motivation</h2>
  <table>
    <tr><th style="width:14%">Day</th><th>Action</th></tr>
    <tr><td>Day 1</td><td><strong>Act first, feel second.</strong> Low mood removes motivation before it removes capability. Pick one small activity you used to enjoy and schedule it for tomorrow — waiting to feel like it is how the trap holds.</td></tr>
    <tr><td>Day 2</td><td><strong>Do it, badly.</strong> Ten minutes counts. Note your mood before and after out of 10.</td></tr>
    <tr><td>Day 3</td><td><strong>One human.</strong> Contact one person — a call, not a text. Withdrawal deepens low mood faster than almost anything else.</td></tr>
    <tr><td>Day 4</td><td><strong>Move your body for 20 minutes.</strong> A walk qualifies. Intensity is not the point; regularity is.</td></tr>
    <tr><td>Day 5</td><td><strong>Catch the harshest sentence</strong> you said to yourself today and write what you would say to a friend in the same position. The gap between the two is the target of therapy.</td></tr>
    <tr><td>Day 6</td><td><strong>One thing you did.</strong> Write it down, however small. Depression erases the record of your own effort.</td></tr>
    <tr><td>Day 7</td><td><strong>Review.</strong> Compare mood scores from Day 2 onwards. If nothing has moved at all this week, treat that as information, not failure — see the last section.</td></tr>
  </table>

  <div class="lm-guide__page"></div>

  <h2>Track C — Body &amp; sleep</h2>
  <table>
    <tr><th style="width:14%">Day</th><th>Action</th></tr>
    <tr><td>Day 1</td><td><strong>Set the window.</strong> Choose a fixed wake time and a bedtime seven and a half hours earlier. Do not move the wake time for seven days, whatever the night was like.</td></tr>
    <tr><td>Day 2</td><td><strong>Bed is for sleep.</strong> No laptop, no scrolling, no work calls in bed. If you are awake more than 20 minutes, get up, sit somewhere dim, return when sleepy.</td></tr>
    <tr><td>Day 3</td><td><strong>Caffeine curfew — 2pm.</strong> Caffeine has a half-life of around five to six hours; a 5pm coffee is still working at midnight.</td></tr>
    <tr><td>Day 4</td><td><strong>Empty the head before bed.</strong> Five minutes, on paper: tomorrow's list and anything unresolved. Rumination at 1am is usually unprocessed admin.</td></tr>
    <tr><td>Day 5</td><td><strong>Release the tension.</strong> Tense and release each muscle group from feet to jaw, 10 minutes. Jaw and shoulders hold more than people expect.</td></tr>
    <tr><td>Day 6</td><td><strong>Drop the alcohol.</strong> It shortens sleep onset and wrecks the second half of the night. One week off is a fair test.</td></tr>
    <tr><td>Day 7</td><td><strong>Review.</strong> Sleep quality usually shifts on days five to seven, not day two. If you snore heavily, wake gasping, or feel unrefreshed after eight hours, ask your GP about sleep apnoea — no amount of sleep hygiene fixes that.</td></tr>
  </table>

  <h2>Track D — Burnout &amp; capacity</h2>
  <table>
    <tr><th style="width:14%">Day</th><th>Action</th></tr>
    <tr><td>Day 1</td><td><strong>Separate the two.</strong> Burnout is demand minus recovery. List your demands in one column and your genuine recovery in the other. Most people discover the second column is empty, not that the first is too long.</td></tr>
    <tr><td>Day 2</td><td><strong>Reclaim one boundary.</strong> A real lunch break away from the screen, or a hard logoff time. One, held all week, beats five aspirational ones.</td></tr>
    <tr><td>Day 3</td><td><strong>Find the values gap.</strong> Write what you thought this work was for, and what you spend your days actually doing. Cynicism is usually the gap between the two, not a character flaw.</td></tr>
    <tr><td>Day 4</td><td><strong>Say one no,</strong> or negotiate one deadline. Burnout is maintained by the belief that everything is non-negotiable. Test it once.</td></tr>
    <tr><td>Day 5</td><td><strong>Micro-recovery.</strong> Three five-minute breaks, away from screens, with no phone. Rest that involves scrolling is not rest — measure your energy at 6pm and see.</td></tr>
    <tr><td>Day 6</td><td><strong>Reconnect to one thing you are good at</strong> outside work. Burnout narrows identity down to output; that is what makes a bad quarter feel like a bad life.</td></tr>
    <tr><td>Day 7</td><td><strong>Review and decide.</strong> If the demand side genuinely cannot change, the conversation is with your manager or HR, not with yourself. Many employers we work with fund therapy without ever knowing who used it.</td></tr>
  </table>

  <h2>When a plan like this is not enough</h2>
  <p>Self-help works well for elevated stress and stalls at clinical-level distress. Book time with a clinical psychologist if any of these apply:</p>
  <ul>
    <li>You have run a structured week honestly and nothing has moved.</li>
    <li>Symptoms have persisted most days for more than a month.</li>
    <li>Work, relationships or parenting are visibly affected.</li>
    <li>You are using alcohol, substances or food to get through the evenings.</li>
    <li>You have had thoughts of not being here, or of hurting yourself — in this case, today, not eventually.</li>
  </ul>

  <div class="lm-guide__box lm-guide__box--warn">
    <p><strong>Immediate support, any time.</strong> Tele-MANAS (Government of India, 24×7, free):
    <strong>14416</strong> or 1-800-891-4416. AASRA (24×7): <strong>+91 98204 66726</strong>.
    iCall (TISS), Mon–Sat 10am–8pm: <strong>+91 91529 87821</strong>. Emergency: <strong>112</strong>.</p>
  </div>

  <h2>What therapy at eMbrace looks like</h2>
  <p>
    Sessions are with RCI-certified clinical psychologists, in English or Hindi, online or at our Vasant Kunj,
    Gurugram or Malviya Nagar centres. Work for anxiety, low mood and burnout is structured and goal-led —
    typically six to twelve sessions, weekly to start and then spaced out, with fees quoted upfront.
  </p>
  <ul>
    <li><strong>Free 15-minute call</strong> — <a href="/appointment.php">book here</a> or WhatsApp +91 99715 76800.</li>
    <li><strong>Further reading</strong> — <a href="/individuals.php">Individual therapy</a> &nbsp;·&nbsp; <a href="/couples.php">Couples therapy</a> &nbsp;·&nbsp; <a href="/corporate.php">Corporate wellness</a>.</li>
  </ul>

  <div class="lm-guide__foot">
    <p><strong>Important.</strong> This plan is educational and is not treatment, therapy or a diagnosis.
    Several medical conditions — thyroid disorders, anaemia, vitamin B12 and D deficiency, sleep apnoea and
    some medication side effects — produce identical symptoms and are worth ruling out with your doctor.</p>
    <p>&copy; eMbrace, a unit of SMD Wellness. Share this plan freely — please keep it intact and credited.</p>
  </div>

  <div class="lm-noprint" style="margin-top:2.5rem;display:flex;flex-wrap:wrap;gap:.75rem">
    <a class="lm-btn lm-btn--primary" href="/appointment.php">Book a free 15-minute call</a>
    <a class="lm-btn lm-btn--ghost" href="/resources/adult-stress-check.php">Re-take the self-check</a>
    <a class="lm-btn lm-btn--ghost" href="/adult-mental-health/adult-counselling.php">Adult mental health hub</a>
  </div>

</article>
</body>
</html>
