<!DOCTYPE html>

<html lang="en-IN">
<head>
<meta charset="utf-8"/>
<link href="/Favicon.png" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Find eMbrace psychology and therapy services near you: child psychologists, autism and ADHD assessments, speech and occupational therapy across Delhi NCR." name="description"/>
<meta content="index, follow" name="robots"/>
<link href="https://embracelives.com/locations" rel="canonical"/>
<meta content="website" property="og:type"/>
<meta content="https://embracelives.com/locations" property="og:url"/>
<meta content="Psychology &amp; Therapy Locations Across Delhi NCR | eMbrace" property="og:title"/>
<meta content="Find eMbrace psychology, assessment and therapy services near you across Delhi, South Delhi, Gurgaon and Noida." property="og:description"/>
<meta content="https://embracelives.com/og-image.png" property="og:image"/>
<meta content="eMbrace Lives" property="og:site_name"/>
<meta content="en_IN" property="og:locale"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Psychology &amp; Therapy Locations Across Delhi NCR | eMbrace" name="twitter:title"/>
<meta content="Find eMbrace psychology, assessment and therapy services near you across Delhi, South Delhi, Gurgaon and Noida." name="twitter:description"/>
<meta content="https://embracelives.com/og-image.png" name="twitter:image"/>
<title>Psychology &amp; Therapy Locations Across Delhi NCR | eMbrace</title>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect"/>
<link href="/_external/fonts.googleapis.com/css2_4d2f350a.css" rel="stylesheet"/>
<link href="/assets/index-B-kGA3UA.css" rel="stylesheet"/>
<style>
      .breadcrumbs { background: linear-gradient(to right, #f8fafc, #f1f5f9); }
      .breadcrumbs a { color: #234394; transition: color 0.2s; }
      .breadcrumbs a:hover { color: #1a1a2e; text-decoration: underline; }
      .hero-tag { background: linear-gradient(135deg, #234394, #1e3a8a) !important; color: white !important; box-shadow: 0 2px 4px rgba(35,67,148,0.2); }
      .cta-card { background: linear-gradient(135deg, #fef9e7 0%, #fef3c7 50%, #fff8e1 100%); border: 1px solid #fde68a; border-radius: 2rem; padding: 2.5rem 2rem; text-align: center; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }

      /* Area cards — scoped so they do not depend on purged Tailwind utilities. */
      .emb-areas { display: grid; grid-template-columns: repeat(1, minmax(0, 1fr)); gap: 1.5rem; }
      @media (min-width: 640px) { .emb-areas { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
      @media (min-width: 1024px) { .emb-areas { grid-template-columns: repeat(3, minmax(0, 1fr)); } }
      .emb-area { background: #F9FBFF; border: 1px solid #E0E6F0; border-radius: 1.5rem; padding: 1.75rem; transition: box-shadow .2s, border-color .2s; }
      .emb-area:hover { border-color: #c7d6f0; box-shadow: 0 8px 20px -8px rgba(35,67,148,0.18); }
      .emb-area__name { display: flex; align-items: center; gap: .5rem; font-size: 1.125rem; font-weight: 800; color: #234394; margin-bottom: .25rem; }
      .emb-area__count { font-size: .75rem; font-weight: 600; color: #64748b; margin-bottom: 1rem; }
      .emb-area__links { list-style: none; padding: 0; margin: 0; }
      .emb-area__links li { margin-bottom: .4rem; }
      .emb-area__links a { display: block; font-size: .8125rem; color: #475569; text-decoration: none; padding: .3rem .5rem; border-radius: .5rem; transition: background .15s, color .15s; }
      .emb-area__links a:hover, .emb-area__links a:focus-visible { background: #E7F7FF; color: #234394; }
    </style>
<link href="/assets/lead-magnets.css" rel="stylesheet"/>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "BreadcrumbList",
      "@id": "https://embracelives.com/locations#breadcrumb",
      "itemListElement": [
        {
          "@type": "ListItem",
          "position": 1,
          "name": "Home",
          "item": "https://embracelives.com/"
        },
        {
          "@type": "ListItem",
          "position": 2,
          "name": "Locations"
        }
      ]
    },
    {
      "@type": "CollectionPage",
      "@id": "https://embracelives.com/locations#webpage",
      "url": "https://embracelives.com/locations",
      "name": "Psychology & Therapy Locations Across Delhi NCR | eMbrace",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "Find eMbrace psychology and therapy services near you: child psychologists, autism and ADHD assessments, speech and occupational therapy across Delhi NCR.",
      "breadcrumb": {
        "@id": "https://embracelives.com/locations#breadcrumb"
      }
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
<body style="overflow: auto">
<div id="root">
<?php include __DIR__ . '/../components/header.php'; ?>
<div class="px-6 md:px-16 py-12 md:py-20 bg-gradient-to-b from-[#E7F7FF] to-white relative overflow-hidden flex items-center justify-center border-b border-[#E0E6F0]">
<div class="absolute w-24 h-24 bg-purple-200/50 rounded-full -left-10 top-10 hidden md:block"></div>
<div class="absolute w-32 h-32 bg-blue-100/60 rounded-full -right-12 bottom-5 hidden md:block"></div>
<div class="w-full max-w-7xl mx-auto text-center">
<span class="inline-block px-5 py-1.5 text-xs font-bold rounded-full hero-tag mb-5 tracking-wider uppercase shadow-sm">Our Locations</span>
<h1 class="text-3xl md:text-5xl font-extrabold text-[#234394] leading-tight mb-4">Therapy &amp; Assessment Services Across Delhi NCR</h1>
<p class="text-base md:text-lg text-gray-600 max-w-3xl mx-auto italic">Child psychology, autism and ADHD assessment, speech therapy, occupational therapy and special education — close to where you live.</p>
<div class="mt-8 flex justify-center">
<a href="/appointment" class="inline-block bg-[#234394] hover:bg-[#1e3a80] text-white font-semibold px-8 py-3 rounded-full shadow-lg transition-all transform hover:scale-105 cursor-pointer">
              Book a Consultation
            </a>
</div>
</div>
</div>
<div class="py-3 px-6 md:px-16 border-b border-gray-100 text-xs md:text-sm text-gray-500 breadcrumbs">
<div class="max-w-7xl mx-auto flex items-center gap-2">
<a class="hover:text-[#234394]" href="/">Home</a>
<span>/</span>
<span class="text-gray-800 font-medium">Locations</span>
</div>
</div>
<div class="px-6 md:px-16 py-12 bg-white">
<div class="max-w-7xl mx-auto">
<div class="max-w-3xl mb-10">
<h2 class="text-2xl md:text-3xl font-extrabold text-[#1e293b] mb-3">Find eMbrace near you</h2>
<p class="text-base text-gray-600 leading-relaxed">
          Our clinical psychologists, child psychologists, speech-language pathologists and occupational
          therapists support families across Delhi and the wider NCR. Choose your area below to see the
          full range of assessment and therapy services available there, or
          <a class="text-[#234394] font-semibold hover:underline" href="/contact-us">get in touch</a>
          if you would like help deciding which service fits your child or family.
        </p>
</div>

<!-- LOCATIONS-HUB:START (generated by generate-locations-nav.js — do not edit by hand) -->
<div class="emb-areas">
<div class="emb-area">
<h3 class="emb-area__name">Delhi</h3>
<p class="emb-area__count">20 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-delhi">Child Psychologist in Delhi</a></li>
  <li><a href="/locations/child-counselling-in-delhi">Child Counselling in Delhi</a></li>
  <li><a href="/locations/teen-counselling-in-delhi">Teen Counselling in Delhi</a></li>
  <li><a href="/locations/adult-counselling-in-delhi">Adult Counselling in Delhi</a></li>
  <li><a href="/locations/autism-assessment-in-delhi">Autism Assessment in Delhi</a></li>
  <li><a href="/locations/autism-therapy-in-delhi">Autism Therapy in Delhi</a></li>
  <li><a href="/locations/adhd-assessment-in-delhi">ADHD Assessment in Delhi</a></li>
  <li><a href="/locations/learning-disability-assessment-in-delhi">Learning Disability Assessment in Delhi</a></li>
  <li><a href="/locations/speech-therapy-in-delhi">Speech Therapy in Delhi</a></li>
  <li><a href="/locations/occupational-therapy-in-delhi">Occupational Therapy in Delhi</a></li>
  <li><a href="/locations/special-education-in-delhi">Special Education in Delhi</a></li>
  <li><a href="/locations/developmental-delay-treatment-in-delhi">Developmental Delay Treatment in Delhi</a></li>
  <li><a href="/locations/intellectual-disability-treatment-in-delhi">Intellectual Disability Treatment in Delhi</a></li>
  <li><a href="/locations/down-syndrome-treatment-in-delhi">Down Syndrome Treatment in Delhi</a></li>
  <li><a href="/locations/oral-motor-therapy-in-delhi">Oral Motor Delay Treatment in Delhi</a></li>
  <li><a href="/locations/aba-therapy-in-delhi">ABA Therapy in Delhi</a></li>
  <li><a href="/locations/physiotherapy-in-delhi">Physiotherapy in Delhi</a></li>
  <li><a href="/locations/pediatric-neurologist-in-delhi">Pediatric Neurologist in Delhi</a></li>
  <li><a href="/locations/developmental-pediatrician-in-delhi">Developmental Pediatrician in Delhi</a></li>
  <li><a href="/locations/child-development-centre-in-delhi">Child Development Centre in Delhi</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">South Delhi</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-south-delhi">Child Psychologist in South Delhi</a></li>
  <li><a href="/locations/child-counselling-in-south-delhi">Child Counselling in South Delhi</a></li>
  <li><a href="/locations/teen-counselling-in-south-delhi">Teen Counselling in South Delhi</a></li>
  <li><a href="/locations/adult-counselling-in-south-delhi">Adult Counselling in South Delhi</a></li>
  <li><a href="/locations/autism-assessment-in-south-delhi">Autism Assessment in South Delhi</a></li>
  <li><a href="/locations/autism-therapy-in-south-delhi">Autism Therapy in South Delhi</a></li>
  <li><a href="/locations/adhd-assessment-in-south-delhi">ADHD Assessment in South Delhi</a></li>
  <li><a href="/locations/learning-disability-assessment-in-south-delhi">Learning Disability Assessment in South Delhi</a></li>
  <li><a href="/locations/speech-therapy-in-south-delhi">Speech Therapy in South Delhi</a></li>
  <li><a href="/locations/occupational-therapy-in-south-delhi">Occupational Therapy in South Delhi</a></li>
  <li><a href="/locations/special-education-in-south-delhi">Special Education in South Delhi</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Saket</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-saket">Child Psychologist in Saket</a></li>
  <li><a href="/locations/child-counselling-in-saket">Child Counselling in Saket</a></li>
  <li><a href="/locations/teen-counselling-in-saket">Teen Counselling in Saket</a></li>
  <li><a href="/locations/adult-counselling-in-saket">Adult Counselling in Saket</a></li>
  <li><a href="/locations/autism-assessment-in-saket">Autism Assessment in Saket</a></li>
  <li><a href="/locations/autism-therapy-in-saket">Autism Therapy in Saket</a></li>
  <li><a href="/locations/adhd-assessment-in-saket">ADHD Assessment in Saket</a></li>
  <li><a href="/locations/learning-disability-assessment-in-saket">Learning Disability Assessment in Saket</a></li>
  <li><a href="/locations/speech-therapy-in-saket">Speech Therapy in Saket</a></li>
  <li><a href="/locations/occupational-therapy-in-saket">Occupational Therapy in Saket</a></li>
  <li><a href="/locations/special-education-in-saket">Special Education in Saket</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Hauz Khas</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-hauz-khas">Child Psychologist in Hauz Khas</a></li>
  <li><a href="/locations/child-counselling-in-hauz-khas">Child Counselling in Hauz Khas</a></li>
  <li><a href="/locations/teen-counselling-in-hauz-khas">Teen Counselling in Hauz Khas</a></li>
  <li><a href="/locations/adult-counselling-in-hauz-khas">Adult Counselling in Hauz Khas</a></li>
  <li><a href="/locations/autism-assessment-in-hauz-khas">Autism Assessment in Hauz Khas</a></li>
  <li><a href="/locations/autism-therapy-in-hauz-khas">Autism Therapy in Hauz Khas</a></li>
  <li><a href="/locations/adhd-assessment-in-hauz-khas">ADHD Assessment in Hauz Khas</a></li>
  <li><a href="/locations/learning-disability-assessment-in-hauz-khas">Learning Disability Assessment in Hauz Khas</a></li>
  <li><a href="/locations/speech-therapy-in-hauz-khas">Speech Therapy in Hauz Khas</a></li>
  <li><a href="/locations/occupational-therapy-in-hauz-khas">Occupational Therapy in Hauz Khas</a></li>
  <li><a href="/locations/special-education-in-hauz-khas">Special Education in Hauz Khas</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Green Park</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-green-park">Child Psychologist in Green Park</a></li>
  <li><a href="/locations/child-counselling-in-green-park">Child Counselling in Green Park</a></li>
  <li><a href="/locations/teen-counselling-in-green-park">Teen Counselling in Green Park</a></li>
  <li><a href="/locations/adult-counselling-in-green-park">Adult Counselling in Green Park</a></li>
  <li><a href="/locations/autism-assessment-in-green-park">Autism Assessment in Green Park</a></li>
  <li><a href="/locations/autism-therapy-in-green-park">Autism Therapy in Green Park</a></li>
  <li><a href="/locations/adhd-assessment-in-green-park">ADHD Assessment in Green Park</a></li>
  <li><a href="/locations/learning-disability-assessment-in-green-park">Learning Disability Assessment in Green Park</a></li>
  <li><a href="/locations/speech-therapy-in-green-park">Speech Therapy in Green Park</a></li>
  <li><a href="/locations/occupational-therapy-in-green-park">Occupational Therapy in Green Park</a></li>
  <li><a href="/locations/special-education-in-green-park">Special Education in Green Park</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Greater Kailash</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-greater-kailash">Child Psychologist in Greater Kailash</a></li>
  <li><a href="/locations/child-counselling-in-greater-kailash">Child Counselling in Greater Kailash</a></li>
  <li><a href="/locations/teen-counselling-in-greater-kailash">Teen Counselling in Greater Kailash</a></li>
  <li><a href="/locations/adult-counselling-in-greater-kailash">Adult Counselling in Greater Kailash</a></li>
  <li><a href="/locations/autism-assessment-in-greater-kailash">Autism Assessment in Greater Kailash</a></li>
  <li><a href="/locations/autism-therapy-in-greater-kailash">Autism Therapy in Greater Kailash</a></li>
  <li><a href="/locations/adhd-assessment-in-greater-kailash">ADHD Assessment in Greater Kailash</a></li>
  <li><a href="/locations/learning-disability-assessment-in-greater-kailash">Learning Disability Assessment in Greater Kailash</a></li>
  <li><a href="/locations/speech-therapy-in-greater-kailash">Speech Therapy in Greater Kailash</a></li>
  <li><a href="/locations/occupational-therapy-in-greater-kailash">Occupational Therapy in Greater Kailash</a></li>
  <li><a href="/locations/special-education-in-greater-kailash">Special Education in Greater Kailash</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Defence Colony</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-defence-colony">Child Psychologist in Defence Colony</a></li>
  <li><a href="/locations/child-counselling-in-defence-colony">Child Counselling in Defence Colony</a></li>
  <li><a href="/locations/teen-counselling-in-defence-colony">Teen Counselling in Defence Colony</a></li>
  <li><a href="/locations/adult-counselling-in-defence-colony">Adult Counselling in Defence Colony</a></li>
  <li><a href="/locations/autism-assessment-in-defence-colony">Autism Assessment in Defence Colony</a></li>
  <li><a href="/locations/autism-therapy-in-defence-colony">Autism Therapy in Defence Colony</a></li>
  <li><a href="/locations/adhd-assessment-in-defence-colony">ADHD Assessment in Defence Colony</a></li>
  <li><a href="/locations/learning-disability-assessment-in-defence-colony">Learning Disability Assessment in Defence Colony</a></li>
  <li><a href="/locations/speech-therapy-in-defence-colony">Speech Therapy in Defence Colony</a></li>
  <li><a href="/locations/occupational-therapy-in-defence-colony">Occupational Therapy in Defence Colony</a></li>
  <li><a href="/locations/special-education-in-defence-colony">Special Education in Defence Colony</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Vasant Kunj</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-vasant-kunj">Child Psychologist in Vasant Kunj</a></li>
  <li><a href="/locations/child-counselling-in-vasant-kunj">Child Counselling in Vasant Kunj</a></li>
  <li><a href="/locations/teen-counselling-in-vasant-kunj">Teen Counselling in Vasant Kunj</a></li>
  <li><a href="/locations/adult-counselling-in-vasant-kunj">Adult Counselling in Vasant Kunj</a></li>
  <li><a href="/locations/autism-assessment-in-vasant-kunj">Autism Assessment in Vasant Kunj</a></li>
  <li><a href="/locations/autism-therapy-in-vasant-kunj">Autism Therapy in Vasant Kunj</a></li>
  <li><a href="/locations/adhd-assessment-in-vasant-kunj">ADHD Assessment in Vasant Kunj</a></li>
  <li><a href="/locations/learning-disability-assessment-in-vasant-kunj">Learning Disability Assessment in Vasant Kunj</a></li>
  <li><a href="/locations/speech-therapy-in-vasant-kunj">Speech Therapy in Vasant Kunj</a></li>
  <li><a href="/locations/occupational-therapy-in-vasant-kunj">Occupational Therapy in Vasant Kunj</a></li>
  <li><a href="/locations/special-education-in-vasant-kunj">Special Education in Vasant Kunj</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Gurgaon</h3>
<p class="emb-area__count">20 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-gurgaon">Child Psychologist in Gurgaon</a></li>
  <li><a href="/locations/child-counselling-in-gurgaon">Child Counselling in Gurgaon</a></li>
  <li><a href="/locations/teen-counselling-in-gurgaon">Teen Counselling in Gurgaon</a></li>
  <li><a href="/locations/adult-counselling-in-gurgaon">Adult Counselling in Gurgaon</a></li>
  <li><a href="/locations/autism-assessment-in-gurgaon">Autism Assessment in Gurgaon</a></li>
  <li><a href="/locations/autism-therapy-in-gurgaon">Autism Therapy in Gurgaon</a></li>
  <li><a href="/locations/adhd-assessment-in-gurgaon">ADHD Assessment in Gurgaon</a></li>
  <li><a href="/locations/learning-disability-assessment-in-gurgaon">Learning Disability Assessment in Gurgaon</a></li>
  <li><a href="/locations/speech-therapy-in-gurgaon">Speech Therapy in Gurgaon</a></li>
  <li><a href="/locations/occupational-therapy-in-gurgaon">Occupational Therapy in Gurgaon</a></li>
  <li><a href="/locations/special-education-in-gurgaon">Special Education in Gurgaon</a></li>
  <li><a href="/locations/developmental-delay-treatment-in-gurgaon">Developmental Delay Treatment in Gurgaon</a></li>
  <li><a href="/locations/intellectual-disability-treatment-in-gurgaon">Intellectual Disability Treatment in Gurgaon</a></li>
  <li><a href="/locations/down-syndrome-treatment-in-gurgaon">Down Syndrome Treatment in Gurgaon</a></li>
  <li><a href="/locations/oral-motor-therapy-in-gurgaon">Oral Motor Delay Treatment in Gurgaon</a></li>
  <li><a href="/locations/aba-therapy-in-gurgaon">ABA Therapy in Gurgaon</a></li>
  <li><a href="/locations/physiotherapy-in-gurgaon">Physiotherapy in Gurgaon</a></li>
  <li><a href="/locations/pediatric-neurologist-in-gurgaon">Pediatric Neurologist in Gurgaon</a></li>
  <li><a href="/locations/developmental-pediatrician-in-gurgaon">Developmental Pediatrician in Gurgaon</a></li>
  <li><a href="/locations/child-development-centre-in-gurgaon">Child Development Centre in Gurgaon</a></li>
</ul>
</div>
<div class="emb-area">
<h3 class="emb-area__name">Noida</h3>
<p class="emb-area__count">11 services available</p>
<ul class="emb-area__links">
  <li><a href="/locations/child-psychologist-in-noida">Child Psychologist in Noida</a></li>
  <li><a href="/locations/child-counselling-in-noida">Child Counselling in Noida</a></li>
  <li><a href="/locations/teen-counselling-in-noida">Teen Counselling in Noida</a></li>
  <li><a href="/locations/adult-counselling-in-noida">Adult Counselling in Noida</a></li>
  <li><a href="/locations/autism-assessment-in-noida">Autism Assessment in Noida</a></li>
  <li><a href="/locations/autism-therapy-in-noida">Autism Therapy in Noida</a></li>
  <li><a href="/locations/adhd-assessment-in-noida">ADHD Assessment in Noida</a></li>
  <li><a href="/locations/learning-disability-assessment-in-noida">Learning Disability Assessment in Noida</a></li>
  <li><a href="/locations/speech-therapy-in-noida">Speech Therapy in Noida</a></li>
  <li><a href="/locations/occupational-therapy-in-noida">Occupational Therapy in Noida</a></li>
  <li><a href="/locations/special-education-in-noida">Special Education in Noida</a></li>
</ul>
</div>
</div>
<!-- LOCATIONS-HUB:END -->

<div class="cta-card my-14">
<h3 class="text-xl md:text-2xl font-bold text-gray-800 mb-3">Not sure which service you need?</h3>
<p class="text-sm md:text-base text-gray-600 mb-6 max-w-xl mx-auto">Speak with our intake team — we will guide you to the right assessment or therapy pathway and the centre closest to you.</p>
<a href="/appointment" class="inline-block bg-[#234394] text-white px-8 py-3 rounded-full hover:bg-blue-800 font-semibold cursor-pointer shadow">
            Schedule an Appointment
          </a>
</div>
</div>
</div>
<?php include __DIR__ . '/../components/lead-magnet-band-child.php'; ?>
<?php include __DIR__ . '/../components/footer.php'; ?>
</div>
<script src="/assets/interactive.js"></script>
<script src="/assets/lead-magnets.js"></script>
</body>
</html>
