<!DOCTYPE html>
<html lang="en-IN">
<head>
<meta charset="utf-8"/>
<link href="/Favicon.png" rel="icon" type="image/svg+xml"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Physiotherapy Clinic in Delhi at our two Delhi centres: paediatric movement, tone, balance and coordination, plus adults. Free 15-minute intake call available." name="description"/>
<meta content="index, follow" name="robots"/>
<link href="https://embracelives.com/locations/physiotherapy-in-delhi" rel="canonical"/>
<!-- Open Graph -->
<meta content="website" property="og:type"/>
<meta content="https://embracelives.com/locations/physiotherapy-in-delhi" property="og:url"/>
<meta content="Physiotherapy Clinic in Delhi | eMbrace Delhi NCR Centres" property="og:title"/>
<meta content="Physiotherapy Clinic in Delhi at our two Delhi centres: paediatric movement, tone, balance and coordination, plus adults. Free 15-minute intake call available." property="og:description"/>
<meta content="https://embracelives.com/og-image.png" property="og:image"/>
<meta content="1200" property="og:image:width"/>
<meta content="630" property="og:image:height"/>
<meta content="eMbrace Lives" property="og:site_name"/>
<meta content="en_IN" property="og:locale"/>
<!-- Twitter Card -->
<meta content="summary_large_image" name="twitter:card"/>
<meta content="Physiotherapy Clinic in Delhi | eMbrace Delhi NCR Centres" name="twitter:title"/>
<meta content="Physiotherapy Clinic in Delhi at our two Delhi centres: paediatric movement, tone, balance and coordination, plus adults. Free 15-minute intake call available." name="twitter:description"/>
<meta content="https://embracelives.com/og-image.png" name="twitter:image"/>
<title>Physiotherapy Clinic in Delhi | eMbrace Delhi NCR Centres</title>
<link href="https://fonts.googleapis.com" rel="preconnect"/>
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Inter:wght@400;500;600&display=swap" rel="stylesheet" />
<link href="/assets/index-B-kGA3UA.css" rel="stylesheet"/>
<link href="/assets/lead-magnets.css" rel="stylesheet"/>
<style>
  body, h1, h2, h3, h4, h5, h6, p, a, span, div, button, input { font-family: 'Outfit', sans-serif; }
  .breadcrumbs { background: linear-gradient(to right, #f8fafc, #f1f5f9); }
  .breadcrumbs a { color: #234394; transition: color 0.2s; }
  .breadcrumbs a:hover { color: #1a1a2e; text-decoration: underline; }
  .article-content h2 { color: #1e293b; font-weight: 800; font-size: 1.65rem; margin-top: 2.5rem; margin-bottom: 0.75rem; letter-spacing: -0.02em; }
  .article-content h3 { color: #334155; font-weight: 700; font-size: 1.25rem; margin-top: 2rem; margin-bottom: 0.5rem; }
  .article-content p { color: #475569; line-height: 1.8; margin-bottom: 1.25rem; font-size: 1rem; }
  .article-content ul { list-style: none; padding-left: 0; margin-bottom: 1.5rem; }
  .article-content ul li { position: relative; padding-left: 1.75rem; margin-bottom: 0.75rem; color: #475569; line-height: 1.7; }
  .article-content ul li::before { content: "\25B8"; position: absolute; left: 0; color: #234394; font-weight: 700; font-size: 1rem; }
  .key-points-card { background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%); border: 1px solid #e2e8f0; border-radius: 1.5rem; padding: 2rem; }
  .key-points-card ul { margin-bottom: 0 !important; }
  .key-points-card ul li { padding-left: 2.25rem !important; margin-bottom: 1rem !important; }
  .faq-item { border-bottom: 1px solid #e2e8f0; transition: background 0.2s; }
  .faq-item:hover { background: #f8fafc; }
  .faq-item button { padding: 1.25rem 1rem; border-radius: 0.75rem; }
  .faq-icon { width: 1.25rem; height: 1.25rem; flex: none; transition: transform 0.25s ease; }
  .faq-answer { max-height: 0; overflow: hidden; transition: max-height 0.3s ease; }
  .side-menu a { display: block; padding: 0.5rem 0.75rem; border-radius: 0.5rem; color: #475569; font-size: 0.9rem; transition: all 0.2s; }
  .side-menu a:hover { background: rgba(35,67,148,0.08); color: #234394; }
  .side-menu a.is-current { background: #234394; color: #fff; font-weight: 600; }

</style>
<!-- SCHEMA:START (generated by generate-schema.js — do not edit by hand) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "ImageObject",
      "@id": "https://embracelives.com/#logo",
      "url": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "contentUrl": "https://embracelives.com/assets/Logo-DrHvIBUF.svg",
      "caption": "eMbrace"
    },
    {
      "@type": [
        "MedicalBusiness",
        "MedicalOrganization"
      ],
      "@id": "https://embracelives.com/#organization",
      "name": "eMbrace",
      "alternateName": "eMbrace Lives",
      "legalName": "eMbrace, a unit of SMD Wellness",
      "url": "https://embracelives.com/",
      "logo": {
        "@id": "https://embracelives.com/#logo"
      },
      "image": {
        "@id": "https://embracelives.com/#logo"
      },
      "description": "Psychology and mental health practice in Delhi NCR offering evidence-based therapy, assessments and neurodevelopmental care for children, adolescents and adults.",
      "telephone": "+91-9971576800",
      "email": "info@embracelives.com",
      "priceRange": "$$",
      "currenciesAccepted": "INR",
      "areaServed": [
        {
          "@type": "AdministrativeArea",
          "name": "Delhi NCR"
        },
        {
          "@type": "Place",
          "name": "Delhi"
        },
        {
          "@type": "Place",
          "name": "South Delhi"
        },
        {
          "@type": "Place",
          "name": "Saket"
        },
        {
          "@type": "Place",
          "name": "Hauz Khas"
        },
        {
          "@type": "Place",
          "name": "Green Park"
        },
        {
          "@type": "Place",
          "name": "Greater Kailash"
        },
        {
          "@type": "Place",
          "name": "Defence Colony"
        },
        {
          "@type": "Place",
          "name": "Vasant Kunj"
        },
        {
          "@type": "Place",
          "name": "Gurgaon"
        },
        {
          "@type": "Place",
          "name": "Noida"
        }
      ],
      "medicalSpecialty": [
        "Psychiatric",
        "Pediatric"
      ],
      "availableService": [
        {
          "@type": "MedicalTherapy",
          "name": "Child Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Clinical Psychology"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Autism Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "ADHD Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Learning Disability Assessment"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Speech and Language Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Occupational Therapy"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Special Education"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Teen Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Adult Counselling"
        },
        {
          "@type": "MedicalTherapy",
          "name": "Couples Therapy"
        }
      ],
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
        "addressLocality": "New Delhi",
        "addressRegion": "Delhi",
        "postalCode": "110070",
        "addressCountry": "IN"
      },
      "location": [
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#vasant-kunj",
          "name": "eMbrace — Vasant Kunj Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "C-7, Sector C, Pocket 5, Basement, Grand Vasant Kunj",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110070",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#gurugram",
          "name": "eMbrace — Gurugram Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "710, Dlf City Court, Mehrauli-Gurgaon Rd, Nathupur, Sector 24",
            "addressLocality": "Gurugram",
            "addressRegion": "Haryana",
            "postalCode": "122002",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        },
        {
          "@type": "MedicalClinic",
          "@id": "https://embracelives.com/contact-us#malviya-nagar",
          "name": "eMbrace — Malviya Nagar Centre",
          "parentOrganization": {
            "@id": "https://embracelives.com/#organization"
          },
          "telephone": "+91-9971576800",
          "email": "info@embracelives.com",
          "url": "https://embracelives.com/contact-us",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": "FC-29, Plot No.5, Geetanjali, Near Malviya Nagar Metro Station Gate No.1",
            "addressLocality": "New Delhi",
            "addressRegion": "Delhi",
            "postalCode": "110017",
            "addressCountry": "IN"
          },
          "openingHoursSpecification": [
            {
              "@type": "OpeningHoursSpecification",
              "dayOfWeek": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday"
              ],
              "opens": "10:00",
              "closes": "18:00"
            }
          ]
        }
      ],
      "openingHoursSpecification": [
        {
          "@type": "OpeningHoursSpecification",
          "dayOfWeek": [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday"
          ],
          "opens": "10:00",
          "closes": "18:00"
        }
      ],
      "sameAs": [
        "https://www.linkedin.com/company/embracelives/",
        "https://www.instagram.com/embracelives/",
        "https://www.facebook.com/embracelives22/"
      ]
    },
    {
      "@type": "WebSite",
      "@id": "https://embracelives.com/#website",
      "url": "https://embracelives.com/",
      "name": "eMbrace",
      "publisher": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN"
    },
    {
      "@type": "BreadcrumbList",
      "@id": "https://embracelives.com/locations/physiotherapy-in-delhi#breadcrumb",
      "itemListElement": [
        {
          "@type": "ListItem",
          "position": 1,
          "name": "Home",
          "item": "https://embracelives.com/"
        },
        {
          "@type": "ListItem",
          "position": 2,
          "name": "Physiotherapy",
          "item": "https://embracelives.com/physiotherapy/physiotherapy"
        }
      ]
    },
    {
      "@type": "MedicalWebPage",
      "@id": "https://embracelives.com/locations/physiotherapy-in-delhi#webpage",
      "url": "https://embracelives.com/locations/physiotherapy-in-delhi",
      "name": "Physiotherapy Clinic in Delhi | eMbrace Delhi NCR Centres",
      "isPartOf": {
        "@id": "https://embracelives.com/#website"
      },
      "about": {
        "@id": "https://embracelives.com/#organization"
      },
      "inLanguage": "en-IN",
      "description": "Physiotherapy Clinic in Delhi at our two Delhi centres: paediatric movement, tone, balance and coordination, plus adults. Free 15-minute intake call available.",
      "breadcrumb": {
        "@id": "https://embracelives.com/locations/physiotherapy-in-delhi#breadcrumb"
      }
    },
    {
      "@type": "FAQPage",
      "@id": "https://embracelives.com/locations/physiotherapy-in-delhi#faq",
      "url": "https://embracelives.com/locations/physiotherapy-in-delhi",
      "name": "Physiotherapy Clinic in Delhi | eMbrace Delhi NCR Centres — Frequently Asked Questions",
      "isPartOf": {
        "@id": "https://embracelives.com/locations/physiotherapy-in-delhi#webpage"
      },
      "inLanguage": "en-IN",
      "mainEntity": [
        {
          "@type": "Question",
          "name": "Do you offer physiotherapy in Delhi?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Yes. Families in Delhi are seen at our Vasant Kunj and Malviya Nagar centres, and online where that suits the work. Start with a free 15-minute intake call."
          }
        },
        {
          "@type": "Question",
          "name": "How quickly can we be seen in Delhi?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "The intake call is usually arranged within a few working days. Appointment timing depends on the service and the clinician needed, and we will tell you honestly on the call."
          }
        },
        {
          "@type": "Question",
          "name": "Can we be seen outside school hours?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "We offer later slots and Saturday appointments where availability allows. Tell the intake team what you need and they will work around school."
          }
        },
        {
          "@type": "Question",
          "name": "What is the difference between physiotherapy and occupational therapy?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Physiotherapy focuses on gross motor skills, strength, tone and mobility. Occupational therapy focuses on fine motor skills, sensory processing and daily living tasks. Many children benefit from both."
          }
        },
        {
          "@type": "Question",
          "name": "My child walks on their toes. Does that need treatment?",
          "acceptedAnswer": {
            "@type": "Answer",
            "text": "Sometimes. Occasional toe walking in young children is common, but persistent toe walking, tight calf muscles or a one-sided pattern is worth assessing properly."
          }
        }
      ]
    },
    {
      "@type": "Service",
      "@id": "https://embracelives.com/locations/physiotherapy-in-delhi#service",
      "name": "Physiotherapy in Delhi",
      "serviceType": "Physiotherapy",
      "provider": {
        "@id": "https://embracelives.com/#organization"
      },
      "areaServed": {
        "@type": "Place",
        "name": "Delhi, India"
      },
      "availableChannel": {
        "@type": "ServiceChannel",
        "serviceUrl": "https://embracelives.com/locations/physiotherapy-in-delhi",
        "servicePhone": "+91-9971576800"
      },
      "audience": {
        "@type": "PeopleAudience",
        "audienceType": "Children, adolescents and adults"
      }
    }
  ]
}
</script>
<!-- SCHEMA:END -->
</head>
<body class="overflow-x-hidden">
<div id="root" class="overflow-x-hidden">
<?php include __DIR__ . '/../components/header.php'; ?>
<div class="px-4 md:px-8 lg:px-16 py-14 md:py-20 bg-gradient-to-b from-[#E7F7FF] to-[#FFFFFF] text-center">
  <div class="max-w-4xl mx-auto">
    <span class="inline-block bg-[#234394] text-white text-xs font-bold tracking-wider uppercase px-4 py-1.5 rounded-full mb-5">Location Services</span>
    <h1 class="text-3xl md:text-5xl font-extrabold text-[#234394] leading-tight mb-4">Physiotherapy Clinic in Delhi</h1>
    <p class="text-base md:text-lg text-gray-600 max-w-3xl mx-auto">Physiotherapy Clinic for families in Delhi, delivered by the same multidisciplinary team that runs our assessments. This page covers where you will be seen, how to get there and what happens first.</p>
    <a href="/appointment.php" class="inline-block mt-8 px-8 py-3 rounded-full bg-[#234394] text-white font-semibold hover:bg-[#1a3272] transition-colors">Book a free 15-minute call</a>
  </div>
</div>
<div class="py-3 px-6 md:px-16 border-b border-gray-100 text-xs md:text-sm text-gray-500 breadcrumbs">
  <div class="max-w-7xl mx-auto flex items-center gap-2 flex-wrap">
      <a href="/index.php">Home</a><span class="text-gray-300">/</span>
      <a href="/physiotherapy/physiotherapy.php">Physiotherapy</a><span class="text-gray-300">/</span>
      <span class="text-gray-700 font-medium">In Delhi</span>
  </div>
</div>
<div class="px-4 md:px-8 lg:px-16 py-12 bg-white">
  <div class="max-w-7xl mx-auto flex flex-col md:flex-row gap-8 lg:gap-12">
<aside class="md:w-72 flex-shrink-0">
  <div class="bg-white border border-gray-100 rounded-2xl p-5 shadow-sm md:sticky md:top-24 side-menu">
    <h2 class="text-lg font-bold text-[#234394] mb-4 border-b pb-3">Child Development Services</h2>
    <div class="space-y-1">
      <a class="" href="/developmental-delay/developmental-delay-treatment.php">Developmental Delay Treatment</a>
      <a class="" href="/intellectual-disability/intellectual-disability-treatment.php">Intellectual Disability Treatment</a>
      <a class="" href="/down-syndrome/down-syndrome-treatment.php">Down Syndrome Treatment &amp; Therapy</a>
      <a class="" href="/oral-motor-therapy/oral-motor-therapy.php">Oral Motor Delay Treatment</a>
      <a class="" href="/aba-therapy/aba-therapy.php">ABA Therapy</a>
      <a class="is-current" href="/physiotherapy/physiotherapy.php">Physiotherapy Clinic</a>
      <a class="" href="/pediatric-neurology/pediatric-neurologist.php">Pediatric Neurologist</a>
      <a class="" href="/developmental-pediatrics/developmental-pediatrician.php">Developmental Pediatrician</a>
      <a class="" href="/child-development-centre/child-development-centre.php">Child Development Centre</a>
    </div>
    <h3 class="text-xs font-bold uppercase tracking-wider text-gray-400 mt-6 mb-2">Related</h3>
    <div class="space-y-1">
      <a href="/occupational-therapy/occupational-therapy.php">Occupational Therapy</a>
    </div>
  </div>
</aside>
    <div class="flex-grow max-w-4xl article-content">

<h2>Where you will be seen in Delhi</h2>
<p>Families across Delhi are seen at one of our two Delhi centres. Vasant Kunj sits in South West Delhi at C-7, Sector C, Pocket 5, Grand Vasant Kunj. Malviya Nagar is in South Delhi at FC-29, Plot No. 5, Geetanjali, beside Malviya Nagar Metro Station Gate No. 1, which puts it within reach of Saket, Hauz Khas, Green Park, Greater Kailash and Defence Colony without a long drive.</p>
<p>Sessions can also run online where the work suits it. History-taking, feedback and a good deal of therapy transfer well to video; direct assessment components are done in person.</p>

<h2>What physiotherapy covers here</h2>
<div class="key-points-card my-8">
  <ul>
    <li>Paediatric specialism, from infants with torticollis to school-age coordination difficulties</li>
    <li>Play-based sessions, because a home programme only works if it gets done</li>
    <li>Planned alongside occupational therapy rather than competing with it</li>
    <li>Medical input available in the same team where it is needed</li>
  </ul>
</div>
<p>For the full clinical picture, including what the difficulty is, the signs worth acting on and how treatment is planned, read our <a href="/physiotherapy/physiotherapy.php" class="text-[#234394] font-semibold">Physiotherapy Clinic guide</a>.</p>

<h2>How to start</h2>
<ul>
  <li><strong>Free 15-minute intake call.</strong> A clinician hears your concern and tells you honestly whether an appointment is the right next step. Some calls end with strategies to try at home instead.</li>
  <li><strong>Assessment or first session.</strong> Booked at whichever Delhi centre suits you, at a time that works around school where possible.</li>
  <li><strong>A written plan.</strong> What happens, how often, what to do at home, and what the school is being asked to do.</li>
  <li><strong>Review.</strong> Progress measured against the baseline set at the start, discussed openly with you.</li>
</ul>
<p>Fees are quoted upfront on your intake call, in writing, before you commit to anything.</p>

<h2 class="text-2xl font-bold mt-12 mb-6 text-[#1e293b]">Frequently Asked Questions</h2>
<div class="space-y-2 mb-10">
<div class="faq-item">
  <button class="w-full text-left flex justify-between items-center focus:outline-none faq-btn">
    <span class="font-semibold text-[#1e293b] pr-4">Do you offer physiotherapy in Delhi?</span>
    <svg class="faq-icon" viewBox="0 0 24 24" fill="none" stroke="#234394" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
  </button>
  <div class="faq-answer"><p class="px-4 pb-5 text-gray-600 leading-relaxed">Yes. Families in Delhi are seen at our Vasant Kunj and Malviya Nagar centres, and online where that suits the work. Start with a free 15-minute intake call.</p></div>
</div>
<div class="faq-item">
  <button class="w-full text-left flex justify-between items-center focus:outline-none faq-btn">
    <span class="font-semibold text-[#1e293b] pr-4">How quickly can we be seen in Delhi?</span>
    <svg class="faq-icon" viewBox="0 0 24 24" fill="none" stroke="#234394" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
  </button>
  <div class="faq-answer"><p class="px-4 pb-5 text-gray-600 leading-relaxed">The intake call is usually arranged within a few working days. Appointment timing depends on the service and the clinician needed, and we will tell you honestly on the call.</p></div>
</div>
<div class="faq-item">
  <button class="w-full text-left flex justify-between items-center focus:outline-none faq-btn">
    <span class="font-semibold text-[#1e293b] pr-4">Can we be seen outside school hours?</span>
    <svg class="faq-icon" viewBox="0 0 24 24" fill="none" stroke="#234394" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
  </button>
  <div class="faq-answer"><p class="px-4 pb-5 text-gray-600 leading-relaxed">We offer later slots and Saturday appointments where availability allows. Tell the intake team what you need and they will work around school.</p></div>
</div>
<div class="faq-item">
  <button class="w-full text-left flex justify-between items-center focus:outline-none faq-btn">
    <span class="font-semibold text-[#1e293b] pr-4">What is the difference between physiotherapy and occupational therapy?</span>
    <svg class="faq-icon" viewBox="0 0 24 24" fill="none" stroke="#234394" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
  </button>
  <div class="faq-answer"><p class="px-4 pb-5 text-gray-600 leading-relaxed">Physiotherapy focuses on gross motor skills, strength, tone and mobility. Occupational therapy focuses on fine motor skills, sensory processing and daily living tasks. Many children benefit from both.</p></div>
</div>
<div class="faq-item">
  <button class="w-full text-left flex justify-between items-center focus:outline-none faq-btn">
    <span class="font-semibold text-[#1e293b] pr-4">My child walks on their toes. Does that need treatment?</span>
    <svg class="faq-icon" viewBox="0 0 24 24" fill="none" stroke="#234394" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
  </button>
  <div class="faq-answer"><p class="px-4 pb-5 text-gray-600 leading-relaxed">Sometimes. Occasional toe walking in young children is common, but persistent toe walking, tight calf muscles or a one-sided pattern is worth assessing properly.</p></div>
</div>
</div>

<h2>Other eMbrace services near you</h2>
<ul>
<li><a href="/locations/child-psychologist-in-saket.php" class="text-[#234394]">Child psychology in Saket</a></li>
<li><a href="/locations/child-psychologist-in-hauz-khas.php" class="text-[#234394]">Child psychology in Hauz Khas</a></li>
<li><a href="/locations/child-psychologist-in-green-park.php" class="text-[#234394]">Child psychology in Green Park</a></li>
<li><a href="/locations/child-psychologist-in-greater-kailash.php" class="text-[#234394]">Child psychology in Greater Kailash</a></li>
<li><a href="/locations/child-psychologist-in-defence-colony.php" class="text-[#234394]">Child psychology in Defence Colony</a></li>
<li><a href="/locations/child-psychologist-in-south-delhi.php" class="text-[#234394]">Child psychology in South Delhi</a></li>
<li><a href="/locations/child-psychologist-in-vasant-kunj.php" class="text-[#234394]">Child psychology in Vasant Kunj</a></li>
  <li><a href="/locations/index.php" class="text-[#234394]">View all eMbrace locations</a></li>
</ul>

<div class="pathway-card mt-12 rounded-3xl p-8 bg-gradient-to-br from-[#eef2ff] to-[#e0e7ff] border border-[#c7d2fe]">
  <h2 class="text-xl md:text-2xl font-bold text-gray-800 mb-3">Not sure whether you need this yet?</h2>
  <p class="text-gray-600 mb-6">Start with a free 15-minute intake call. A clinician will tell you honestly whether physiotherapy is the right next step, or whether something else is. There is no obligation and no waiting list to join.</p>
  <div class="flex flex-wrap gap-3">
    <a href="/appointment.php" class="inline-block px-7 py-3 rounded-full bg-[#234394] text-white font-semibold hover:bg-[#1a3272] transition-colors">Book a free call</a>
    <a href="https://wa.me/919971576800" target="_blank" rel="noopener" class="inline-block px-7 py-3 rounded-full bg-white border border-[#c7d2fe] text-[#234394] font-semibold hover:bg-[#f8faff] transition-colors">WhatsApp +91 99715 76800</a>
  </div>
</div>
    </div>
  </div>
</div>
<?php include __DIR__ . '/../components/lead-magnet-band-child.php'; ?>
<?php include __DIR__ . '/../components/footer.php'; ?>
</div>
<script src="/assets/interactive.js"></script>
<script src="/assets/lead-magnets.js"></script>
</body>
</html>
